/*
Copyright (c) 2019-2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

/**
 * Core game logic for Dagon-based applications.
 *
 * Description:
 * The `dagon.game.basegame` module defines the `BaseGame` class, which serves
 * as a basic template for creating a game application using Dagon's built-in
 * world management system.
 *
 * Copyright: Timur Gafarov 2019-2026
 * License: $(LINK2 https://boost.org/LICENSE_1_0.txt, Boost License 1.0).
 * Authors: Timur Gafarov
 */
module dagon.game.basegame;

import dlib.core.memory;
import dlib.core.ownership;
import dlib.container.array;
import dlib.container.dict;
import dlib.filesystem.filesystem;

import dagon.core.application;
import dagon.core.time;
import dagon.core.logger;
import dagon.game.world;
import gscript;

/**
 * Basic game class for Dagon applications.
 *
 * Description:
 * The `BaseGame` class is a subclass of `Application` that provides
 * basic game logic, including world management and scripting.
 */
class BaseGame: Application, GsObject
{
    /// Array of worlds of the game.
    Array!World worlds;
    
    /// Currently active World.
    World activeWorld;
    
    /// GScript3 virtual machine.
    GsVirtualMachine vm;
    
    /// Virtual path to the main script.
    string mainScriptPath = "scripts/main.gsc";
    
    /// Instruction stream for the main script.
    GsInstruction[] mainScriptProgram;
    
    /// Raw bytecode of the main script.
    ubyte[] mainScriptBytecode;
    
    /// GScript properties global to the game object.
    Dict!(GsDynamic, string) gsProperties;
    
    /// Arguments array for calling script event handlers.
    GsDynamic[4] gsEventHandlerArgs;
    
    /**
     * Initializes the `BaseGame` object.
     *
     * Params:
     *   winWidth = Window width in pixels.
     *   winHeight = Window height in pixels.
     *   fullscreen = If true, the application will run in fullscreen mode.
     *   windowTitle = The window title.
     *   args = Command line arguments.
     */
    this(uint winWidth, uint winHeight, bool fullscreen, string windowTitle, string[] args)
    {
        super(winWidth, winHeight, fullscreen, windowTitle, args);
        
        // Initialize VM
        vm = New!GsVirtualMachine(this);
        vm.set("log", GsDynamic(&vmLog));
        vm.set("logDebug", GsDynamic(&vmLogDebug));
        vm.set("logInfo", GsDynamic(&vmLogInfo));
        vm.set("logWarning", GsDynamic(&vmLogWarning));
        vm.set("logError", GsDynamic(&vmLogError));
        vm.set("logFatalError", GsDynamic(&vmLogFatalError));
        vm.set("queueUserEvent", GsDynamic(&vmQueueUserEvent));
        vm.set("send", GsDynamic(&vmSend));
        vm.set("game", GsDynamic(this));
        
        gsProperties = dict!(GsDynamic, string);
        gsEventHandlerArgs[0] = this;
        
        // Load main script
        // TODO: user-defined path from settings.conf
        if (fileExists(mainScriptPath))
        {
            FileStat s;
            if (vfs.stat(mainScriptPath, s))
            {
                size_t size = cast(size_t)s.sizeInBytes;
                if (size > 0)
                {
                    logDebug("Loading ", mainScriptPath, "...");
                    auto istrm = vfs.openForInput(mainScriptPath);
                    mainScriptBytecode = New!(ubyte[])(size);
                    istrm.fillArray(mainScriptBytecode);
                    Delete(istrm);
                    
                    mainScriptProgram = loadBytecode(mainScriptBytecode);
                    if (mainScriptProgram.length)
                    {
                        vm.load(mainScriptProgram);
                        vm.run();
                    }
                }
            }
        }
        else
        {
            logWarning("scripts/main.gsc not found");
        }
    }
    
    /// Destructor. Releases VM and game-owned objects.
    ~this()
    {
        worlds.free();
        if (mainScriptBytecode.length)
            Delete(mainScriptBytecode);
        Delete(gsProperties);
    }
    
    /// Adds a world object to the worlds array.
    World addWorld(World world)
    {
        worlds.append(world);
        return world;
    }
    
    /// Calls script event handler, if it exists.
    void triggerScriptEvent(string name, GsDynamic[] args)
    {
        GsDynamic* eventHandler = name in gsProperties;
        if (eventHandler)
        {
            if (eventHandler.type == GsDynamicType.String)
                vm.call(eventHandler.asString, args);
        }
    }
    
    /**
     * Called every frame to update game logic.
     *
     * Params:
     *   t = Time information for the frame.
     */
    override void onUpdate(Time t)
    {
        if (activeWorld)
            activeWorld.update(t);
        
        gsEventHandlerArgs[1] = GsDynamic(t.delta);
        triggerScriptEvent("onUpdate", gsEventHandlerArgs[0..2]);
    }
    
    /**
     * Key press handler.
     */
    override void onKeyDown(int key)
    {
        gsEventHandlerArgs[1] = GsDynamic(key);
        triggerScriptEvent("onKeyDown", gsEventHandlerArgs[0..2]);
    }
    
    ///
    GsDynamic get(string key)
    {
        switch(key)
        {
            case "activeWorld":
                if (activeWorld)
                    return GsDynamic(activeWorld);
                else
                    return GsDynamic();
            default:
                auto v = key in gsProperties;
                if (v)
                    return *v;
                else
                    return GsDynamic();
        }
    }
    
    ///
    void set(string key, GsDynamic value)
    {
        gsProperties[key] = value;
    }
    
    ///
    bool contains(string key)
    {
        switch(key)
        {
            case "activeWorld": return true;
            default:
                if ((key in gsProperties) !is null)
                    return true;
                else
                    return false;
        }
    }
    
    ///
    void setPrototype(GsObject obj)
    {
        // No-op
    }
    
    ///
    GsDynamic vmLog(GsDynamic[] args)
    {
        auto logLevel = cast(LogLevel)cast(uint)args[1].asNumber;
        auto message = args[2].toString;
        log(logLevel, message);
        return GsDynamic();
    }
    
    ///
    GsDynamic vmLogDebug(GsDynamic[] args)
    {
        auto message = args[1].toString;
        logDebug(message);
        return GsDynamic();
    }
    
    ///
    GsDynamic vmLogInfo(GsDynamic[] args)
    {
        auto message = args[1].toString;
        logInfo(message);
        return GsDynamic();
    }
    
    ///
    GsDynamic vmLogWarning(GsDynamic[] args)
    {
        auto message = args[1].toString;
        logWarning(message);
        return GsDynamic();
    }
    
    ///
    GsDynamic vmLogError(GsDynamic[] args)
    {
        auto message = args[1].toString;
        logError(message);
        return GsDynamic();
    }
    
    ///
    GsDynamic vmLogFatalError(GsDynamic[] args)
    {
        auto message = args[1].toString;
        logFatalError(message);
        return GsDynamic();
    }
    
    ///
    GsDynamic vmQueueUserEvent(GsDynamic[] args)
    {
        int code = cast(int)args[1].asNumber;
        eventManager.queueUserEvent(code);
        return GsDynamic();
    }
    
    ///
    GsDynamic vmSend(GsDynamic[] args)
    {
        auto recipient = args[1].asString;
        auto message = args[2].asString;
        queueMessage(recipient, message, null, 1);
        return GsDynamic();
    }
}
