/*
Copyright (c) 2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module dagon.game.world;

import dlib.core.memory;
import dlib.core.ownership;

import dagon.core.logger;
import dagon.core.event;
import dagon.core.time;
import dagon.core.gpu;
import dagon.graphics.texture;
import dagon.graphics.scene;
import dagon.game.basegame;
//import dagon.resource.asset;
import dagon.resource.image;
import dagon.resource.texture;

class World: EventListener
{
    BaseGame baseGame;
    GPU gpu;
    Scene scene;
    bool recalculateMatrices = true;
    
    ImageConversionOptions defaultImageConversionOptions = {
        compressionFormat: TextureCompressionFormat.None
    };
    
    TextureCreationOptions defaultTextureCreationOptions = {
        generateMipmaps: true,
        repeatUV: true,
        anisotropicFiltering: true
    };
    
    this(BaseGame baseGame)
    {
        super(baseGame.eventManager, baseGame);
        this.baseGame = baseGame;
        this.gpu = baseGame.gpu;
        
        // TODO: init defaultImageConversionOptions and defaultTextureCreationOptions from baseGame settings
    }
    
    void activate()
    {
        baseGame.activeWorld = this;
    }
    
    // TODO: move to AssetManager
    TextureAsset loadTexture(string filename, ImageConversionOptions* conversionOptions, TextureCreationOptions* creationOptions, bool cache = true)
    {
        TextureAsset asset = New!TextureAsset(gpu, this);
        asset.conversionOptions = *conversionOptions;
        asset.creationOptions = *creationOptions;
        asset.cache = cache;
        if (baseGame.fileExists(filename))
            asset.load(filename, baseGame.vfs);
        else
            logError("Can\'t find file ", filename);
        return asset;
    }
    
    TextureAsset loadTexture(string filename, bool cache = true)
    {
        return loadTexture(filename, &defaultImageConversionOptions, &defaultTextureCreationOptions, cache);
    }
    
    // TODO: move to AssetManager
    T loadAsset(T)(string filename)
    {
        T asset = New!T(gpu, this);
        auto istrm = baseGame.vfs.openForInput(filename);
        if (baseGame.fileExists(filename))
            asset.load(filename, istrm, baseGame.vfs);
        else
            logError("Can\'t find file ", filename);
        Delete(istrm);
        return asset;
    }
    
    void update(Time t)
    {
        processEvents();
        
        onUpdate(t);
        
        if (scene)
        {
            foreach(entity; scene.entities)
            {
                entity.update(t);
            }
        }
        
        onPostUpdate(t);
        
        if (scene)
        {
            foreach(entity; scene.entities)
            {
                entity.postUpdate(t);
            }
        }
    }
    
    void onUpdate(Time t)
    {
        //
    }
    
    void onPostUpdate(Time t)
    {
        //
    }
}
