/*
Copyright (c) 2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module dagon.render.postprocessing.passes.npr;

import std.math;

import dlib.core.memory;
import dlib.core.ownership;
import dlib.math.vector;
import dlib.math.matrix;
import dlib.image.color;

import dagon.core.sdl3;
import dagon.core.gpu;
import dagon.core.crashhandler;
import dagon.core.logger;
import dagon.core.time;
import dagon.graphics.state;
import dagon.graphics.mesh;
import dagon.graphics.shapes;
import dagon.graphics.entity;
import dagon.resource.shader;
import dagon.render.renderer;
import dagon.render.pass;
import dagon.render.view;
import dagon.render.deferred.gbuffer;
import dagon.render.postprocessing.context;

struct NPRShaderVertexUniformBuffer
{
    Matrix4x4f modelViewMatrix;
    Matrix4x4f normalMatrix;
    Matrix4x4f projectionMatrix;
    Matrix4x4f prevModelViewMatrix;
}

struct NPRShaderFragmentUniformBuffer
{
    Vector4f resolution;
    Color4f baseColor;
    uint[4] iparams;
}

class NPRShader: Shader
{
   protected:
    NPRShaderVertexUniformBuffer vsUBO;
    NPRShaderFragmentUniformBuffer fsUBO;
    
   public:
    this(GPU gpu, Owner owner)
    {
        super(gpu, owner);
        
        vertexModule = New!ShaderModule(gpu, this);
        vertexModule.create("NPR.vert.glsl", "data/__internal/shaders/NPR/NPR.vert.glsl",
            ShaderSourceType.File, ShaderLanguage.GLSL, PipelineStage.Vertex);
        
        fragmentModule = New!ShaderModule(gpu, this);
        fragmentModule.create("NPR.frag.glsl", "data/__internal/shaders/NPR/NPR.frag.glsl",
            ShaderSourceType.File, ShaderLanguage.GLSL, PipelineStage.Fragment);
        
        if (!vertexModule.valid || !fragmentModule.valid)
        {
            exitWithError("Failed to create NPRShader");
        }
        
        vsUBO.modelViewMatrix = Matrix4x4f.identity;
        vsUBO.normalMatrix = Matrix4x4f.identity;
        vsUBO.projectionMatrix = Matrix4x4f.identity;
        vsUBO.prevModelViewMatrix = Matrix4x4f.identity;
        
        fsUBO.resolution = Vector4f(0.0f, 0.0f, 0.0f, 0.0f);
    }
    
    override void bindParameters(GraphicsState* state)
    {
        auto pass = state.pass;
        auto entity = state.entity;
        auto material = state.material;
        
        vsUBO.modelViewMatrix = pass.view.viewMatrix * entity.modelMatrix;
        vsUBO.normalMatrix = vsUBO.modelViewMatrix.inverse.transposed;
        vsUBO.projectionMatrix = pass.view.projectionMatrix;
        vsUBO.prevModelViewMatrix = pass.view.prevViewMatrix * entity.prevModelMatrix;
        
        fsUBO.resolution.x = pass.view.width;
        fsUBO.resolution.y = pass.view.height;
        
        fsUBO.baseColor = material.baseColor;
        
        if (material.baseColorTexture)
        {
            pass.bindTexture(PipelineStage.Fragment, 0, material.baseColorTexture);
            fsUBO.iparams[0] = 1;
        }
        else
        {
            pass.bindDefaultTexture(PipelineStage.Fragment, 0);
            fsUBO.iparams[0] = 0;
        }
        
        pass.bindInputBuffer(PipelineStage.Fragment, 1, &state.velocityBuffer);
        
        pass.bindUniformBuffer(PipelineStage.Vertex, 0, &vsUBO);
        pass.bindUniformBuffer(PipelineStage.Fragment, 0, &fsUBO);
    }
}

class NPRPass: RenderPass
{
    GPU gpu;
    GBuffer gbuffer;
    PostProcessingContext ppContext;
    NPRShader nprShader;
    SDL_GPUColorTargetInfo colorTargetInfo;
    
    this(Renderer renderer, PostProcessingContext ppContext)
    {
        super(renderer);
        this.gpu = renderer.gpu;
        this.gbuffer = ppContext.gbuffer;
        this.ppContext = ppContext;
        
        nprShader = New!NPRShader(gpu, this);
        shader = nprShader;
        
        SDL_GPUGraphicsPipelineCreateInfo pipelineCreateInfo;
        pipelineCreateInfo.vertex_shader = nprShader.vertexModule.shader;
        pipelineCreateInfo.fragment_shader = nprShader.fragmentModule.shader;
        pipelineCreateInfo.primitive_type = SDL_GPU_PRIMITIVETYPE_TRIANGLELIST;
        
        SDL_GPUVertexBufferDescription[3] vbDescriptions;
        
        vbDescriptions[0].slot = 0;
        vbDescriptions[0].input_rate = SDL_GPU_VERTEXINPUTRATE_VERTEX;
        vbDescriptions[0].instance_step_rate = 0;
        vbDescriptions[0].pitch = Vector3f.sizeof;
        
        vbDescriptions[1].slot = 1;
        vbDescriptions[1].input_rate = SDL_GPU_VERTEXINPUTRATE_VERTEX;
        vbDescriptions[1].instance_step_rate = 0;
        vbDescriptions[1].pitch = Vector2f.sizeof;
        
        vbDescriptions[2].slot = 2;
        vbDescriptions[2].input_rate = SDL_GPU_VERTEXINPUTRATE_VERTEX;
        vbDescriptions[2].instance_step_rate = 0;
        vbDescriptions[2].pitch = Vector3f.sizeof;

        pipelineCreateInfo.vertex_input_state.num_vertex_buffers = vbDescriptions.length;
        pipelineCreateInfo.vertex_input_state.vertex_buffer_descriptions = vbDescriptions.ptr;
        
        SDL_GPUVertexAttribute[3] vertexAttributes;
    
        // Position
        vertexAttributes[0].buffer_slot = VertexAttribute.Position;
        vertexAttributes[0].location = VertexAttribute.Position;
        vertexAttributes[0].format = SDL_GPU_VERTEXELEMENTFORMAT_FLOAT3;
        vertexAttributes[0].offset = 0;
        
        // Texcoords
        vertexAttributes[1].buffer_slot = VertexAttribute.Texcoord;
        vertexAttributes[1].location = VertexAttribute.Texcoord;
        vertexAttributes[1].format = SDL_GPU_VERTEXELEMENTFORMAT_FLOAT2;
        vertexAttributes[1].offset = 0;
        
        // Normals
        vertexAttributes[2].buffer_slot = VertexAttribute.Normal;
        vertexAttributes[2].location = VertexAttribute.Normal;
        vertexAttributes[2].format = SDL_GPU_VERTEXELEMENTFORMAT_FLOAT3;
        vertexAttributes[2].offset = 0;
        
        pipelineCreateInfo.vertex_input_state.num_vertex_attributes = vertexAttributes.length;
        pipelineCreateInfo.vertex_input_state.vertex_attributes = vertexAttributes.ptr;
        
        SDL_GPUColorTargetDescription colorTargetDescription;
        colorTargetDescription.format = ppContext.bufferFormat;
        
        /*
        colorTargetDescription.blend_state.enable_blend = true;
        colorTargetDescription.blend_state.color_blend_op = SDL_GPU_BLENDOP_ADD;
        colorTargetDescription.blend_state.alpha_blend_op = SDL_GPU_BLENDOP_ADD;
        colorTargetDescription.blend_state.src_color_blendfactor = SDL_GPU_BLENDFACTOR_SRC_ALPHA;
        colorTargetDescription.blend_state.dst_color_blendfactor = SDL_GPU_BLENDFACTOR_ONE_MINUS_SRC_ALPHA;
        colorTargetDescription.blend_state.src_alpha_blendfactor = SDL_GPU_BLENDFACTOR_SRC_ALPHA;
        colorTargetDescription.blend_state.dst_alpha_blendfactor = SDL_GPU_BLENDFACTOR_ONE_MINUS_SRC_ALPHA;
        */
        
        SDL_GPUColorTargetBlendState blendState = {
            src_color_blendfactor: SDL_GPU_BLENDFACTOR_SRC_ALPHA,
            dst_color_blendfactor: SDL_GPU_BLENDFACTOR_ONE_MINUS_SRC_ALPHA,
            color_blend_op: SDL_GPU_BLENDOP_ADD,
            src_alpha_blendfactor: SDL_GPU_BLENDFACTOR_ZERO,
            dst_alpha_blendfactor: SDL_GPU_BLENDFACTOR_ONE,
            alpha_blend_op: SDL_GPU_BLENDOP_ADD,
            color_write_mask: SDL_GPU_COLORCOMPONENT_R | SDL_GPU_COLORCOMPONENT_G | SDL_GPU_COLORCOMPONENT_B,
            enable_blend: true,
            enable_color_write_mask: true
        };
        colorTargetDescription.blend_state = blendState;
        
        pipelineCreateInfo.target_info.num_color_targets = 1;
        pipelineCreateInfo.target_info.color_target_descriptions = &colorTargetDescription;
        pipelineCreateInfo.target_info.has_depth_stencil_target = false;
        
        pipelineCreateInfo.rasterizer_state.fill_mode = SDL_GPU_FILLMODE_FILL;
        pipelineCreateInfo.rasterizer_state.cull_mode = SDL_GPU_CULLMODE_NONE;
        pipelineCreateInfo.rasterizer_state.front_face = SDL_GPU_FRONTFACE_COUNTER_CLOCKWISE;
        pipelineCreateInfo.rasterizer_state.depth_bias_constant_factor = 0.0f;
        pipelineCreateInfo.rasterizer_state.depth_bias_clamp = 0.0f;
        pipelineCreateInfo.rasterizer_state.depth_bias_slope_factor = 1.0f;
        pipelineCreateInfo.rasterizer_state.enable_depth_bias = false;
        pipelineCreateInfo.rasterizer_state.enable_depth_clip = false;
        
        pipelineCreateInfo.depth_stencil_state.compare_op = SDL_GPU_COMPAREOP_LESS;
        pipelineCreateInfo.depth_stencil_state.enable_depth_test = false;
        pipelineCreateInfo.depth_stencil_state.enable_depth_write = false;
        pipelineCreateInfo.depth_stencil_state.enable_stencil_test = false;
        
        graphicsPipeline = SDL_CreateGPUGraphicsPipeline(gpu.device, &pipelineCreateInfo);
        
        colorTargetInfo.clear_color = SDL_FColor(0.0f, 0.0f, 0.0f, 0.0f);
        colorTargetInfo.load_op = SDL_GPU_LOADOP_LOAD;
        colorTargetInfo.store_op = SDL_GPU_STOREOP_STORE;
        
        colorTargetsInfo = &colorTargetInfo;
        numColorTargets = 1;
        depthStencilTargetInfo = null;
        enableDepthTarget = false;
    }
    
    override void render(GraphicsState* state)
    {
        if (state.scene is null)
            return;
        
        colorTargetInfo.texture = ppContext.readBuffer;
        
        beginPass();
        
        state.depthBuffer = InputBuffer(gbuffer.depthBuffer, gbuffer.depthSampler);
        state.colorBuffer = InputBuffer(gbuffer.colorBuffer, gbuffer.colorSampler);
        state.normalBuffer = InputBuffer(gbuffer.normalBuffer, gbuffer.colorSampler);
        state.roughnessMetallicBuffer = InputBuffer(gbuffer.roughnessMetallicBuffer, gbuffer.colorSampler);
        state.emissionBuffer = InputBuffer(gbuffer.emissionBuffer, gbuffer.colorSampler);
        state.velocityBuffer = InputBuffer(gbuffer.velocityBuffer, gbuffer.colorSampler);
        state.reflectionBuffer = InputBuffer(gbuffer.currentReflectionBuffer, gbuffer.colorSampler);
        state.radianceBuffer = InputBuffer(ppContext.writeBuffer, ppContext.bufferSampler);
        
        foreach(entity; state.scene.entities)
        {
            if (entity.visible && entity.type == EntityType.NPRObject && entity.drawable)
            {
                state.entity = entity;
                if (entity.material)
                    state.material = entity.material;
                else
                    state.material = renderer.defaultMaterial;
                nprShader.bindParameters(state);
                entity.drawable.render(state);
            }
        }
        
        endPass();
        
        //ppContext.swapTargets();
    }
}
