/*
Copyright (c) 2025-2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module bindbc.assimp.loader;

import bindbc.loader;
import bindbc.assimp.types;
import bindbc.assimp.funcs;

enum AssimpSupport
{
    noLibrary,
    badLibrary,
    v500 = 500,
}

private
{
    SharedLib lib;
    AssimpSupport loadedVersion;
}

void unloadAssimp()
{
    if (lib != invalidHandle)
    {
        lib.unload();
    }
}

AssimpSupport loadedAssimpVersion()
{
    return loadedVersion;
}

bool isAssimpLoaded()
{
    return lib != invalidHandle;
}

AssimpSupport loadAssimp()
{
    version(Windows)
    {
        const(char)[][1] libNames = [
            "Assimp.dll"
        ];
    }
    else version(OSX)
    {
        const(char)[][1] libNames = [
            "libassimp.dylib"
        ];
    }
    else version(Posix)
    {
        const(char)[][1] libNames = [
            "libassimp.so"
        ];
    }
    else static assert(0, "bindbc-assimp is not yet supported on this platform.");

    AssimpSupport ret;
    foreach(name; libNames)
    {
        ret = loadAssimp(name.ptr);
        if (ret != AssimpSupport.noLibrary)
            break;
    }
    return ret;
}

AssimpSupport loadAssimp(const(char)* libName)
{
    lib = load(libName);
    if (lib == invalidHandle)
    {
        return AssimpSupport.noLibrary;
    }
    
    auto errCount = errorCount();
    loadedVersion = AssimpSupport.badLibrary;
    
    import std.algorithm.searching: startsWith;
    static foreach(symbol; __traits(allMembers, bindbc.assimp.funcs))
    {
        static if (symbol.startsWith("ai"))
            lib.bindSymbol(
                cast(void**)&__traits(getMember, bindbc.assimp.funcs, symbol),
                __traits(getMember, bindbc.assimp.funcs, symbol).stringof);
    }
    
    loadedVersion = AssimpSupport.v500;
    
    if (errorCount() != errCount)
        return AssimpSupport.badLibrary;
    
    return loadedVersion;
}
