/*
Copyright (c) 2025-2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module bindbc.assimp.signatures;

import bindbc.assimp.types;

extern(System) @nogc nothrow
{
    alias p_aiGetExportFormatCount = size_t function();
    alias p_aiGetExportFormatDescription = const(aiExportFormatDesc*) function(size_t pIndex);
    alias p_aiReleaseExportFormatDescription = void function(const(aiExportFormatDesc)* desc);
    alias p_aiCopyScene = void function(const(aiScene)* pIn, aiScene** pOut);
    alias p_aiFreeScene = void function(const(aiScene)* pIn);
    alias p_aiExportScene = aiReturn function(const(aiScene)* pScene, const(char)* pFormatId, const(char)* pFileName, uint pPreprocessing);
    alias p_aiExportSceneEx = aiReturn function(const(aiScene)* pScene, const(char)* pFormatId, const(char)* pFileName, aiFileIO* pIO, uint pPreprocessing);
    alias p_aiExportSceneToBlob = const(aiExportDataBlob*) function(const(aiScene)* pScene, const(char)* pFormatId, uint pPreprocessing);
    alias p_aiReleaseExportBlob = void function(const(aiExportDataBlob)* pData);
    alias p_aiImportFile = const(aiScene*) function(const(char)* pFile, uint pFlags);
    alias p_aiImportFileEx = const(aiScene*) function(const(char)* pFile, uint pFlags, aiFileIO* pFS);
    alias p_aiImportFileExWithProperties = const(aiScene*) function(const(char)* pFile, uint pFlags, aiFileIO* pFS, const(aiPropertyStore)* pProps);
    alias p_aiImportFileFromMemory = const(aiScene*) function(const(char)* pBuffer, uint pLength, uint pFlags, const(char)* pHint);
    alias p_aiImportFileFromMemoryWithProperties = const(aiScene*) function(const(char)* pBuffer, uint pLength, uint pFlags, const(char)* pHint, const(aiPropertyStore)* pProps);
    alias p_aiApplyPostProcessing = const(aiScene*) function(const(aiScene)* pScene, uint pFlags);
    alias p_aiGetPredefinedLogStream = aiLogStream function(aiDefaultLogStream pStreams, const(char)* file);
    alias p_aiAttachLogStream = void function(const aiLogStream* stream);
    alias p_aiEnableVerboseLogging = void function(aiBool d);
    alias p_aiDetachLogStream = aiReturn function(const aiLogStream* stream);
    alias p_aiDetachAllLogStreams = void function();
    alias p_aiReleaseImport = void function(const aiScene* pScene);
    alias p_aiGetErrorString = const(char*) function();
    alias p_aiIsExtensionSupported = aiBool function(const char* szExtension);
    alias p_aiGetExtensionList = void function(aiString* szOut);
    alias p_aiGetMemoryRequirements = void function(const aiScene* pIn, aiMemoryInfo* _in);
    alias p_aiCreatePropertyStore = aiPropertyStore* function();
    alias p_aiReleasePropertyStore = void function(aiPropertyStore* p);
    alias p_aiSetImportPropertyInteger = void function(aiPropertyStore* store, const char* szName, int value);
    alias p_aiSetImportPropertyFloat = void function(aiPropertyStore* store, const char* szName, ai_real value);
    alias p_aiSetImportPropertyString = void function(aiPropertyStore* store, const char* szName, const aiString* st);
    alias p_aiSetImportPropertyMatrix = void function(aiPropertyStore* store, const char* szName, const aiMatrix4x4* mat);
    alias p_aiCreateQuaternionFromMatrix = void function(aiQuaternion* quat, const aiMatrix3x3* mat);
    alias p_aiDecomposeMatrix = void function(const aiMatrix4x4* mat, aiVector3D* scaling, aiQuaternion* rotation, aiVector3D* position);
    alias p_aiTransposeMatrix4 = void function(aiMatrix4x4* mat);
    alias p_aiTransposeMatrix3 = void function(aiMatrix3x3* mat);
    alias p_aiTransformVecByMatrix3 = void function(aiVector3D* vec, const aiMatrix3x3* mat);
    alias p_aiTransformVecByMatrix4 = void function(aiVector3D* vec, const aiMatrix4x4* mat);
    alias p_aiMultiplyMatrix4 = void function(aiMatrix4x4* dst, const aiMatrix4x4* src);
    alias p_aiMultiplyMatrix3 = void function(aiMatrix3x3* dst, const aiMatrix3x3* src);
    alias p_aiIdentityMatrix3 = void function(aiMatrix3x3* mat);
    alias p_aiIdentityMatrix4 = void function(aiMatrix4x4* mat);
    alias p_aiGetImportFormatCount = size_t function();
    alias p_aiGetImportFormatDescription = const(aiImporterDesc*) function(size_t pIndex);
    alias p_aiGetImporterDesc = const(aiImporterDesc*) function(const char *extension);
    alias p_aiGetMaterialProperty = aiReturn function(const aiMaterial* pMat, const char* pKey, uint type, uint index, const aiMaterialProperty** pPropOut);
    alias p_aiGetMaterialFloatArray = aiReturn function(const aiMaterial* pMat, const char* pKey, uint type, uint index, ai_real* pOut, uint* pMax);
    alias p_aiGetMaterialIntegerArray = aiReturn function(const aiMaterial* pMat, const char* pKey, uint type, uint index, int* pOut, uint* pMax);
    alias p_aiGetMaterialColor = aiReturn function(const aiMaterial* pMat, const char* pKey, uint type, uint index, aiColor4D* pOut);
    alias p_aiGetMaterialUVTransform = aiReturn function(const aiMaterial* pMat, const char* pKey, uint type, uint index, aiUVTransform* pOut);
    alias p_aiGetMaterialString = aiReturn function(const aiMaterial* pMat, const char* pKey, uint type, uint index, aiString* pOut);
    alias p_aiGetMaterialTextureCount = uint function(const aiMaterial* pMat, aiTextureType type);
    alias p_aiGetMaterialTexture = aiReturn function(const aiMaterial* mat, aiTextureType type, uint index, aiString* path, aiTextureMapping* mapping, uint* uvindex, ai_real* blend, aiTextureOp* op, aiTextureMapMode* mapmode, uint* flags);
    alias p_aiGetLegalString = const(char*) function();
    alias p_aiGetVersionMinor = uint function();
    alias p_aiGetVersionMajor = uint function();
    alias p_aiGetVersionRevision = uint function();
    alias p_aiGetBranchName = const(char*) function();
    alias p_aiGetCompileFlags = uint function();
}
