/*
Copyright (c) 2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

/**
 * BRDF LUT generator.
 *
 * dagon.graphics.brdflut module provides classes to create a BRDF lookup texture
 * for PBR workflow.
 *
 * Copyright: Timur Gafarov 2026
 * License: $(LINK2 https://boost.org/LICENSE_1_0.txt, Boost License 1.0).
 * Authors: Timur Gafarov
 */
module dagon.graphics.brdflut;

import dlib.core.memory;
import dlib.core.ownership;
import dlib.math.vector;
import dlib.math.matrix;
import dlib.math.transformation;
import dlib.math.utils;

import dagon.core.logger;
import dagon.core.sdl3;
import dagon.core.gpu;
import dagon.core.crashhandler;
import dagon.core.event;
import dagon.graphics.mesh;
import dagon.graphics.texture;
import dagon.graphics.state;
import dagon.resource.shader;
import dagon.render.renderer;
import dagon.render.pass;

/// Uniform buffer object for BRDF LUT vertex shader stage.
struct BRDFLUTShaderVertexUniformBuffer
{
}

/// Uniform buffer object for BRDF LUT fragment shader stage.
struct BRDFLUTShaderFragmentUniformBuffer
{
    /// Vector that stores output resolution in pixels in its x, y components.
    Vector4f resolution;
}

/**
 * Shader for BRDF LUT creation.
 */
class BRDFLUTShader: Shader
{
   protected:
    BRDFLUTShaderVertexUniformBuffer vsUBO;
    BRDFLUTShaderFragmentUniformBuffer fsUBO;
    
   public:
    /// Requested output resolution for the lookup texture.
    Vector2f resolution = Vector2f(0.0f, 0.0f);

    this(GPU gpu, Owner owner)
    {
        super(gpu, owner);
        
        vertexModule = New!ShaderModule(gpu, this);
        vertexModule.create("BRDFLUT.vert.glsl", "data/__internal/shaders/BRDFLUT/BRDFLUT.vert.glsl",
            ShaderSourceType.File, ShaderLanguage.GLSL, PipelineStage.Vertex);
        
        fragmentModule = New!ShaderModule(gpu, this);
        fragmentModule.create("BRDFLUT.frag.glsl", "data/__internal/shaders/BRDFLUT/BRDFLUT.frag.glsl",
            ShaderSourceType.File, ShaderLanguage.GLSL, PipelineStage.Fragment);
        
        if (!vertexModule.valid || !fragmentModule.valid)
        {
            exitWithError("Failed to create BRDFLUTShader");
        }
        
        fsUBO.resolution = Vector4f(0.0f, 0.0f, 0.0f, 0.0f);
    }
    
    /**
     * Binds shader parameters to the GPU pipeline.
     *
     * Params:
     *   state = Pointer to the current graphics state.
     */
    override void bindParameters(GraphicsState* state)
    {
        auto pass = state.pass;
        
        fsUBO.resolution.x = resolution.x;
        fsUBO.resolution.y = resolution.y;
        
        //pass.bindUniformBuffer(PipelineStage.Vertex, 0, &vsUBO);
        pass.bindUniformBuffer(PipelineStage.Fragment, 0, &fsUBO);
    }
}

/**
 * Render pass that draws a full-screen quad into a texture using the BRDF LUT shader.
 */
class BRDFLUTPass: RenderPass
{
    BRDFLUTShader brdflutShader;
    Texture outputTexture;
    SDL_GPUColorTargetDescription colorTargetDescription;
    SDL_GPUColorTargetInfo colorTargetInfo;
    
    this(Renderer renderer, SDL_GPUTextureFormat outputFormat)
    {
        super(renderer);
        
        brdflutShader = New!BRDFLUTShader(renderer.gpu, this);
        
        SDL_GPUGraphicsPipelineCreateInfo pipelineCreateInfo;
        pipelineCreateInfo.vertex_shader = brdflutShader.vertexModule.shader;
        pipelineCreateInfo.fragment_shader = brdflutShader.fragmentModule.shader;
        pipelineCreateInfo.primitive_type = SDL_GPU_PRIMITIVETYPE_TRIANGLELIST;
        
        SDL_GPUVertexBufferDescription[2] vbDescriptions;
        
        vbDescriptions[0].slot = VertexAttribute.Position;
        vbDescriptions[0].input_rate = SDL_GPU_VERTEXINPUTRATE_VERTEX;
        vbDescriptions[0].instance_step_rate = 0;
        vbDescriptions[0].pitch = Vector2f.sizeof;
        
        vbDescriptions[1].slot = VertexAttribute.Texcoord;
        vbDescriptions[1].input_rate = SDL_GPU_VERTEXINPUTRATE_VERTEX;
        vbDescriptions[1].instance_step_rate = 0;
        vbDescriptions[1].pitch = Vector2f.sizeof;
        
        pipelineCreateInfo.vertex_input_state.num_vertex_buffers = vbDescriptions.length;
        pipelineCreateInfo.vertex_input_state.vertex_buffer_descriptions = vbDescriptions.ptr;
        
        SDL_GPUVertexAttribute[2] vertexAttributes;
        
        // Position
        vertexAttributes[0].buffer_slot = VertexAttribute.Position;
        vertexAttributes[0].location = VertexAttribute.Position;
        vertexAttributes[0].format = SDL_GPU_VERTEXELEMENTFORMAT_FLOAT2;
        vertexAttributes[0].offset = 0;
        
        // Texcoords
        vertexAttributes[1].buffer_slot = VertexAttribute.Texcoord;
        vertexAttributes[1].location = VertexAttribute.Texcoord;
        vertexAttributes[1].format = SDL_GPU_VERTEXELEMENTFORMAT_FLOAT2;
        vertexAttributes[1].offset = 0;
        
        pipelineCreateInfo.vertex_input_state.num_vertex_attributes = vertexAttributes.length;
        pipelineCreateInfo.vertex_input_state.vertex_attributes = vertexAttributes.ptr;
        
        SDL_GPUColorTargetBlendState blendState = {
            src_color_blendfactor: SDL_GPU_BLENDFACTOR_ONE,
            dst_color_blendfactor: SDL_GPU_BLENDFACTOR_ONE,
            color_blend_op: SDL_GPU_BLENDOP_ADD,
            src_alpha_blendfactor: SDL_GPU_BLENDFACTOR_ONE,
            dst_alpha_blendfactor: SDL_GPU_BLENDFACTOR_ONE,
            alpha_blend_op: SDL_GPU_BLENDOP_ADD,
            color_write_mask: 0,
            enable_blend: false,
            enable_color_write_mask: false
        };
        colorTargetDescription.format = outputFormat;
        colorTargetDescription.blend_state = blendState;
        
        pipelineCreateInfo.target_info.num_color_targets = 1;
        pipelineCreateInfo.target_info.color_target_descriptions = &colorTargetDescription;
        pipelineCreateInfo.target_info.has_depth_stencil_target = false;
        
        pipelineCreateInfo.rasterizer_state.fill_mode = SDL_GPU_FILLMODE_FILL;
        pipelineCreateInfo.rasterizer_state.cull_mode = SDL_GPU_CULLMODE_NONE;
        pipelineCreateInfo.rasterizer_state.front_face = SDL_GPU_FRONTFACE_COUNTER_CLOCKWISE;
        pipelineCreateInfo.rasterizer_state.depth_bias_constant_factor = 0.0f;
        pipelineCreateInfo.rasterizer_state.depth_bias_clamp = 0.0f;
        pipelineCreateInfo.rasterizer_state.depth_bias_slope_factor = 1.0f;
        pipelineCreateInfo.rasterizer_state.enable_depth_bias = false;
        pipelineCreateInfo.rasterizer_state.enable_depth_clip = false;
        
        pipelineCreateInfo.depth_stencil_state.compare_op = SDL_GPU_COMPAREOP_LESS;
        pipelineCreateInfo.depth_stencil_state.enable_depth_test = false;
        pipelineCreateInfo.depth_stencil_state.enable_depth_write = false;
        pipelineCreateInfo.depth_stencil_state.enable_stencil_test = false;
        
        graphicsPipeline = SDL_CreateGPUGraphicsPipeline(renderer.gpu.device, &pipelineCreateInfo);
        
        colorTargetInfo.clear_color = SDL_FColor(0.0f, 0.0f, 0.0f, 1.0f);
        colorTargetInfo.load_op = SDL_GPU_LOADOP_DONT_CARE;
        colorTargetInfo.store_op = SDL_GPU_STOREOP_STORE;
        
        colorTargetsInfo = &colorTargetInfo;
        numColorTargets = 1;
        depthStencilTargetInfo = null;
        enableDepthTarget = false;
    }
    
    override void render(GraphicsState* state)
    {
        colorTargetInfo.texture = outputTexture.texture;
        colorTargetInfo.mip_level = 0;
        colorTargetInfo.layer_or_depth_plane = 0;
        
        beginPass();
        
        brdflutShader.resolution = Vector2f(renderer.view.width, renderer.view.height);
        brdflutShader.bindParameters(state);
        
        renderer.renderScreenQuad(state);
        
        endPass();
    }
}

/**
 * High-level interface to generate BRDF LUT textures.
 */
class BRDFLUTRenderer: Renderer
{
    BRDFLUTPass brdflutPass;
    
    /// Initializes BRDF LUT renderer with GPU and render target format.
    this(GPU gpu, EventManager eventManager, SDL_GPUTextureFormat format)
    {
        super(gpu, eventManager);
        brdflutPass = New!BRDFLUTPass(this, format);
    }
    
    /**
     * Generates BRDF LUT and store result in `outputTexture`.
     * The passed texture must be already allocated and have the desired size.
     */
    void generateTexture(Texture outputTexture)
    {
        view.resize(outputTexture.buffer.size.width, outputTexture.buffer.size.height);
        brdflutPass.outputTexture = outputTexture;
        
        state.reset();
        
        commandBuffer = SDL_AcquireGPUCommandBuffer(gpu.device);
        
        state.pass = brdflutPass;
        brdflutPass.render(&state);
        
        SDL_SubmitGPUCommandBuffer(commandBuffer);
    }
}
