/*
Copyright (c) 2019-2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

/**
 * Defines the camera class.
 *
 * Description:
 * The `dagon.graphics.camera` module provides the `Camera` class,
 * which inherits from `Entity` and represents a view into the scene.
 * The camera supports perspective projection parameters (field of view,
 * near and far planes) and provides methods to obtain the view and inverse
 * view matrices for rendering.
 *
 * Copyright: Timur Gafarov 2019-2026
 * License: $(LINK2 https://boost.org/LICENSE_1_0.txt, Boost License 1.0).
 * Authors: Timur Gafarov
 */
module dagon.graphics.camera;

import dlib.core.ownership;
import dlib.math.vector;
import dlib.math.matrix;
import dlib.math.quaternion;
import dlib.math.transformation;
import dlib.math.utils;
import dlib.math.interpolation;

import dagon.core.logger;
import dagon.core.time;
import dagon.core.event;
import dagon.graphics.entity;

/**
 * Represents a camera in the scene, inheriting from `Entity`.
 *
 * Description:
 * The camera defines a view into the scene with projection parameters.
 * It provides methods to obtain the view and inverse view matrices
 * for rendering.
 */
class Camera: Entity
{
    /// Field of view in degrees (vertical) for perspective projection.
    float fov = 60.0f;

    /// Near clipping plane distance.
    float zNear = 0.01f;

    /// Far clipping plane distance.
    float zFar = 1000.0f;

    //TODO: lens parameters for DoF

    /**
     * Constructs a camera entity.
     *
     * Params:
     *   owner = The owner object.
     */
    this(Owner owner)
    {
        super(owner);
        
        visible = false;
        castShadow = false;
    }
    
    /**
     * Returns the view matrix for this camera.
     *
     * Returns:
     *   The inverse of the absolute transformation matrix.
     */
    Matrix4x4f viewMatrix()
    {
        return invModelMatrix;
    }
    
    /**
     * Returns the inverse view matrix for this camera.
     *
     * Returns:
     *   The absolute transformation matrix.
     */
    Matrix4x4f invViewMatrix()
    {
        return modelMatrix;
    }
    
    /**
     * Returns the projection matrix (perspective transform) for this camera
     * and given aspect ratio.
     *
     * Returns:
     *   The projection matrix.
     */
    Matrix4x4f projectionMatrix(float aspectRatio)
    {
        return perspectiveMatrix(fov, aspectRatio, zNear, zFar);
    }
}

///
struct CameraState
{
    Vector3f position;
    Quaternionf rotation;
    float fov;
}

///
interface CameraDriver
{
    ///
    void update(Time t, CameraState* outState);
}

///
enum Easing
{
    Linear = 0,
    EaseInQuad = 1,
    EaseOutQuad = 2,
    EaseInOutQuad = 3,
    EaseInBack = 4,
    EaseOutBack = 5,
    EaseInOutBack = 6,
    EaseOutBounce = 7,
    EaseOutElastic = 8
}

///
class CameraController: EntityController
{
   public:
    ///
    Camera camera;
   
   protected:
    CameraDriver currentDriver;
    CameraDriver targetDriver;
    CameraState transitionState;
    float transitionTime = 0.0f;
    float transitionDuration = 0.0f;
    Easing easing = Easing.Linear;
    bool finished = true;
    bool lerpFromTransitionState = false;
    
   public:
    ///
    this(EventManager eventManager, Camera camera, CameraDriver initialDriver)
    {
        super(eventManager, camera);
        this.camera = camera;
        currentDriver = initialDriver;
        targetDriver = initialDriver;
    }
    
    ///
    void transitionTo(CameraDriver driver, float duration, Easing easing = Easing.Linear)
    {
        if (duration <= 0.0f)
        {
            currentDriver = driver;
            targetDriver = driver;
            transitionTime = 0.0f;
            transitionDuration = 0.0f;
            this.easing = easing;
            finished = true;
            lerpFromTransitionState = false;
            return;
        }
        
        currentDriver = targetDriver;
        targetDriver = driver;
        transitionTime = 0.0f;
        transitionDuration = duration;
        this.easing = easing;
        
        if (!finished)
        {
            lerpFromTransitionState = true;
            transitionState.position = camera.position;
            transitionState.rotation = camera.rotation;
            transitionState.fov = camera.fov;
        }
        
        finished = false;
    }
    
    ///
    override void update(Time t)
    {
        if (currentDriver is null || targetDriver is null)
            return;
        
        CameraState currentState;
        if (lerpFromTransitionState)
            currentState = transitionState;
        else
            currentDriver.update(t, &currentState);
        
        if (currentDriver is targetDriver || transitionDuration <= 0.0f)
        {
            camera.position = currentState.position;
            camera.rotation = currentState.rotation;
            camera.fov = currentState.fov;
        }
        else
        {
            CameraState targetState;
            targetDriver.update(t, &targetState);
            transitionTime += t.delta;
            
            float linearT = clamp(transitionTime / transitionDuration, 0.0f, 1.0f);
            float nonLinearT;
            switch(easing)
            {
                case Easing.EaseInQuad:
                    nonLinearT = easeInQuad(linearT);
                    break;
                case Easing.EaseOutQuad:
                    nonLinearT = easeOutQuad(linearT);
                    break;
                case Easing.EaseInOutQuad:
                    nonLinearT = easeInOutQuad(linearT);
                    break;
                case Easing.EaseInBack:
                    nonLinearT = easeInBack(linearT);
                    break;
                case Easing.EaseOutBack:
                    nonLinearT = easeOutBack(linearT);
                    break;
                case Easing.EaseInOutBack:
                    nonLinearT = easeInOutBack(linearT);
                    break;
                case Easing.EaseOutBounce:
                    nonLinearT = easeOutBounce(linearT);
                    break;
                case Easing.EaseOutElastic:
                    nonLinearT = easeOutElastic(linearT);
                    break;
                default:
                    nonLinearT = linearT;
                    break;
            }
            
            camera.position = lerp(currentState.position, targetState.position, nonLinearT);
            camera.rotation = slerp(currentState.rotation, targetState.rotation, nonLinearT);
            camera.fov = lerp(currentState.fov, targetState.fov, nonLinearT);
            
            if (linearT >= 1.0f)
            {
                currentDriver = targetDriver;
                transitionTime = 0.0f;
                transitionDuration = 0.0f;
                finished = true;
                lerpFromTransitionState = false;
            }
        }
        
        camera.transformation =
            (translationMatrix(camera.position) *
            camera.rotation.toMatrix4x4 *
            scaleMatrix(camera.scaling));
        camera.invTransformation = camera.transformation.inverse;
    }
    
    ///
    override void postUpdate(Time t)
    {
        if (camera.parent)
        {
            camera.modelMatrix = camera.parent.modelMatrix * camera.transformation;
            camera.invModelMatrix = camera.modelMatrix.inverse;
        }
        else
        {
            camera.modelMatrix = camera.transformation;
            camera.invModelMatrix = camera.invTransformation;
        }
    }
}
