/*
Copyright (c) 2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module dagon.graphics.conv;

import dagon.core.sdl3;
import dagon.core.vkformat;
import dagon.core.dxgiformat;
import dagon.graphics.texturebuffer;

// Texture format conversion functions (Vulkan -> SDL GPU, DXGI <-> SDL GPU)

/**
 * Converts Vulkan texture format to SDL GPU texture format.
 *
 * Params:
 *   fmt = VkFormat.
 *   tf = Output SDL_GPUTextureFormat.
 * Returns:
 *   true if format is supported, false otherwise.
 */
bool vkFormatToSDLFormat(VkFormat fmt, out TextureFormat tf)
{
    tf.format = SDL_GPU_TEXTUREFORMAT_INVALID;
    tf.blockSize = 0;
    
    switch(fmt)
    {
        case VkFormat.R8_UNORM:
            tf.format = SDL_GPU_TEXTUREFORMAT_R8_UNORM;
            tf.numChannels = 1;
            tf.pixelSize = 1;
            break;
        case VkFormat.R8_SNORM:
            tf.format = SDL_GPU_TEXTUREFORMAT_R8_SNORM;
            tf.numChannels = 1;
            tf.pixelSize = 1;
            break;
        case VkFormat.R8G8_UNORM:
            tf.format = SDL_GPU_TEXTUREFORMAT_R8G8_UNORM;
            tf.numChannels = 2;
            tf.pixelSize = 2;
            break;
        case VkFormat.R8G8_SNORM:
            tf.format = SDL_GPU_TEXTUREFORMAT_R8G8_SNORM;
            tf.numChannels = 2;
            tf.pixelSize = 2;
            break;
        case VkFormat.R8G8B8A8_UNORM, VkFormat.R8G8B8A8_SRGB:
            tf.format = SDL_GPU_TEXTUREFORMAT_R8G8B8A8_UNORM;
            tf.numChannels = 4;
            tf.pixelSize = 4;
            break;
        case VkFormat.R32G32B32A32_SFLOAT:
            tf.format = SDL_GPU_TEXTUREFORMAT_R32G32B32A32_FLOAT;
            tf.numChannels = 4;
            tf.pixelSize = 16;
            break;
        case VkFormat.R16G16B16A16_SFLOAT:
            tf.format = SDL_GPU_TEXTUREFORMAT_R16G16B16A16_FLOAT;
            tf.numChannels = 4;
            tf.pixelSize = 8;
            break;
        case VkFormat.BC1_RGB_UNORM_BLOCK, VkFormat.BC1_RGB_SRGB_BLOCK:
            tf.format = SDL_GPU_TEXTUREFORMAT_BC1_RGBA_UNORM;
            tf.numChannels = 4;
            tf.blockSize = 8;
            break;
        case VkFormat.BC2_UNORM_BLOCK, VkFormat.BC2_SRGB_BLOCK:
            tf.format = SDL_GPU_TEXTUREFORMAT_BC2_RGBA_UNORM;
            tf.numChannels = 4;
            tf.blockSize = 16;
            break;
        case VkFormat.BC3_UNORM_BLOCK, VkFormat.BC3_SRGB_BLOCK:
            tf.format = SDL_GPU_TEXTUREFORMAT_BC3_RGBA_UNORM;
            tf.numChannels = 4;
            tf.blockSize = 16;
            break;
        case VkFormat.BC4_UNORM_BLOCK, VkFormat.BC4_SNORM_BLOCK:
            tf.format = SDL_GPU_TEXTUREFORMAT_BC4_R_UNORM;
            tf.numChannels = 1;
            tf.blockSize = 8;
            break;
        case VkFormat.BC5_UNORM_BLOCK, VkFormat.BC5_SNORM_BLOCK:
            tf.format = SDL_GPU_TEXTUREFORMAT_BC5_RG_UNORM;
            tf.numChannels = 2;
            tf.blockSize = 16;
            break;
        case VkFormat.BC6H_SFLOAT_BLOCK:
            tf.format = SDL_GPU_TEXTUREFORMAT_BC6H_RGB_FLOAT;
            tf.numChannels = 4;
            tf.blockSize = 16;
            break;
        case VkFormat.BC6H_UFLOAT_BLOCK:
            tf.format = SDL_GPU_TEXTUREFORMAT_BC6H_RGB_UFLOAT;
            tf.numChannels = 4;
            tf.blockSize = 16;
            break;
        case VkFormat.BC7_UNORM_BLOCK, VkFormat.BC7_SRGB_BLOCK:
            tf.format = SDL_GPU_TEXTUREFORMAT_BC7_RGBA_UNORM;
            tf.numChannels = 4;
            tf.blockSize = 16;
            break;
        case VkFormat.ASTC_4x4_UNORM_BLOCK, VkFormat.ASTC_4x4_SRGB_BLOCK:
            tf.format = SDL_GPU_TEXTUREFORMAT_ASTC_4x4_UNORM;
            tf.numChannels = 4;
            tf.blockSize = 16;
            break;
        
        // TODO: other ASTC formats
        
        default:
            return false;
    }
    
    return true;
}

/**
 * Converts DirectX texture format to SDL GPU texture format.
 *
 * Params:
 *   fmt = DXGIFormat.
 *   tf = Output SDL_GPUTextureFormat.
 * Returns:
 *   true if format is supported, false otherwise.
 */
bool dxgiFormatToSDLFormat(DXGIFormat fmt, out TextureFormat tf)
{
    tf.format = SDL_GPU_TEXTUREFORMAT_INVALID;
    tf.blockSize = 0;
    
    switch(fmt)
    {
        case DXGIFormat.R32G32B32A32_TYPELESS:
            tf.format = SDL_GPU_TEXTUREFORMAT_R32G32B32A32_UINT;
            tf.numChannels = 4;
            tf.pixelSize = 16;
            break;
        case DXGIFormat.R32G32B32A32_FLOAT:
            tf.format = SDL_GPU_TEXTUREFORMAT_R32G32B32A32_FLOAT;
            tf.numChannels = 4;
            tf.pixelSize = 16;
            break;
        case DXGIFormat.R32G32B32A32_UINT:
            tf.format = SDL_GPU_TEXTUREFORMAT_R32G32B32A32_UINT;
            tf.numChannels = 4;
            tf.pixelSize = 16;
            break;
        case DXGIFormat.R32G32B32A32_SINT:
            tf.format = SDL_GPU_TEXTUREFORMAT_R32G32B32A32_INT;
            tf.numChannels = 4;
            tf.pixelSize = 16;
            break;
        case DXGIFormat.R16G16B16A16_TYPELESS:
            tf.format = SDL_GPU_TEXTUREFORMAT_R16G16B16A16_UINT;
            tf.numChannels = 4;
            tf.pixelSize = 8;
            break;
        case DXGIFormat.R16G16B16A16_FLOAT:
            tf.format = SDL_GPU_TEXTUREFORMAT_R16G16B16A16_FLOAT;
            tf.numChannels = 4;
            tf.pixelSize = 8;
            break;
        case DXGIFormat.R16G16B16A16_UNORM:
            tf.format = SDL_GPU_TEXTUREFORMAT_R16G16B16A16_UNORM;
            tf.numChannels = 4;
            tf.pixelSize = 8;
            break;
        case DXGIFormat.R16G16B16A16_UINT:
            tf.format = SDL_GPU_TEXTUREFORMAT_R16G16B16A16_UINT;
            tf.numChannels = 4;
            tf.pixelSize = 8;
            break;
        case DXGIFormat.R16G16B16A16_SNORM:
            tf.format = SDL_GPU_TEXTUREFORMAT_R16G16B16A16_SNORM;
            tf.numChannels = 4;
            tf.pixelSize = 8;
            break;
        case DXGIFormat.R16G16B16A16_SINT:
            tf.format = SDL_GPU_TEXTUREFORMAT_R16G16B16A16_INT;
            tf.numChannels = 4;
            tf.pixelSize = 8;
            break;
        case DXGIFormat.R32G32_TYPELESS:
            tf.format = SDL_GPU_TEXTUREFORMAT_R32G32_UINT;
            tf.numChannels = 2;
            tf.pixelSize = 8;
            break;
        case DXGIFormat.R32G32_FLOAT:
            tf.format = SDL_GPU_TEXTUREFORMAT_R32G32_FLOAT;
            tf.numChannels = 2;
            tf.pixelSize = 8;
            break;
        case DXGIFormat.R32G32_UINT:
            tf.format = SDL_GPU_TEXTUREFORMAT_R32G32_UINT;
            tf.numChannels = 2;
            tf.pixelSize = 8;
            break;
        case DXGIFormat.R32G32_SINT:
            tf.format = SDL_GPU_TEXTUREFORMAT_R32G32_INT;
            tf.numChannels = 2;
            tf.pixelSize = 8;
            break;
        case DXGIFormat.R10G10B10A2_TYPELESS:
            tf.format = SDL_GPU_TEXTUREFORMAT_R10G10B10A2_UNORM;
            tf.numChannels = 4;
            tf.pixelSize = 4;
            break;
        case DXGIFormat.R10G10B10A2_UNORM:
            tf.format = SDL_GPU_TEXTUREFORMAT_R10G10B10A2_UNORM;
            tf.numChannels = 4;
            tf.pixelSize = 4;
            break;
        case DXGIFormat.R10G10B10A2_UINT:
            tf.format = SDL_GPU_TEXTUREFORMAT_R10G10B10A2_UNORM;
            tf.numChannels = 4;
            tf.pixelSize = 4;
            break;
        case DXGIFormat.R11G11B10_FLOAT:
            tf.format = SDL_GPU_TEXTUREFORMAT_R11G11B10_UFLOAT;
            tf.numChannels = 3;
            tf.pixelSize = 4;
            break;
        case DXGIFormat.R8G8B8A8_TYPELESS:
            tf.format = SDL_GPU_TEXTUREFORMAT_R8G8B8A8_UINT;
            tf.numChannels = 4;
            tf.pixelSize = 4;
            break;
        case DXGIFormat.R8G8B8A8_UNORM, DXGIFormat.R8G8B8A8_UNORM_SRGB:
            tf.format = SDL_GPU_TEXTUREFORMAT_R8G8B8A8_UNORM;
            tf.numChannels = 4;
            tf.pixelSize = 4;
            break;
        case DXGIFormat.R8G8B8A8_UINT:
            tf.format = SDL_GPU_TEXTUREFORMAT_R8G8B8A8_UINT;
            tf.numChannels = 4;
            tf.pixelSize = 4;
            break;
        case DXGIFormat.R8G8B8A8_SNORM:
            tf.format = SDL_GPU_TEXTUREFORMAT_R8G8B8A8_SNORM;
            tf.numChannels = 4;
            tf.pixelSize = 4;
            break;
        case DXGIFormat.R8G8B8A8_SINT:
            tf.format = SDL_GPU_TEXTUREFORMAT_R8G8B8A8_INT;
            tf.numChannels = 4;
            tf.pixelSize = 4;
            break;
        case DXGIFormat.R16G16_TYPELESS:
            tf.format = SDL_GPU_TEXTUREFORMAT_R16G16_UINT;
            tf.numChannels = 2;
            tf.pixelSize = 4;
            break;
        case DXGIFormat.R16G16_FLOAT:
            tf.format = SDL_GPU_TEXTUREFORMAT_R16G16_FLOAT;
            tf.numChannels = 2;
            tf.pixelSize = 4;
            break;
        case DXGIFormat.R16G16_UNORM:
            tf.format = SDL_GPU_TEXTUREFORMAT_R16G16_UNORM;
            tf.numChannels = 2;
            tf.pixelSize = 4;
            break;
        case DXGIFormat.R16G16_UINT:
            tf.format = SDL_GPU_TEXTUREFORMAT_R16G16_UINT;
            tf.numChannels = 2;
            tf.pixelSize = 4;
            break;
        case DXGIFormat.R16G16_SNORM:
            tf.format = SDL_GPU_TEXTUREFORMAT_R16G16_SNORM;
            tf.numChannels = 2;
            tf.pixelSize = 4;
            break;
        case DXGIFormat.R16G16_SINT:
            tf.format = SDL_GPU_TEXTUREFORMAT_R16G16_INT;
            tf.numChannels = 2;
            tf.pixelSize = 4;
            break;
        case DXGIFormat.R32_TYPELESS:
            tf.format = SDL_GPU_TEXTUREFORMAT_R32_UINT;
            tf.numChannels = 1;
            tf.pixelSize = 4;
            break;
        case DXGIFormat.R32_FLOAT, DXGIFormat.D32_FLOAT:
            tf.format = SDL_GPU_TEXTUREFORMAT_R32_FLOAT;
            tf.numChannels = 1;
            tf.pixelSize = 4;
            break;
        case DXGIFormat.R32_UINT:
            tf.format = SDL_GPU_TEXTUREFORMAT_R32_UINT;
            tf.numChannels = 1;
            tf.pixelSize = 4;
            break;
        case DXGIFormat.R32_SINT:
            tf.format = SDL_GPU_TEXTUREFORMAT_R32_INT;
            tf.numChannels = 1;
            tf.pixelSize = 4;
            break;
        case DXGIFormat.D24_UNORM_S8_UINT, DXGIFormat.R24_UNORM_X8_TYPELESS, DXGIFormat.X24_TYPELESS_G8_UINT:
            tf.format = SDL_GPU_TEXTUREFORMAT_D24_UNORM_S8_UINT;
            tf.numChannels = 2;
            tf.pixelSize = 4;
            break;
        case DXGIFormat.R8G8_TYPELESS:
            tf.format = SDL_GPU_TEXTUREFORMAT_R8G8_UINT;
            tf.numChannels = 2;
            tf.pixelSize = 2;
            break;
        case DXGIFormat.R8G8_UNORM:
            tf.format = SDL_GPU_TEXTUREFORMAT_R8G8_UNORM;
            tf.numChannels = 2;
            tf.pixelSize = 2;
            break;
        case DXGIFormat.R8G8_UINT:
            tf.format = SDL_GPU_TEXTUREFORMAT_R8G8_UINT;
            tf.numChannels = 2;
            tf.pixelSize = 2;
            break;
        case DXGIFormat.R8G8_SNORM:
            tf.format = SDL_GPU_TEXTUREFORMAT_R8G8_SNORM;
            tf.numChannels = 2;
            tf.pixelSize = 2;
            break;
        case DXGIFormat.R8G8_SINT:
            tf.format = SDL_GPU_TEXTUREFORMAT_R8G8_INT;
            tf.numChannels = 2;
            tf.pixelSize = 2;
            break;
        case DXGIFormat.R16_TYPELESS:
            tf.format = SDL_GPU_TEXTUREFORMAT_R16_UINT;
            tf.numChannels = 1;
            tf.pixelSize = 2;
            break;
        case DXGIFormat.R16_FLOAT:
            tf.format = SDL_GPU_TEXTUREFORMAT_R16_FLOAT;
            tf.numChannels = 1;
            tf.pixelSize = 2;
            break;
        case DXGIFormat.R16_UNORM, DXGIFormat.D16_UNORM:
            tf.format = SDL_GPU_TEXTUREFORMAT_R16_UNORM;
            tf.numChannels = 1;
            tf.pixelSize = 2;
            break;
        case DXGIFormat.R16_UINT:
            tf.format = SDL_GPU_TEXTUREFORMAT_R16_UINT;
            tf.numChannels = 1;
            tf.pixelSize = 2;
            break;
        case DXGIFormat.R16_SNORM:
            tf.format = SDL_GPU_TEXTUREFORMAT_R16_SNORM;
            tf.numChannels = 1;
            tf.pixelSize = 2;
            break;
        case DXGIFormat.R16_SINT:
            tf.format = SDL_GPU_TEXTUREFORMAT_R16_INT;
            tf.numChannels = 1;
            tf.pixelSize = 2;
            break;
        case DXGIFormat.R8_TYPELESS:
            tf.format = SDL_GPU_TEXTUREFORMAT_R8_UINT;
            tf.numChannels = 1;
            tf.pixelSize = 1;
            break;
        case DXGIFormat.R8_UNORM:
            tf.format = SDL_GPU_TEXTUREFORMAT_R8_UNORM;
            tf.numChannels = 1;
            tf.pixelSize = 1;
            break;
        case DXGIFormat.R8_UINT:
            tf.format = SDL_GPU_TEXTUREFORMAT_R8_UINT;
            tf.numChannels = 1;
            tf.pixelSize = 1;
            break;
        case DXGIFormat.R8_SNORM:
            tf.format = SDL_GPU_TEXTUREFORMAT_R8_SNORM;
            tf.numChannels = 1;
            tf.pixelSize = 1;
            break;
        case DXGIFormat.R8_SINT:
            tf.format = SDL_GPU_TEXTUREFORMAT_R8_INT;
            tf.numChannels = 1;
            tf.pixelSize = 1;
            break;
        case DXGIFormat.A8_UNORM:
            tf.format = SDL_GPU_TEXTUREFORMAT_A8_UNORM;
            tf.numChannels = 1;
            tf.pixelSize = 1;
            break;
        case DXGIFormat.BC1_UNORM:
            tf.format = SDL_GPU_TEXTUREFORMAT_BC1_RGBA_UNORM;
            tf.numChannels = 4;
            tf.blockSize = 8;
            break;
        case DXGIFormat.BC2_UNORM:
            tf.format = SDL_GPU_TEXTUREFORMAT_BC2_RGBA_UNORM;
            tf.numChannels = 4;
            tf.blockSize = 16;
            break;
        case DXGIFormat.BC3_UNORM:
            tf.format = SDL_GPU_TEXTUREFORMAT_BC3_RGBA_UNORM;
            tf.numChannels = 4;
            tf.blockSize = 16;
            break;
        case DXGIFormat.BC4_UNORM, DXGIFormat.BC4_SNORM:
            tf.format = SDL_GPU_TEXTUREFORMAT_BC4_R_UNORM;
            tf.numChannels = 1;
            tf.blockSize = 8;
            break;
        case DXGIFormat.BC5_UNORM, DXGIFormat.BC5_SNORM:
            tf.format = SDL_GPU_TEXTUREFORMAT_BC5_RG_UNORM;
            tf.numChannels = 2;
            tf.blockSize = 16;
            break;
        case DXGIFormat.B5G6R5_UNORM:
            tf.format = SDL_GPU_TEXTUREFORMAT_B5G6R5_UNORM;
            tf.numChannels = 3;
            tf.pixelSize = 2;
            break;
        case DXGIFormat.B5G5R5A1_UNORM:
            tf.format = SDL_GPU_TEXTUREFORMAT_B5G5R5A1_UNORM;
            tf.numChannels = 4;
            tf.pixelSize = 2;
            break;
        case DXGIFormat.B8G8R8A8_UNORM, DXGIFormat.B8G8R8X8_UNORM, DXGIFormat.B8G8R8A8_TYPELESS,
             DXGIFormat.B8G8R8A8_UNORM_SRGB, DXGIFormat.B8G8R8X8_TYPELESS, DXGIFormat.B8G8R8X8_UNORM_SRGB:
            tf.format = SDL_GPU_TEXTUREFORMAT_B8G8R8A8_UNORM;
            tf.numChannels = 4;
            tf.pixelSize = 4;
            break;
        case DXGIFormat.BC6H_SF16:
            tf.format = SDL_GPU_TEXTUREFORMAT_BC6H_RGB_FLOAT;
            tf.numChannels = 4;
            tf.blockSize = 16;
            break;
        case DXGIFormat.BC6H_UF16:
            tf.format = SDL_GPU_TEXTUREFORMAT_BC6H_RGB_UFLOAT;
            tf.numChannels = 4;
            tf.blockSize = 16;
            break;
        case DXGIFormat.BC7_UNORM, DXGIFormat.BC7_UNORM_SRGB:
            tf.format = SDL_GPU_TEXTUREFORMAT_BC7_RGBA_UNORM;
            tf.numChannels = 4;
            tf.blockSize = 16;
            break;
        case DXGIFormat.ASTC_4X4_UNORM, DXGIFormat.ASTC_4X4_UNORM_SRGB:
            tf.format = SDL_GPU_TEXTUREFORMAT_ASTC_4x4_UNORM;
            tf.numChannels = 4;
            tf.blockSize = 16;
            break;
        // TODO: other ASTC formats
        default:
            return false;
    }
    
    return true;
}

/**
 * Converts SDL GPU texture format to DXGI format.
 *
 * Params:
 *   fmt = SDL_GPUTextureFormat.
 *   dxgiFmt = Output DXGIFormat.
 * Returns:
 *   true if format is supported, false otherwise.
 */
bool sdlFormatToDXGIFormat(SDL_GPUTextureFormat fmt, out DXGIFormat dxgiFmt)
{
    switch (fmt)
    {
        case SDL_GPU_TEXTUREFORMAT_A8_UNORM:
            dxgiFmt = DXGIFormat.A8_UNORM;
            break;
        case SDL_GPU_TEXTUREFORMAT_R8_UNORM:
            dxgiFmt = DXGIFormat.R8_UNORM;
            break;
        case SDL_GPU_TEXTUREFORMAT_R8G8_UNORM:
            dxgiFmt = DXGIFormat.R8G8_UNORM;
            break;
        case SDL_GPU_TEXTUREFORMAT_R8G8B8A8_UNORM:
            dxgiFmt = DXGIFormat.R8G8B8A8_UNORM;
            break;
        case SDL_GPU_TEXTUREFORMAT_R16_UNORM:
            dxgiFmt = DXGIFormat.R16_UNORM;
            break;
        case SDL_GPU_TEXTUREFORMAT_R16G16_UNORM:
            dxgiFmt = DXGIFormat.R16G16_UNORM;
            break;
        case SDL_GPU_TEXTUREFORMAT_R16G16B16A16_UNORM:
            dxgiFmt = DXGIFormat.R16G16B16A16_UNORM;
            break;
        case SDL_GPU_TEXTUREFORMAT_R10G10B10A2_UNORM:
            dxgiFmt = DXGIFormat.R10G10B10A2_UNORM;
            break;
        case SDL_GPU_TEXTUREFORMAT_B5G6R5_UNORM:
            dxgiFmt = DXGIFormat.B5G6R5_UNORM;
            break;
        case SDL_GPU_TEXTUREFORMAT_B5G5R5A1_UNORM:
            dxgiFmt = DXGIFormat.B5G5R5A1_UNORM;
            break;
        case SDL_GPU_TEXTUREFORMAT_B4G4R4A4_UNORM:
            dxgiFmt = DXGIFormat.B4G4R4A4_UNORM;
            break;
        case SDL_GPU_TEXTUREFORMAT_B8G8R8A8_UNORM:
            dxgiFmt = DXGIFormat.B8G8R8A8_UNORM;
            break;
        case SDL_GPU_TEXTUREFORMAT_BC1_RGBA_UNORM:
            dxgiFmt = DXGIFormat.BC1_UNORM;
            break;
        case SDL_GPU_TEXTUREFORMAT_BC2_RGBA_UNORM:
            dxgiFmt = DXGIFormat.BC2_UNORM;
            break;
        case SDL_GPU_TEXTUREFORMAT_BC3_RGBA_UNORM:
            dxgiFmt = DXGIFormat.BC3_UNORM;
            break;
        case SDL_GPU_TEXTUREFORMAT_BC4_R_UNORM:
            dxgiFmt = DXGIFormat.BC4_UNORM;
            break;
        case SDL_GPU_TEXTUREFORMAT_BC5_RG_UNORM:
            dxgiFmt = DXGIFormat.BC5_UNORM;
            break;
        case SDL_GPU_TEXTUREFORMAT_BC7_RGBA_UNORM:
            dxgiFmt = DXGIFormat.BC7_UNORM;
            break;
        case SDL_GPU_TEXTUREFORMAT_BC6H_RGB_FLOAT:
            dxgiFmt = DXGIFormat.BC6H_SF16;
            break;
        case SDL_GPU_TEXTUREFORMAT_BC6H_RGB_UFLOAT:
            dxgiFmt = DXGIFormat.BC6H_UF16;
            break;
        case SDL_GPU_TEXTUREFORMAT_R8_SNORM:
            dxgiFmt = DXGIFormat.R8_SNORM;
            break;
        case SDL_GPU_TEXTUREFORMAT_R8G8_SNORM:
            dxgiFmt = DXGIFormat.R8G8_SNORM;
            break;
        case SDL_GPU_TEXTUREFORMAT_R8G8B8A8_SNORM:
            dxgiFmt = DXGIFormat.R8G8B8A8_SNORM;
            break;
        case SDL_GPU_TEXTUREFORMAT_R16_SNORM:
            dxgiFmt = DXGIFormat.R16_SNORM;
            break;
        case SDL_GPU_TEXTUREFORMAT_R16G16_SNORM:
            dxgiFmt = DXGIFormat.R16G16_SNORM;
            break;
        case SDL_GPU_TEXTUREFORMAT_R16G16B16A16_SNORM:
            dxgiFmt = DXGIFormat.R16G16B16A16_SNORM;
            break;
        case SDL_GPU_TEXTUREFORMAT_R16_FLOAT:
            dxgiFmt = DXGIFormat.R16_FLOAT;
            break;
        case SDL_GPU_TEXTUREFORMAT_R16G16_FLOAT:
            dxgiFmt = DXGIFormat.R16G16_FLOAT;
            break;
        case SDL_GPU_TEXTUREFORMAT_R16G16B16A16_FLOAT:
            dxgiFmt = DXGIFormat.R16G16B16A16_FLOAT;
            break;
        case SDL_GPU_TEXTUREFORMAT_R32_FLOAT:
            dxgiFmt = DXGIFormat.R32_FLOAT;
            break;
        case SDL_GPU_TEXTUREFORMAT_R32G32_FLOAT:
            dxgiFmt = DXGIFormat.R32G32_FLOAT;
            break;
        case SDL_GPU_TEXTUREFORMAT_R32G32B32A32_FLOAT:
            dxgiFmt = DXGIFormat.R32G32B32A32_FLOAT;
            break;
        case SDL_GPU_TEXTUREFORMAT_R11G11B10_UFLOAT:
            dxgiFmt = DXGIFormat.R11G11B10_FLOAT;
            break;
        case SDL_GPU_TEXTUREFORMAT_R8_UINT:
            dxgiFmt = DXGIFormat.R8_UINT;
            break;
        case SDL_GPU_TEXTUREFORMAT_R8G8_UINT:
            dxgiFmt = DXGIFormat.R8G8_UINT;
            break;
        case SDL_GPU_TEXTUREFORMAT_R8G8B8A8_UINT:
            dxgiFmt = DXGIFormat.R8G8B8A8_UINT;
            break;
        case SDL_GPU_TEXTUREFORMAT_R16_UINT:
            dxgiFmt = DXGIFormat.R16_UINT;
            break;
        case SDL_GPU_TEXTUREFORMAT_R16G16_UINT:
            dxgiFmt = DXGIFormat.R16G16_UINT;
            break;
        case SDL_GPU_TEXTUREFORMAT_R16G16B16A16_UINT:
            dxgiFmt = DXGIFormat.R16G16B16A16_UINT;
            break;
        case SDL_GPU_TEXTUREFORMAT_R32_UINT:
            dxgiFmt = DXGIFormat.R32_UINT;
            break;
        case SDL_GPU_TEXTUREFORMAT_R32G32_UINT:
            dxgiFmt = DXGIFormat.R32G32_UINT;
            break;
        case SDL_GPU_TEXTUREFORMAT_R32G32B32A32_UINT:
            dxgiFmt = DXGIFormat.R32G32B32A32_UINT;
            break;
        case SDL_GPU_TEXTUREFORMAT_R8_INT:
            dxgiFmt = DXGIFormat.R8_SINT;
            break;
        case SDL_GPU_TEXTUREFORMAT_R8G8_INT:
            dxgiFmt = DXGIFormat.R8G8_SINT;
            break;
        case SDL_GPU_TEXTUREFORMAT_R8G8B8A8_INT:
            dxgiFmt = DXGIFormat.R8G8B8A8_SINT;
            break;
        case SDL_GPU_TEXTUREFORMAT_R16_INT:
            dxgiFmt = DXGIFormat.R16_SINT;
            break;
        case SDL_GPU_TEXTUREFORMAT_R16G16_INT:
            dxgiFmt = DXGIFormat.R16G16_SINT;
            break;
        case SDL_GPU_TEXTUREFORMAT_R16G16B16A16_INT:
            dxgiFmt = DXGIFormat.R16G16B16A16_SINT;
            break;
        case SDL_GPU_TEXTUREFORMAT_R32_INT:
            dxgiFmt = DXGIFormat.R32_SINT;
            break;
        case SDL_GPU_TEXTUREFORMAT_R32G32_INT:
            dxgiFmt = DXGIFormat.R32G32_SINT;
            break;
        case SDL_GPU_TEXTUREFORMAT_R32G32B32A32_INT:
            dxgiFmt = DXGIFormat.R32G32B32A32_SINT;
            break;
        case SDL_GPU_TEXTUREFORMAT_R8G8B8A8_UNORM_SRGB:
            dxgiFmt = DXGIFormat.R8G8B8A8_UNORM_SRGB;
            break;
        case SDL_GPU_TEXTUREFORMAT_B8G8R8A8_UNORM_SRGB:
            dxgiFmt = DXGIFormat.B8G8R8A8_UNORM_SRGB;
            break;
        case SDL_GPU_TEXTUREFORMAT_BC1_RGBA_UNORM_SRGB:
            dxgiFmt = DXGIFormat.BC1_UNORM_SRGB;
            break;
        case SDL_GPU_TEXTUREFORMAT_BC2_RGBA_UNORM_SRGB:
            dxgiFmt = DXGIFormat.BC2_UNORM_SRGB;
            break;
        case SDL_GPU_TEXTUREFORMAT_BC3_RGBA_UNORM_SRGB:
            dxgiFmt = DXGIFormat.BC3_UNORM_SRGB;
            break;
        case SDL_GPU_TEXTUREFORMAT_BC7_RGBA_UNORM_SRGB:
            dxgiFmt = DXGIFormat.BC7_UNORM_SRGB;
            break;
        case SDL_GPU_TEXTUREFORMAT_D16_UNORM:
            dxgiFmt = DXGIFormat.D16_UNORM;
            break;
        case SDL_GPU_TEXTUREFORMAT_D24_UNORM:
            dxgiFmt = DXGIFormat.D24_UNORM_S8_UINT;
            break;
        case SDL_GPU_TEXTUREFORMAT_D32_FLOAT:
            dxgiFmt = DXGIFormat.D32_FLOAT;
            break;
        case SDL_GPU_TEXTUREFORMAT_D24_UNORM_S8_UINT:
            dxgiFmt = DXGIFormat.D24_UNORM_S8_UINT;
            break;
        case SDL_GPU_TEXTUREFORMAT_D32_FLOAT_S8_UINT:
            dxgiFmt = DXGIFormat.D32_FLOAT_S8X24_UINT;
            break;
        case SDL_GPU_TEXTUREFORMAT_ASTC_4x4_UNORM:
            dxgiFmt = DXGIFormat.ASTC_4X4_UNORM;
            break;
        
        /*
        // TODO: other ASTC formats
        SDL_GPU_TEXTUREFORMAT_ASTC_5x4_UNORM,
        SDL_GPU_TEXTUREFORMAT_ASTC_5x5_UNORM,
        SDL_GPU_TEXTUREFORMAT_ASTC_6x5_UNORM,
        SDL_GPU_TEXTUREFORMAT_ASTC_6x6_UNORM,
        SDL_GPU_TEXTUREFORMAT_ASTC_8x5_UNORM,
        SDL_GPU_TEXTUREFORMAT_ASTC_8x6_UNORM,
        SDL_GPU_TEXTUREFORMAT_ASTC_8x8_UNORM,
        SDL_GPU_TEXTUREFORMAT_ASTC_10x5_UNORM,
        SDL_GPU_TEXTUREFORMAT_ASTC_10x6_UNORM,
        SDL_GPU_TEXTUREFORMAT_ASTC_10x8_UNORM,
        SDL_GPU_TEXTUREFORMAT_ASTC_10x10_UNORM,
        SDL_GPU_TEXTUREFORMAT_ASTC_12x10_UNORM,
        SDL_GPU_TEXTUREFORMAT_ASTC_12x12_UNORM,
        SDL_GPU_TEXTUREFORMAT_ASTC_4x4_UNORM_SRGB,
        SDL_GPU_TEXTUREFORMAT_ASTC_5x4_UNORM_SRGB,
        SDL_GPU_TEXTUREFORMAT_ASTC_5x5_UNORM_SRGB,
        SDL_GPU_TEXTUREFORMAT_ASTC_6x5_UNORM_SRGB,
        SDL_GPU_TEXTUREFORMAT_ASTC_6x6_UNORM_SRGB,
        SDL_GPU_TEXTUREFORMAT_ASTC_8x5_UNORM_SRGB,
        SDL_GPU_TEXTUREFORMAT_ASTC_8x6_UNORM_SRGB,
        SDL_GPU_TEXTUREFORMAT_ASTC_8x8_UNORM_SRGB,
        SDL_GPU_TEXTUREFORMAT_ASTC_10x5_UNORM_SRGB,
        SDL_GPU_TEXTUREFORMAT_ASTC_10x6_UNORM_SRGB,
        SDL_GPU_TEXTUREFORMAT_ASTC_10x8_UNORM_SRGB,
        SDL_GPU_TEXTUREFORMAT_ASTC_10x10_UNORM_SRGB,
        SDL_GPU_TEXTUREFORMAT_ASTC_12x10_UNORM_SRGB,
        SDL_GPU_TEXTUREFORMAT_ASTC_12x12_UNORM_SRGB,
        SDL_GPU_TEXTUREFORMAT_ASTC_4x4_FLOAT,
        SDL_GPU_TEXTUREFORMAT_ASTC_5x4_FLOAT,
        SDL_GPU_TEXTUREFORMAT_ASTC_5x5_FLOAT,
        SDL_GPU_TEXTUREFORMAT_ASTC_6x5_FLOAT,
        SDL_GPU_TEXTUREFORMAT_ASTC_6x6_FLOAT,
        SDL_GPU_TEXTUREFORMAT_ASTC_8x5_FLOAT,
        SDL_GPU_TEXTUREFORMAT_ASTC_8x6_FLOAT,
        SDL_GPU_TEXTUREFORMAT_ASTC_8x8_FLOAT,
        SDL_GPU_TEXTUREFORMAT_ASTC_10x5_FLOAT,
        SDL_GPU_TEXTUREFORMAT_ASTC_10x6_FLOAT,
        SDL_GPU_TEXTUREFORMAT_ASTC_10x8_FLOAT,
        SDL_GPU_TEXTUREFORMAT_ASTC_10x10_FLOAT,
        SDL_GPU_TEXTUREFORMAT_ASTC_12x10_FLOAT,
        SDL_GPU_TEXTUREFORMAT_ASTC_12x12_FLOAT
        */
        
        default:
            return false;
    }
    
    return true;
}
