/*
Copyright (c) 2019-2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

/**
 * Provides the scene graph node.
 *
 * Description:
 * The `dagon.graphics.entity` module provides the `Entity` class, which represents
 * a node in the scene graph and supports hierarchical transformations.
 *
 * Copyright: Timur Gafarov 2019-2026
 * License: $(LINK2 https://boost.org/LICENSE_1_0.txt, Boost License 1.0).
 * Authors: Timur Gafarov
 */
module dagon.graphics.entity;

import dlib.core.ownership;
import dlib.math.vector;
import dlib.math.matrix;
import dlib.math.transformation;
import dlib.math.quaternion;
import dlib.math.utils;
import dlib.container.array;

import dagon.core.logger;
import dagon.core.event;
import dagon.core.time;
import dagon.core.updateable;
import dagon.graphics.drawable;
import dagon.graphics.material;

enum EntityLayer
{
    Scene = 0,
    Background = 1,
    Foreground = 2
}

class Entity: Owner, Updateable
{
    Array!Entity children;
    Entity parent;
    EntityController controller;
    Matrix4x4f transformation;
    Matrix4x4f invTransformation;
    Matrix4x4f modelMatrix;
    Matrix4x4f invModelMatrix;
    Matrix4x4f prevModelMatrix;
    Vector3f position;
    Quaternionf rotation;
    Vector3f scaling;
    Drawable drawable;
    Material material;
    EntityLayer layer;
    float opacity = 1.0f;
    float motionBlurMask = 1.0f;
    bool visible = true;
    bool castShadow = true;
    bool receiveDecals = true;
    bool dynamic = false;
    bool transformationValid = false;
    bool modelMatricesValid = false;
    
    this(Owner owner)
    {
        super(owner);
        modelMatrix = Matrix4x4f.identity;
        invModelMatrix = Matrix4x4f.identity;
        prevModelMatrix = Matrix4x4f.identity;
        position = Vector3f(0.0f, 0.0f, 0.0f);
        rotation = Quaternionf.identity;
        scaling = Vector3f(1.0f, 1.0f, 1.0f);
    }
    
    ~this()
    {
        children.free();
    }
    
    void addChild(Entity child)
    {
        child.parent = this;
        child.dynamic = dynamic;
        child.transformationValid = false;
        children.append(child);
    }
    
    void update()
    {
        update(Time(0.0, 0.0));
    }
    
    void update(Time t)
    {
        if (controller)
        {
            controller.update(t);
            modelMatricesValid = false;
        }
        else
        {
            if (!transformationValid)
            {
                transformation = trsMatrix(position, rotation, scaling);
                invTransformation = transformation.inverse;
                transformationValid = true;
                modelMatricesValid = false;
            }
        }
    }
    
    /// Recalculates modelMatrix and invModelMatrix for the entity and its children.
    void postUpdate(Time t)
    {
        prevModelMatrix = modelMatrix;
        
        if (modelMatricesValid)
            return;
        
        if (controller)
        {
            controller.postUpdate(t);
        }
        else if (parent)
        {
            modelMatrix = parent.modelMatrix * transformation;
            invModelMatrix = modelMatrix.inverse;
        }
        else
        {
            modelMatrix = transformation;
            invModelMatrix = invTransformation;
        }
        
        foreach(child; children)
        {
            child.postUpdate(t);
        }
        
        modelMatricesValid = true;
        
        // For dynamic entities transformation is recalculated every frame
        transformationValid = !dynamic;
    }
    
    /// Returns the absolute position of the entity.
    Vector3f positionAbsolute()
    {
        return modelMatrix.translation;
    }
    
    /// Returns the absolute rotation of the entity.
    Quaternionf rotationAbsolute()
    {
        if (parent)
            return parent.rotationAbsolute * rotation;
        else
            return rotation;
    }
    
    Vector3f direction()
    {
        return transformation.forward;
    }
    
    Vector3f directionAbsolute()
    {
        return modelMatrix.forward;
    }
    
    Vector3f right()
    {
        return transformation.right;
    }
    
    Vector3f rightAbsolute()
    {
        return modelMatrix.right;
    }
    
    Vector3f up()
    {
        return transformation.up;
    }
    
    Vector3f upAbsolute()
    {
        return modelMatrix.up;
    }
    
    /// Translates the entity by the given vector.
    void translate(Vector3f v)
    {
        position += v;
    }

    /// Translates the entity by the given vector components.
    void translate(float vx, float vy, float vz)
    {
        position += Vector3f(vx, vy, vz);
    }

    /// Moves the entity forward by the given speed.
    void move(float speed)
    {
        position += transformation.forward * speed;
    }
    
    /// Strafes (moves to the right) by the given speed.
    void strafe(float speed)
    {
        position += transformation.right * speed;
    }

    /// Lifts (moves up) by the given speed.
    void lift(float speed)
    {
        position += transformation.up * speed;
    }
    
    /// Rotates the entity by the given Euler angles (degrees).
    void rotate(Vector3f v)
    {
        auto r =
            rotationQuaternion!float(Axis.x, degtorad(v.x)) *
            rotationQuaternion!float(Axis.y, degtorad(v.y)) *
            rotationQuaternion!float(Axis.z, degtorad(v.z));
        rotation *= r;
    }
    
    /// Rotates the entity by the given Euler angles (degrees).
    void rotate(float x, float y, float z)
    {
        rotate(Vector3f(x, y, z));
    }
    
    /// Rotates the entity around the local X axis.
    void pitch(float angle)
    {
        rotation *= rotationQuaternion!float(Axis.x, degtorad(angle));
    }

    /// Rotates the entity around the local Y axis.
    void turn(float angle)
    {
        rotation *= rotationQuaternion!float(Axis.y, degtorad(angle));
    }

    /// Rotates the entity around the local Z axis.
    void roll(float angle)
    {
        rotation *= rotationQuaternion!float(Axis.z, degtorad(angle));
    }

    /// Scales the entity uniformly.
    void scale(float s)
    {
        scaling += Vector3f(s, s, s);
    }

    /// Scales the entity non-uniformly by the given vector.
    void scale(Vector3f s)
    {
        scaling += s;
    }
}

abstract class EntityController: EventListener, Updateable
{
    Entity entity;
    
    this(EventManager eventManager, Entity entity)
    {
        super(eventManager, entity);
        this.entity = entity;
        entity.controller = this;
    }
    
    void update(Time t)
    {
        //
    }
    
    void postUpdate(Time t)
    {
        //
    }
}

class PositionSync: EntityController
{
    Entity targetEntity;
    
    this(EventManager eventManager, Entity entity, Entity targetEntity)
    {
        super(eventManager, entity);
        this.targetEntity = targetEntity;
    }
    
    override void update(Time t)
    {
        entity.transformation = trsMatrix(targetEntity.positionAbsolute, entity.rotation, entity.scaling);
        entity.invTransformation = entity.transformation.inverse;
        entity.prevModelMatrix = entity.modelMatrix;
        entity.modelMatrix = entity.transformation;
        entity.invModelMatrix = entity.invTransformation;
    }
}

/**
 * Constructs a transformation matrix from translation, rotation, and scaling.
 *
 * Params:
 *   t = Translation vector.
 *   r = Rotation quaternion.
 *   s = Scaling vector.
 * Returns:
 *   The resulting transformation matrix.
 */
Matrix4x4f trsMatrix(Vector3f t, Quaternionf r, Vector3f s)
{
    Matrix4x4f res = Matrix4x4f.identity;
    Matrix3x3f rm = r.toMatrix3x3;
    res.a11 = rm.a11 * s.x; res.a12 = rm.a12 * s.x; res.a13 = rm.a13 * s.x;
    res.a21 = rm.a21 * s.y; res.a22 = rm.a22 * s.y; res.a23 = rm.a23 * s.y;
    res.a31 = rm.a31 * s.z; res.a32 = rm.a32 * s.z; res.a33 = rm.a33 * s.z;
    res.a14 = t.x;
    res.a24 = t.y;
    res.a34 = t.z;
    return res;
}
