/*
Copyright (c) 2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

/**
 * Lightmap UV unwrap utilities for mesh geometry.
 *
 * This module creates a new mesh with duplicated vertices and
 * generates a lightmap UV atlas in the mesh's primary texcoord channel.
 */
module dagon.graphics.lightmap;

import std.math;
import std.algorithm;

import dlib.core.memory;
import dlib.core.ownership;
import dlib.math.vector;

import dagon.core.gpu;
import dagon.graphics.mesh;

Vector2f projectToLightmapPlane(Vector3f point, Vector3f normal)
{
    float ax = abs(normal.x);
    float ay = abs(normal.y);
    float az = abs(normal.z);

    if (ax >= ay && ax >= az)
        return Vector2f(point.y, point.z);
    if (ay >= az)
        return Vector2f(point.x, point.z);

    return Vector2f(point.x, point.y);
}

Vector2f normalizeUV(Vector2f uv, Vector2f minuv, Vector2f extent)
{
    Vector2f result;
    result.x = extent.x > 0.0f ? (uv.x - minuv.x) / extent.x : 0.5f;
    result.y = extent.y > 0.0f ? (uv.y - minuv.y) / extent.y : 0.5f;
    return result;
}

class LightmappedMesh: Mesh
{
    /// The UV padding inside each atlas cell.
    float padding = 0.001f;
    
    this(GPU gpu, Owner owner)
    {
        super(gpu, owner);
    }
    
    ~this()
    {
        if (vertices.length)
            Delete(vertices);
        if (normals.length)
            Delete(normals);
        if (texcoords.length)
            Delete(texcoords);
        if (indices.length)
            Delete(indices);
    }
    
    /**
     * Creates a new mesh with duplicated vertices and a simple lightmap UV atlas.
     */
    bool generate(Mesh source)
    {
        if (unwrap(source))
        {
            dataReady = true;
            prepareBuffers();
            calcBoundingBox();
            // TODO: generate lightmap material
            return true;
        }
        else
            return false;
    }
    
    protected bool unwrap(Mesh source)
    {
        size_t numTriangles = source.indices.length;
        if (numTriangles == 0)
        {
            return false;
        }
        
        size_t numVertices = numTriangles * 3;
        
        vertices = New!(Vector3f[])(numVertices);
        normals = New!(Vector3f[])(numVertices);
        texcoords = New!(Vector2f[])(numVertices);
        indices = New!(uint[3][])(numTriangles);
        
        // TODO
        
        return false;
    }
}
