/*
Copyright (c) 2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module dagon.graphics.lut;

import dlib.core.memory;
import dlib.core.ownership;

import dagon.core.sdl3;
import dagon.core.gpu;
import dagon.core.logger;
import dagon.graphics.texture;

enum LUTFormat
{
    Undefined = 0,
    GPUImage = 1,
    Hald = 2,
    Texture3D = 3
}

void convertGPUImageLUTto3DTexture(TextureBuffer* lut)
{
    if (lut.size.width != 512 || lut.size.height != 512)
    {
        logError("GPUImage LUT size should be 512x512");
        return;
    }
    
    if (lut.format.format != SDL_GPU_TEXTUREFORMAT_R8G8B8A8_UNORM)
    {
        logError("GPUImage LUT should be SDL_GPU_TEXTUREFORMAT_R8G8B8A8_UNORM");
        return;
    }
    
    uint numChannels = lut.format.numChannels;
    
    TextureBuffer lut3D;
    lut3D.size.width = 64;
    lut3D.size.height = 64;
    lut3D.size.depth = 64;
    lut3D.format.type = SDL_GPU_TEXTURETYPE_3D;
    lut3D.format.format = SDL_GPU_TEXTUREFORMAT_R8G8B8A8_UNORM;
    lut3D.format.blockSize = 0;
    lut3D.format.numChannels = 4;
    lut3D.format.pixelSize = 4;
    lut3D.mipLevels = 1;
    lut3D.data = New!(ubyte[])(64 * 64 * 64 * 4);
    
    for (uint z = 0; z < 64; z++)
    {
        uint quadX = z % 8;
        uint quadY = z / 8;
        
        for (uint y = 0; y < 64; y++)
        {
            for (uint x = 0; x < 64; x++)
            {
                uint px = quadX * 64 + x;
                uint py = quadY * 64 + y;
                
                size_t offset = (py * 512 + px) * numChannels;
                ubyte r = lut.data[offset];
                ubyte g = lut.data[offset + 1];
                ubyte b = lut.data[offset + 2];
                
                uint idx = ((z * 64 + y) * 64 + x) * 4;
                lut3D.data[idx] = r;
                lut3D.data[idx + 1] = g;
                lut3D.data[idx + 2] = b;
                lut3D.data[idx + 3] = 255;
            }
        }
    }
    
    Delete(lut.data);
    
    *lut = lut3D;
}

/*
void convertGPUImageLUTto3DTexture(TextureBuffer lut, Texture lutTexture)
{
    if (lut.size.width != 512 || lut.size.height != 512)
    {
        logError("GPUImage LUT size should be 512x512");
        return;
    }
    
    if (lut.format.format != SDL_GPU_TEXTUREFORMAT_R8G8B8A8_UNORM)
    {
        logError("GPUImage LUT should be SDL_GPU_TEXTUREFORMAT_R8G8B8A8_UNORM");
        return;
    }
    
    uint numChannels = lut.format.numChannels;
    
    TextureBuffer lut3D;
    lut3D.size.width = 64;
    lut3D.size.height = 64;
    lut3D.size.depth = 64;
    lut3D.format.type = SDL_GPU_TEXTURETYPE_3D;
    lut3D.format.format = SDL_GPU_TEXTUREFORMAT_R8G8B8A8_UNORM;
    lut3D.format.blockSize = 0;
    lut3D.format.numChannels = 4;
    lut3D.format.pixelSize = 4;
    lut3D.mipLevels = 1;
    lut3D.data = New!(ubyte[])(64 * 64 * 64 * 4);
    
    for (uint z = 0; z < 64; z++)
    {
        uint quadX = z % 8;
        uint quadY = z / 8;
        
        for (uint y = 0; y < 64; y++)
        {
            for (uint x = 0; x < 64; x++)
            {
                uint px = quadX * 64 + x;
                uint py = quadY * 64 + y;
                
                size_t offset = (py * 512 + px) * numChannels;
                ubyte r = lut.data[offset];
                ubyte g = lut.data[offset + 1];
                ubyte b = lut.data[offset + 2];
                
                uint idx = ((z * 64 + y) * 64 + x) * 4;
                lut3D.data[idx] = r;
                lut3D.data[idx + 1] = g;
                lut3D.data[idx + 2] = b;
                lut3D.data[idx + 3] = 255;
            }
        }
    }
    
    TextureCreationOptions options = {
        generateMipmaps: false,
        repeatUV: false,
        anisotropicFiltering: false
    };
    if (!lutTexture.create(&lut3D, &options))
    {
        logError("Failed to create 3D LUT texture");
    }
    
    Delete(lut3D.data);
}

Texture convertGPUImageLUTto3DTexture(GPU gpu, TextureBuffer lut, Owner textureOwner = null)
{
    Texture lutTexture = New!Texture(gpu, textureOwner);
    convertGPUImageLUTto3DTexture(lut, lutTexture);
    return lutTexture;
}
*/
