/*
Copyright (c) 2017-2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

/**
 * Defines mesh data structure and utilities.
 *
 * Description:
 * The `dagon.graphics.mesh` module provides the `Mesh` class for storing
 * and rendering 3D geometry (indexed triangle mesh). The module also defines
 * the `VertexAttribute` enumeration for standard attribute locations used in the renderer.
 *
 * Copyright: Timur Gafarov 2017-2026
 * License: $(LINK2 https://boost.org/LICENSE_1_0.txt, Boost License 1.0).
 * Authors: Timur Gafarov
 */
module dagon.graphics.mesh;

import std.algorithm;

import dlib.core.memory;
import dlib.core.ownership;
import dlib.geometry.triangle;
import dlib.math.vector;
import dlib.math.base;
import dlib.geometry.aabb;

import dagon.core.sdl3;
import dagon.core.gpu;
import dagon.core.logger;
import dagon.graphics.drawable;
import dagon.graphics.material;
import dagon.graphics.state;

/**
 * Enumerates vertex attribute locations for mesh data.
 */
enum VertexAttribute
{
    /// Positions - array of float[3].
    Position = 0,
    
    /// Texture coordinates - array of float[2].
    Texcoord = 1,
    
    /// Normals - array of float[3].
    Normal = 2,
    
    /// Tangents - array of float[4]
    Tangent = 3
}

/**
 * Interface for objects that provide access to a set of triangles.
 */
interface TriangleSet
{
    /**
     * Iterates over all triangles in the set.
     *
     * Params:
     *   dg = Delegate to call for each triangle.
     * Returns:
     *   0 if iteration completed, or the value returned by the delegate if nonzero.
     */
    int opApply(scope int delegate(Triangle* t) dg);
    
    /// Returns a total number of triangles in the set.
    size_t numTriangles();
}

/**
 * A group of triangles that use the same material.
 */
struct FaceGroup
{
    /// First triangle index in Mesh.indices array.
    uint firstTriangle;
    
    /// Number of triangles in the face group.
    uint numTriangles;
    
    /// Material for the face group.
    Material material;
    
    /// Face group visibility flag.
    bool visible;
}

/**
 * Represents an indexed 3D mesh.
 *
 * Description:
 * The `Mesh` class stores arrays of vertex positions, normals,
 * texture coordinates, triangle indices, and face groups,
 * managing their GPU counterparts.
 * It doesn't by itself allocate actual mesh data and doesn't
 * manage its lifetime. This is delegated to external code
 * on purpose, so that the mesh can store slices to other
 * buffers instead of dedicated allocations.
 */
class Mesh: Owner, Drawable, TriangleSet
{
    /// Symbolic name.
    string name;
    
    /// GPU object.
    GPU gpu;
    
    /// True if mesh data is ready for rendering.
    bool dataReady = false;

    /// True if the buffers are prepared and mesh can be rendered.
    bool canRender = false;

    /// Array of vertex positions.
    Vector3f[] vertices;

    /// Array of vertex normals.
    Vector3f[] normals;

    /// Array of vertex tangents (optional).
    Vector4f[] tangents;

    /// Array of texture coordinates.
    Vector2f[] texcoords;

    /// Array of triangle indices.
    uint[3][] indices;
    
    /// Array of face groups (optional).
    FaceGroup[] facegroups;
    
    /// Axis-aligned bounding box for the mesh.
    AABB boundingBox;
    
    /// GPU vertex positions buffer.
    SDL_GPUBuffer* positionBuffer;
    
    /// GPU texture coordinates buffer.
    SDL_GPUBuffer* texcoordBuffer;
    
    /// GPU normals buffer.
    SDL_GPUBuffer* normalBuffer;
    
    /// GPU tangents buffer.
    SDL_GPUBuffer* tangentBuffer;
    
    /// GPU index buffer.
    SDL_GPUBuffer* indexBuffer;
    
    /// Material for the mesh (optional).
    Material material;
    
    /**
     * Constructs a mesh with the given owner.
     *
     * Params:
     *   gpu   = GPU object.
     *   owner = The owner object.
     */
    this(GPU gpu, Owner owner)
    {
        super(owner);
        this.gpu = gpu;
    }
    
    /// Destructor.
    ~this()
    {
        release();
    }
    
    ///
    void release()
    {
        if (positionBuffer)
        {
            gpu.releaseBuffer(positionBuffer);
            positionBuffer = null;
        }
        
        if (texcoordBuffer)
        {
            gpu.releaseBuffer(texcoordBuffer);
            texcoordBuffer = null;
        }
        
        if (normalBuffer)
        {
            gpu.releaseBuffer(normalBuffer);
            normalBuffer = null;
        }
        
        if (tangentBuffer)
        {
            gpu.releaseBuffer(tangentBuffer);
            tangentBuffer = null;
        }
        
        if (indexBuffer)
        {
            gpu.releaseBuffer(indexBuffer);
            indexBuffer = null;
        }
    }
    
    /**
     * Calculates the axis-aligned bounding box for the mesh.
     * Sets the `boundingBox` member based on the furthest vertex extents.
     */
    void calcBoundingBox()
    {
        float maxDimension = 0.0f;
        
        foreach(v; vertices)
        {
            float ax = abs(v.x);
            float ay = abs(v.y);
            float az = abs(v.z);
            if (ax > maxDimension) maxDimension = ax;
            if (ay > maxDimension) maxDimension = ay;
            if (az > maxDimension) maxDimension = az;
        }
        
        Vector3f furthest = Vector3f(maxDimension, maxDimension, maxDimension);

        boundingBox = boxFromMinMaxPoints(-furthest, furthest);
    }
    
    /**
     * Returns the triangle at the specified face index.
     *
     * Params:
     *   faceIndex = The index of the triangle to retrieve.
     * Returns:
     *   The triangle at the given index.
     */
    Triangle getTriangle(size_t faceIndex)
    {
        uint[3] f = indices[faceIndex];
        Triangle tri;
        tri.v[0] = vertices[f[0]];
        tri.v[1] = vertices[f[1]];
        tri.v[2] = vertices[f[2]];
        tri.n[0] = normals[f[0]];
        tri.n[1] = normals[f[1]];
        tri.n[2] = normals[f[2]];
        tri.t1[0] = texcoords[f[0]];
        tri.t1[1] = texcoords[f[1]];
        tri.t1[2] = texcoords[f[2]];
        if (tangents.length)
        {
            tri.tg[0] = tangents[f[0]];
            tri.tg[1] = tangents[f[1]];
            tri.tg[2] = tangents[f[2]];
        }
        tri.normal = (tri.n[0] + tri.n[1] + tri.n[2]) / 3.0f;
        if (material)
            tri.materialIndex = material.id;
        return tri;
    }
    
    /**
     * Iterates over all triangles in the mesh.
     *
     * Params:
     *   dg = Delegate to call for each triangle.
     * Returns:
     *   0 if iteration completed, or the value returned by the delegate if nonzero.
     */
    int opApply(scope int delegate(Triangle* t) dg)
    {
        int result = 0;

        foreach(i, ref f; indices)
        {
            Triangle tri = getTriangle(i);
            result = dg(&tri);
            if (result)
                break;
        }

        return result;
    }
    
    /// Returns total number of triangles in the mesh.
    size_t numTriangles()
    {
        return indices.length;
    }
    
    /**
     * Generates smooth vertex normals for the mesh based on triangle geometry.
     * Overwrites the `normals` array with computed normals.
     * `normals` array should already be allocated.
     */
    bool generateNormals()
    {
        if (vertices.length == 0 ||
            normals.length == 0)
            return false;
        
        normals[] = Vector3f(0.0f, 0.0f, 0.0f);
        
        foreach(i, ref f; indices)
        {
            Vector3f v0 = vertices[f[0]];
            Vector3f v1 = vertices[f[1]];
            Vector3f v2 = vertices[f[2]];
            
            Vector3f p = cross(v1 - v0, v2 - v0);
            
            normals[f[0]] += p;
            normals[f[1]] += p;
            normals[f[2]] += p;
        }
        
        foreach(i, n; normals)
        {
            normals[i] = n.normalized;
        }
        
        return true;
    }
    
    /**
     * Generates tangent vectors for the mesh based on existing vertex data.
     * Requires vertices, normals, texcoords, and indices.
     * Overwrites the `tangents` array with computed tangents (alighed with U-direction in texture space).
     * `tangents` array should already be allocated.
     */
    bool generateTangents()
    {
        if (indices.length == 0 ||
            vertices.length == 0 ||
            normals.length == 0 ||
            tangents.length == 0 ||
            texcoords.length == 0)
            return false;
        
        // Temporary array for accumulating tangents and bitangents
        Vector3f[] tSum = New!(Vector3f[])(vertices.length);
        Vector3f[] bSum = New!(Vector3f[])(vertices.length);
        tSum[] = Vector3f(0.0f, 0.0f, 0.0f);
        bSum[] = Vector3f(0.0f, 0.0f, 0.0f);
        
        foreach(ref tri; indices)
        {
            uint i0 = tri[0];
            uint i1 = tri[1];
            uint i2 = tri[2];
            
            Vector3f v0 = vertices[i0];
            Vector3f v1 = vertices[i1];
            Vector3f v2 = vertices[i2];
            
            Vector2f uv0 = texcoords[i0];
            Vector2f uv1 = texcoords[i1];
            Vector2f uv2 = texcoords[i2];
            
            Vector3f edge1 = v1 - v0;
            Vector3f edge2 = v2 - v0;
            
            Vector2f duv1 = uv1 - uv0;
            Vector2f duv2 = uv2 - uv0;
            
            float det = (duv1.x * duv2.y) - (duv2.x * duv1.y);
            
            // Skip degenerate UV triangles
            if (abs(det) < 1e-8f)
                continue;
            
            float f = 1.0f / det;
            
            Vector3f tangent   = (edge1 * duv2.y - edge2 * duv1.y) * f;
            Vector3f bitangent = (edge2 * duv1.x - edge1 * duv2.x) * f;
            
            tSum[i0] += tangent;
            tSum[i1] += tangent;
            tSum[i2] += tangent;
            
            bSum[i0] += bitangent;
            bSum[i1] += bitangent;
            bSum[i2] += bitangent;
        }
        
        foreach(i, ref tangent; tangents)
        {
            Vector3f n = normals[i];
            Vector3f t = tSum[i];
            Vector3f b = bSum[i];

            // Gram-Schmidt orthogonalization
            t = (t - n * dot(n, t)).normalized;
            
            float handedness = dot(cross(n, t), b) < 0.0f ? -1.0f : 1.0f;
            
            tangent = Vector4f(t.x, t.y, t.z, handedness);
        }
        
        Delete(tSum);
        Delete(bSum);
        
        return true;
    }
    
    /**
     * Prepares vertex buffers for rendering the mesh.
     * Uploads vertex, normal, texcoord, and index data to the GPU.
     */
    void prepareBuffers()
    {
        if (canRender)
            return;
        
        if (!dataReady)
            return;
        
        if (vertices.length)
        {
            positionBuffer = gpu.createBuffer(SDL_GPU_BUFFERUSAGE_VERTEX, Vector3f.sizeof * vertices.length);
            gpu.uploadBuffer(vertices.ptr, Vector3f.sizeof * vertices.length, positionBuffer);
        }
        
        if (normals.length)
        {
            normalBuffer = gpu.createBuffer(SDL_GPU_BUFFERUSAGE_VERTEX, Vector3f.sizeof * normals.length);
            gpu.uploadBuffer(normals.ptr, Vector3f.sizeof * vertices.length, normalBuffer);
        }
        
        if (tangents.length)
        {
            tangentBuffer = gpu.createBuffer(SDL_GPU_BUFFERUSAGE_VERTEX, Vector4f.sizeof * tangents.length);
            gpu.uploadBuffer(tangents.ptr, Vector4f.sizeof * tangents.length, tangentBuffer);
        }
        
        if (texcoords.length)
        {
            texcoordBuffer = gpu.createBuffer(SDL_GPU_BUFFERUSAGE_VERTEX, Vector2f.sizeof * texcoords.length);
            gpu.uploadBuffer(texcoords.ptr, Vector2f.sizeof * vertices.length, texcoordBuffer);
        }
        
        if (indices.length)
        {
            indexBuffer = gpu.createBuffer(SDL_GPU_BUFFERUSAGE_INDEX, uint.sizeof * 3 * indices.length);
            gpu.uploadBuffer(indices.ptr, uint.sizeof * 3 * indices.length, indexBuffer);
            canRender = true;
        }
    }
    
    /**
     * Renders the mesh using the provided graphics pipeline state.
     *
     * Params:
     *   state = Pointer to the current graphics pipeline state.
     */
    void render(GraphicsState* state)
    {
        if (canRender)
        {
            auto pass = state.pass;
            if (pass)
            {
                pass.bindVertexBuffer(VertexAttribute.Position, positionBuffer);
                pass.bindVertexBuffer(VertexAttribute.Texcoord, texcoordBuffer);
                pass.bindVertexBuffer(VertexAttribute.Normal, normalBuffer);
                if (tangentBuffer && state.bindTangents)
                    pass.bindVertexBuffer(VertexAttribute.Tangent, tangentBuffer);
                pass.bindIndexBuffer(indexBuffer, SDL_GPU_INDEXELEMENTSIZE_32BIT);
                
                if (facegroups.length)
                {
                    foreach(ref fg; facegroups)
                    {
                        if (fg.visible)
                        {
                            if (fg.material)
                                state.material = fg.material;
                            else if (material)
                                state.material = material;
                            else
                                state.material = pass.renderer.defaultMaterial;
                            
                            if (pass.shouldRenderMaterial(state.material))
                            {
                                pass.shader.bindParameters(state);
                                pass.drawIndexedPrimitives(fg.numTriangles * 3, 1, fg.firstTriangle * 3, 0, 0);
                            }
                        }
                    }
                }
                else
                {
                    if (material)
                        state.material = material;
                    
                    if (pass.shouldRenderMaterial(state.material))
                    {
                        pass.shader.bindParameters(state);
                        pass.drawIndexedPrimitives(cast(uint)indices.length * 3, 1, 0, 0, 0);
                    }
                }
            }
        }
    }
}
