/*
Copyright (c) 2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module dagon.graphics.resampler;

import std.math;
import std.algorithm;

import dlib.core.memory;
import dlib.core.ownership;

import dagon.core.logger;
import dagon.core.crashhandler;
import dagon.core.sdl3;
import dagon.core.gpu;
import dagon.graphics.state;
import dagon.graphics.texture;
import dagon.graphics.shader;

struct ResampleShaderUniformBuffer
{
    float[4] srcSize;
    float[4] dstSize;
    uint[4] config;
}

///
enum LanczosPass: uint
{
    Horizontal = 0,
    Vertical = 1
}

///
class LanczosResampleShader: ComputeShader
{
    ResampleShaderUniformBuffer ubo;
    Texture inputTexture;
    Texture outputTexture;
    LanczosPass lanczosPass = LanczosPass.Horizontal;
    uint lanczosRadius = 3;
    
    ///
    this(GPU gpu, Owner owner)
    {
        super(gpu, owner);
        
        computeModule = New!ShaderModule(gpu, this);
        computeModule.create("ResampleLanczos.comp.glsl", "data/__internal/shaders/Compute/ResampleLanczos.comp.glsl",
            ShaderSourceType.File, ShaderLanguage.GLSL, PipelineStage.Compute);
        
        if (!computeModule.valid)
        {
            exitWithError("Failed to create LanczosResampleShader");
        }
        
        ubo.srcSize[0] = 0.0f;
        ubo.srcSize[1] = 0.0f;
        ubo.srcSize[2] = 0.0f;
        ubo.srcSize[3] = 0.0f;
        
        ubo.dstSize[0] = 0.0f;
        ubo.dstSize[1] = 0.0f;
        ubo.dstSize[2] = 0.0f;
        ubo.dstSize[3] = 0.0f;
        
        ubo.config[0] = lanczosPass;
        ubo.config[1] = lanczosRadius;
    }
    
    ///
    override void bindParameters(GraphicsState* state)
    {
        if (inputTexture)
        {
            ubo.srcSize[0] = inputTexture.buffer.size.width;
            ubo.srcSize[1] = inputTexture.buffer.size.height;
        }
        
        if (outputTexture)
        {
            ubo.dstSize[0] = outputTexture.buffer.size.width;
            ubo.dstSize[1] = outputTexture.buffer.size.height;
        }
        
        ubo.config[0] = lanczosPass;
        ubo.config[1] = lanczosRadius;
    }
}

///
class BilinearResampleShader: ComputeShader
{
    ResampleShaderUniformBuffer ubo;
    Texture inputTexture;
    Texture outputTexture;
    
    ///
    this(GPU gpu, Owner owner)
    {
        super(gpu, owner);
        
        computeModule = New!ShaderModule(gpu, this);
        computeModule.create("ResampleBilinear.comp.glsl", "data/__internal/shaders/Compute/ResampleBilinear.comp.glsl",
            ShaderSourceType.File, ShaderLanguage.GLSL, PipelineStage.Compute);
        
        if (!computeModule.valid)
        {
            exitWithError("Failed to create BilinearResampleShader");
        }
        
        ubo.srcSize[0] = 0.0f;
        ubo.srcSize[1] = 0.0f;
        ubo.srcSize[2] = 0.0f;
        ubo.srcSize[3] = 0.0f;
        
        ubo.dstSize[0] = 0.0f;
        ubo.dstSize[1] = 0.0f;
        ubo.dstSize[2] = 0.0f;
        ubo.dstSize[3] = 0.0f;
    }
    
    ///
    override void bindParameters(GraphicsState* state)
    {
        if (inputTexture)
        {
            ubo.srcSize[0] = inputTexture.buffer.size.width;
            ubo.srcSize[1] = inputTexture.buffer.size.height;
        }
        
        if (outputTexture)
        {
            ubo.dstSize[0] = outputTexture.buffer.size.width;
            ubo.dstSize[1] = outputTexture.buffer.size.height;
        }
    }
}

///
enum ResampleMode
{
    Bilinear = 0,
    Lanczos3 = 1
}

///
class Resampler: Owner
{
    GPU gpu;
    SDL_GPUComputePipeline* computePipelineBilinear;
    SDL_GPUComputePipeline* computePipelineLanczos;
    BilinearResampleShader resampleShaderBilinear;
    LanczosResampleShader resampleShaderLanczos;
    Texture inputTexture;
    Texture outputTexture;
    ResampleMode mode = ResampleMode.Lanczos3;
    
    ///
    this(GPU gpu, Owner owner)
    {
        super(owner);
        
        this.gpu = gpu;
        
        resampleShaderBilinear = New!BilinearResampleShader(gpu, this);
        resampleShaderLanczos = New!LanczosResampleShader(gpu, this);
        
        ShaderModule shaderModuleBilinear = resampleShaderBilinear.computeModule;
        ShaderModule shaderModuleLanczos = resampleShaderLanczos.computeModule;
        
        computePipelineBilinear = createPipeline(shaderModuleBilinear);
        computePipelineLanczos = createPipeline(shaderModuleLanczos);
    }
    
    ///
    ~this()
    {
        if (computePipelineBilinear)
        {
            SDL_ReleaseGPUComputePipeline(gpu.device, computePipelineBilinear);
            computePipelineBilinear = null;
        }
        
        if (computePipelineLanczos)
        {
            SDL_ReleaseGPUComputePipeline(gpu.device, computePipelineLanczos);
            computePipelineLanczos = null;
        }
    }
    
    SDL_GPUComputePipeline* createPipeline(ShaderModule shaderModule)
    {
        ubyte[] spirvBytes = shaderModule.spirvAsBytes;
        
        SDL_GPUComputePipelineCreateInfo pipelineCreateInfo = {
            code_size: spirvBytes.length,
            code: spirvBytes.ptr,
            entrypoint: "main",
            format: SDL_GPU_SHADERFORMAT_SPIRV,
            num_samplers: cast(uint)shaderModule.samplers.length,
            num_readonly_storage_textures: shaderModule.countStorageTextures(true),
            num_readonly_storage_buffers: shaderModule.countStorageBuffers(true),
            num_readwrite_storage_textures: shaderModule.countStorageTextures(false),
            num_readwrite_storage_buffers: shaderModule.countStorageBuffers(false),
            num_uniform_buffers: cast(uint)shaderModule.uniformBuffers.length,
            threadcount_x: shaderModule.localSizeX,
            threadcount_y: shaderModule.localSizeY,
            threadcount_z: shaderModule.localSizeZ,
            props: 0
        };
        
        return SDL_CreateGPUComputePipeline(gpu.device, &pipelineCreateInfo);
    }
    
    ///
    void submit()
    {
        if (outputTexture is null || inputTexture is null)
            return;
        
        Texture intermediateTexture;
        
        SDL_GPUCommandBuffer* commandBuffer = SDL_AcquireGPUCommandBuffer(gpu.device);
        
        if (mode == ResampleMode.Bilinear)
        {
            uint workGroupsX =
                (outputTexture.buffer.size.width  + resampleShaderBilinear.computeModule.localSizeX - 1) / resampleShaderBilinear.computeModule.localSizeX;
            uint workGroupsY =
                (outputTexture.buffer.size.height + resampleShaderBilinear.computeModule.localSizeY - 1) / resampleShaderBilinear.computeModule.localSizeY;
            
            auto storageTextureBinding = SDL_GPUStorageTextureReadWriteBinding(outputTexture.texture, 0, 0, false);
            SDL_GPUComputePass* pass = SDL_BeginGPUComputePass(
                commandBuffer,
                &storageTextureBinding, 1,
                null, 0);
            
            SDL_BindGPUComputePipeline(pass, computePipelineBilinear);
            
            // Bind input texture
            auto samplerBinding = SDL_GPUTextureSamplerBinding(inputTexture.texture, inputTexture.sampler);
            SDL_BindGPUComputeSamplers(pass, 0, &samplerBinding, 1);
            
            // Bind output texture
            SDL_BindGPUComputeStorageTextures(pass, 0, &outputTexture.texture, 1);
            
            // Bind UBO
            resampleShaderBilinear.inputTexture = inputTexture;
            resampleShaderBilinear.outputTexture = outputTexture;
            resampleShaderBilinear.bindParameters(null);
            SDL_PushGPUComputeUniformData(commandBuffer, 0, &resampleShaderBilinear.ubo, cast(uint)ResampleShaderUniformBuffer.sizeof);
            
            SDL_DispatchGPUCompute(pass, workGroupsX, workGroupsY, 1);
            
            SDL_EndGPUComputePass(pass);
        }
        else if (mode == ResampleMode.Lanczos3)
        {
            uint interWidth = outputTexture.buffer.size.width;
            uint interHeight = inputTexture.buffer.size.height;
            intermediateTexture = outputTexture.createSameFormat(interWidth, interHeight, 1, null);
            
            // Horizontal pass
            {
                uint workGroupsX =
                    (intermediateTexture.buffer.size.width  + resampleShaderLanczos.computeModule.localSizeX - 1) / resampleShaderLanczos.computeModule.localSizeX;
                uint workGroupsY =
                    (intermediateTexture.buffer.size.height + resampleShaderLanczos.computeModule.localSizeY - 1) / resampleShaderLanczos.computeModule.localSizeY;
                
                auto storageTextureBinding = SDL_GPUStorageTextureReadWriteBinding(intermediateTexture.texture, 0, 0, false);
                SDL_GPUComputePass* pass = SDL_BeginGPUComputePass(
                    commandBuffer,
                    &storageTextureBinding, 1,
                    null, 0);
                
                SDL_BindGPUComputePipeline(pass, computePipelineLanczos);
                
                // Bind input texture
                auto samplerBinding = SDL_GPUTextureSamplerBinding(inputTexture.texture, inputTexture.sampler);
                SDL_BindGPUComputeSamplers(pass, 0, &samplerBinding, 1);
                
                // Bind output texture
                SDL_BindGPUComputeStorageTextures(pass, 0, &intermediateTexture.texture, 1);
                
                // Bind UBO
                resampleShaderLanczos.inputTexture = inputTexture;
                resampleShaderLanczos.outputTexture = intermediateTexture;
                resampleShaderLanczos.lanczosPass = LanczosPass.Horizontal;
                resampleShaderLanczos.bindParameters(null);
                SDL_PushGPUComputeUniformData(commandBuffer, 0, &resampleShaderLanczos.ubo, cast(uint)ResampleShaderUniformBuffer.sizeof);
                
                SDL_DispatchGPUCompute(pass, workGroupsX, workGroupsY, 1);
                
                SDL_EndGPUComputePass(pass);
            }
            
            // Vertical pass
            {
                uint workGroupsX =
                    (outputTexture.buffer.size.width  + resampleShaderLanczos.computeModule.localSizeX - 1) / resampleShaderLanczos.computeModule.localSizeX;
                uint workGroupsY =
                    (outputTexture.buffer.size.height + resampleShaderLanczos.computeModule.localSizeY - 1) / resampleShaderLanczos.computeModule.localSizeY;
                
                auto storageTextureBinding = SDL_GPUStorageTextureReadWriteBinding(outputTexture.texture, 0, 0, false);
                SDL_GPUComputePass* pass = SDL_BeginGPUComputePass(
                    commandBuffer,
                    &storageTextureBinding, 1,
                    null, 0);
                
                SDL_BindGPUComputePipeline(pass, computePipelineLanczos);
                
                // Bind input texture
                auto samplerBinding = SDL_GPUTextureSamplerBinding(intermediateTexture.texture, intermediateTexture.sampler);
                SDL_BindGPUComputeSamplers(pass, 0, &samplerBinding, 1);
                
                // Bind output texture
                SDL_BindGPUComputeStorageTextures(pass, 0, &outputTexture.texture, 1);
                
                // Bind UBO
                resampleShaderLanczos.inputTexture = intermediateTexture;
                resampleShaderLanczos.outputTexture = outputTexture;
                resampleShaderLanczos.lanczosPass = LanczosPass.Vertical;
                resampleShaderLanczos.bindParameters(null);
                SDL_PushGPUComputeUniformData(commandBuffer, 0, &resampleShaderLanczos.ubo, cast(uint)ResampleShaderUniformBuffer.sizeof);
                
                SDL_DispatchGPUCompute(pass, workGroupsX, workGroupsY, 1);
                
                SDL_EndGPUComputePass(pass);
            }
        }
        
        if (outputTexture.options.generateMipmaps)
        {
            outputTexture.mipLevels = 1 + cast(uint)floor(log2(cast(double)max(outputTexture.buffer.size.width, outputTexture.buffer.size.height)));
            SDL_GenerateMipmapsForGPUTexture(commandBuffer, outputTexture.texture);
        }
        
        SDL_GPUFence* fence = SDL_SubmitGPUCommandBufferAndAcquireFence(commandBuffer);
        
        if (fence)
        {
            SDL_WaitForGPUFences(gpu.device, true, &fence, 1);
            SDL_ReleaseGPUFence(gpu.device, fence);
        }
        
        if (intermediateTexture)
            Delete(intermediateTexture);
    }
}
