/*
Copyright (c) 2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

/**
 * Scene class.
 *
 * Description:
 * The `dagon.resource.scene` module defines the `Scene` class, which manages
 * entities and environment for a 3D scene.
 *
 * Copyright: Timur Gafarov 2019-2026
 * License: $(LINK2 https://boost.org/LICENSE_1_0.txt, Boost License 1.0).
 * Authors: Timur Gafarov
 */
module dagon.graphics.scene;

import dlib.core.memory;
import dlib.core.ownership;
import dlib.container.array;
import dlib.image.color;

import dagon.core.logger;
import dagon.core.gpu;
import dagon.graphics.entity;
import dagon.graphics.camera;
import dagon.graphics.light;
import dagon.graphics.texture;

import gscript;

/**
 * Manages entities and environment for a 3D scene.
 *
 * Description:
 * The `Scene` class provides methods for creating entities,
 * cameras, and lights.
 */
class Scene: Owner, GsObject
{
    GPU gpu;
    Array!Entity entities;
    Camera activeCamera;
    Light sun;
    Color4f ambientColor = Color4f(0.5f, 0.5f, 0.5f, 1.0f);
    Texture specularTexture;
    Texture irradianceTexture;
    Texture brdfLUT;
    bool brdfLUTEnabled = true;
    float ambientEnergy = 1.0f;
    
    Color4f fogColor = Color4f(1.0f, 1.0f, 1.0f, 1.0f);
    float fogEnergy = 1.0f;
    float fogStart = 0.0f;
    float fogEnd = 100.0f;
    float fogDensity = 1.0f;
    float groundFogDensity = 0.0f;
    
    /**
     * Constructs a new scene.
     *
     * Params:
     *   gpu = GPU object.
     *   owner = Owner object.
     */
    this(GPU gpu, Owner owner)
    {
        super(owner);
        this.gpu = gpu;
        sun = New!Light(gpu, LightType.Sun, this);
        sun.shadowEnabled = true;
        entities.append(sun);
    }
    
    ~this()
    {
        entities.free();
    }
    
    /// Creates and adds a new entity, optionally with a parent.
    Entity addEntity(Entity parent = null)
    {
        Entity e = New!Entity(this);
        entities.append(e);
        if (parent)
            parent.addChild(e);
        return e;
    }
    
    /// Adds an existing entity to the world.
    Entity useEntity(Entity e, bool useChildren = false)
    {
        entities.append(e);
        if (useChildren)
        {
            foreach(child; e.children)
                useEntity(child, useChildren);
        }
        return e;
    }
    
    /// Removes an entity from the world without deleting it.
    void removeEntity(Entity entity, bool removeChildren = false)
    {
        int index = -1;
        foreach(i, e; entities.data)
        {
            if (e is entity)
            {
                index = cast(int)i;
                break;
            }
        }
        
        if (index >= 0)
            entities.removeKey(cast(size_t)index);
        
        if (removeChildren)
        {
            foreach(child; entity.children)
                removeEntity(child, removeChildren);
        }
    }
    
    /// Creates and adds a new camera, optionally with a parent.
    Camera addCamera(Entity parent = null)
    {
        Camera c = New!Camera(this);
        entities.append(c);
        if (parent)
            parent.addChild(c);
        return c;
    }
    
    /// Creates and adds a new light of the given type, optionally with a parent.
    Light addLight(LightType type, Entity parent = null)
    {
        Light light = New!Light(gpu, type, this);
        entities.append(light);
        if (parent)
            parent.addChild(light);
        return light;
    }
    
    ///
    GsDynamic gsEntityByName(GsDynamic[] args)
    {
        logInfo(args);
        if (args.length < 2)
            return GsDynamic();
        string name = args[1].asString;
        GsDynamic result = GsDynamic();
        foreach(entity; entities)
        {
            if (entity.name == name)
            {
                result = GsDynamic(entity);
                break;
            }
        }
        return result;
    }
    
    ///
    GsDynamic get(string key)
    {
        switch(key)
        {
            case "entities":
                return GsDynamic(entities.data);
            case "entityByName":
                return GsDynamic(&gsEntityByName);
            default:
                return GsDynamic();
        }
    }
    
    ///
    void set(string key, GsDynamic value)
    {
        // TODO
    }
    
    ///
    bool contains(string key)
    {
        switch(key)
        {
            case "entities": return true;
            default: return false;
        }
    }
    
    ///
    void setPrototype(GsObject obj)
    {
        // No-op
    }
}
