/*
Copyright (c) 2017-2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

/**
 * Basic geometric shape classes.
 *
 * Description:
 * The `dagon.graphics.shapes` module defines mesh and drawable classes
 * for common shapes.
 *
 * Copyright: Timur Gafarov 2017-2026
 * License: $(LINK2 https://boost.org/LICENSE_1_0.txt, Boost License 1.0).
 * Authors: Timur Gafarov
 */
module dagon.graphics.shapes;

import std.math;

import dlib.core.memory;
import dlib.core.ownership;
import dlib.math.vector;
import dlib.container.array;

import dagon.core.sdl3;
import dagon.core.gpu;
import dagon.graphics.state;
import dagon.graphics.drawable;
import dagon.graphics.mesh;

private enum HALF_PI = PI * 0.5f;

/**
 * A mesh representing a grid plane in the XZ plane.
 */
class ShapePlane: Mesh
{
    /**
     * Constructs a `ShapePlane`.
     *
     * Params:
     *   sx       = Size along the X axis.
     *   sz       = Size along the Z axis.
     *   numTiles = Number of tiles along each axis.
     *   owner    = Owner object.
     */
    this(float sx, float sz, uint numTiles, GPU gpu, Owner owner)
    {
        super(gpu, owner);

        float px = -sx * 0.5f;
        float py = -sz * 0.5f;

        float tileWidth = sx / numTiles;
        float tileHeight = sz / numTiles;

        Vector3f start = Vector3f(px, 0.0f, py);

        uint gridSize = numTiles + 1;

        vertices = New!(Vector3f[])(gridSize * gridSize);
        normals = New!(Vector3f[])(gridSize * gridSize);
        texcoords = New!(Vector2f[])(gridSize * gridSize);

        for (uint i = 0, y = 0; y < gridSize; y++)
        for (uint x = 0; x < gridSize; x++, i++)
        {
            vertices[i] = start + Vector3f(x * tileWidth, 0, y * tileHeight);
            normals[i] = Vector3f(0, 1, 0);
            texcoords[i] = Vector2f(x, y);
        }

        indices = New!(uint[3][])(gridSize * gridSize * 2);

        uint index = 0;
        for (uint y = 0; y < gridSize - 1; y++)
        for (uint x = 0; x < gridSize - 1; x++)
        {
            uint offset = y * gridSize + x;
            indices[index][2] = (offset + 0);
            indices[index][1] = (offset + 1);
            indices[index][0] = (offset + gridSize);

            indices[index+1][2] = (offset + 1);
            indices[index+1][1] = (offset + gridSize + 1);
            indices[index+1][0] = (offset + gridSize);

            index += 2;
        }
        
        dataReady = true;
        
        prepareBuffers();
    }

    ~this()
    {
        if (vertices)
            Delete(vertices);
        if (normals)
            Delete(normals);
        if (texcoords)
            Delete(texcoords);
        if (indices)
            Delete(indices);
    }
}

/**
 * A mesh representing a box (cuboid) with configurable extents.
 */
class ShapeBox: Mesh
{
    Vector3f halfExtents;

    /**
     * Constructs a `ShapeBox` using extents as a vector.
     *
     * Params:
     *   halfExtents = Half-size along each axis.
     *   owner       = Owner object.
     */
    this(Vector3f halfExtents, GPU gpu, Owner owner)
    {
        super(gpu, owner);
        this.halfExtents = halfExtents;
        
        vertices = New!(Vector3f[])(24);
        normals = New!(Vector3f[])(24);
        texcoords = New!(Vector2f[])(24);
        indices = New!(uint[3][])(12);

        Vector3f pmax = +halfExtents;
        Vector3f pmin = -halfExtents;

        texcoords[0] = Vector2f(1, 0); normals[0] = Vector3f(0,0,1); vertices[0] = Vector3f(pmax.x, pmax.y, pmax.z);
        texcoords[1] = Vector2f(0, 0); normals[1] = Vector3f(0,0,1); vertices[1] = Vector3f(pmin.x, pmax.y, pmax.z);
        texcoords[2] = Vector2f(0, 1); normals[2] = Vector3f(0,0,1); vertices[2] = Vector3f(pmin.x, pmin.y, pmax.z);
        texcoords[3] = Vector2f(1, 1); normals[3] = Vector3f(0,0,1); vertices[3] = Vector3f(pmax.x, pmin.y, pmax.z);
        indices[0][0] = 0; indices[0][1] = 1; indices[0][2] = 2;
        indices[1][0] = 2; indices[1][1] = 3; indices[1][2] = 0;

        texcoords[4] = Vector2f(0, 0); normals[4] = Vector3f(1,0,0); vertices[4] = Vector3f(pmax.x, pmax.y, pmax.z);
        texcoords[5] = Vector2f(0, 1); normals[5] = Vector3f(1,0,0); vertices[5] = Vector3f(pmax.x, pmin.y, pmax.z);
        texcoords[6] = Vector2f(1, 1); normals[6] = Vector3f(1,0,0); vertices[6] = Vector3f(pmax.x, pmin.y, pmin.z);
        texcoords[7] = Vector2f(1, 0); normals[7] = Vector3f(1,0,0); vertices[7] = Vector3f(pmax.x, pmax.y, pmin.z);
        indices[2][0] = 4; indices[2][1] = 5; indices[2][2] = 6;
        indices[3][0] = 6; indices[3][1] = 7; indices[3][2] = 4;

        texcoords[8] = Vector2f(1, 1); normals[8] = Vector3f(0,1,0); vertices[8] = Vector3f(pmax.x, pmax.y, pmax.z);
        texcoords[9] = Vector2f(1, 0); normals[9] = Vector3f(0,1,0); vertices[9] = Vector3f(pmax.x, pmax.y, pmin.z);
        texcoords[10] = Vector2f(0, 0); normals[10] = Vector3f(0,1,0); vertices[10] = Vector3f(pmin.x, pmax.y, pmin.z);
        texcoords[11] = Vector2f(0, 1); normals[11] = Vector3f(0,1,0); vertices[11] = Vector3f(pmin.x, pmax.y, pmax.z);
        indices[4][0] = 8; indices[4][1] = 9; indices[4][2] = 10;
        indices[5][0] = 10; indices[5][1] = 11; indices[5][2] = 8;

        texcoords[12] = Vector2f(1, 0); normals[12] = Vector3f(-1,0,0); vertices[12] = Vector3f(pmin.x, pmax.y, pmax.z);
        texcoords[13] = Vector2f(0, 0); normals[13] = Vector3f(-1,0,0); vertices[13] = Vector3f(pmin.x, pmax.y, pmin.z);
        texcoords[14] = Vector2f(0, 1); normals[14] = Vector3f(-1,0,0); vertices[14] = Vector3f(pmin.x, pmin.y, pmin.z);
        texcoords[15] = Vector2f(1, 1); normals[15] = Vector3f(-1,0,0); vertices[15] = Vector3f(pmin.x, pmin.y, pmax.z);
        indices[6][0] = 12; indices[6][1] = 13; indices[6][2] = 14;
        indices[7][0] = 14; indices[7][1] = 15; indices[7][2] = 12;

        texcoords[16] = Vector2f(0, 1); normals[16] = Vector3f(0,-1,0); vertices[16] = Vector3f(pmin.x, pmin.y, pmin.z);
        texcoords[17] = Vector2f(1, 1); normals[17] = Vector3f(0,-1,0); vertices[17] = Vector3f(pmax.x, pmin.y, pmin.z);
        texcoords[18] = Vector2f(1, 0); normals[18] = Vector3f(0,-1,0); vertices[18] = Vector3f(pmax.x, pmin.y, pmax.z);
        texcoords[19] = Vector2f(0, 0); normals[19] = Vector3f(0,-1,0); vertices[19] = Vector3f(pmin.x, pmin.y, pmax.z);
        indices[8][0] = 16; indices[8][1] = 17; indices[8][2] = 18;
        indices[9][0] = 18; indices[9][1] = 19; indices[9][2] = 16;

        texcoords[20] = Vector2f(0, 1); normals[20] = Vector3f(0,0,-1); vertices[20] = Vector3f(pmax.x, pmin.y, pmin.z);
        texcoords[21] = Vector2f(1, 1); normals[21] = Vector3f(0,0,-1); vertices[21] = Vector3f(pmin.x, pmin.y, pmin.z);
        texcoords[22] = Vector2f(1, 0); normals[22] = Vector3f(0,0,-1); vertices[22] = Vector3f(pmin.x, pmax.y, pmin.z);
        texcoords[23] = Vector2f(0, 0); normals[23] = Vector3f(0,0,-1); vertices[23] = Vector3f(pmax.x, pmax.y, pmin.z);
        indices[10][0] = 20; indices[10][1] = 21; indices[10][2] = 22;
        indices[11][0] = 22; indices[11][1] = 23; indices[11][2] = 20;
        
        dataReady = true;
        
        prepareBuffers();
    }

    /**
     * Constructs a `ShapeBox` using half-extents as separate components.
     *
     * Params:
     *   hw    = Half-width.
     *   hh    = Half-height.
     *   hd    = Half-depth.
     *   owner = Owner object.
     */
    this(float hw, float hh, float hd, GPU gpu, Owner owner)
    {
        this(Vector3f(hw, hh, hd), gpu, owner);
    }

    ~this()
    {
        if (vertices)
            Delete(vertices);
        if (normals)
            Delete(normals);
        if (texcoords)
            Delete(texcoords);
        if (indices)
            Delete(indices);
    }
}

/**
 * A mesh representing a UV sphere.
 */
class ShapeSphere: Mesh
{
    float radius;

    /**
     * Constructs a `ShapeSphere`.
     *
     * Params:
     *   radius     = Sphere radius.
     *   slices     = Number of longitudinal segments.
     *   stacks     = Number of latitudinal segments.
     *   invNormals = If `true`, normals are inverted (inside-out sphere).
     *   owner      = Owner object.
     */
    this(float radius, uint slices, uint stacks, bool invNormals, GPU gpu, Owner owner)
    {
        super(gpu, owner);
        this.radius = radius;
        
        Array!Vector3f daVertices;
        Array!Vector3f daNormals;
        Array!Vector2f daTexcoords;
        Array!(uint[3]) daIndices;

        uint[3] tri;
        uint i = 0;

        float cuts = stacks;
        float invCuts = 1.0f / cuts;

        float invSlices = 1.0f / slices;
        float angleStep = (2.0f * PI) * invSlices;

        for(int h = 0; h < stacks; h++)
        {
            float h1Norm = cast(float)h * invCuts * 2.0f - 1.0f;
            float h2Norm = cast(float)(h+1) * invCuts * 2.0f - 1.0f;
            float y1 = sin(HALF_PI * h1Norm);
            float y2 = sin(HALF_PI * h2Norm);

            float circleRadius1 = cos(HALF_PI * y1);
            float circleRadius2 = cos(HALF_PI * y2);

            for(int a = 0; a < slices; a++)
            {
                float x1a = sin(angleStep * a) * circleRadius1;
                float z1a = cos(angleStep * a) * circleRadius1;
                float x2a = sin(angleStep * (a + 1)) * circleRadius1;
                float z2a = cos(angleStep * (a + 1)) * circleRadius1;

                float x1b = sin(angleStep * a) * circleRadius2;
                float z1b = cos(angleStep * a) * circleRadius2;
                float x2b = sin(angleStep * (a + 1)) * circleRadius2;
                float z2b = cos(angleStep * (a + 1)) * circleRadius2;

                Vector3f v1 = Vector3f(x1a, y1, z1a);
                Vector3f v2 = Vector3f(x2a, y1, z2a);
                Vector3f v3 = Vector3f(x1b, y2, z1b);
                Vector3f v4 = Vector3f(x2b, y2, z2b);

                Vector3f n1 = v1.normalized;
                Vector3f n2 = v2.normalized;
                Vector3f n3 = v3.normalized;
                Vector3f n4 = v4.normalized;

                daVertices.append(n1 * radius);
                daVertices.append(n2 * radius);
                daVertices.append(n3 * radius);

                daVertices.append(n3 * radius);
                daVertices.append(n2 * radius);
                daVertices.append(n4 * radius);

                float sign = invNormals? -1.0f : 1.0f;

                daNormals.append(n1 * sign);
                daNormals.append(n2 * sign);
                daNormals.append(n3 * sign);

                daNormals.append(n3 * sign);
                daNormals.append(n2 * sign);
                daNormals.append(n4 * sign);

                auto uv1 = Vector2f(0, 1);
                auto uv2 = Vector2f(1, 1);
                auto uv3 = Vector2f(0, 0);
                auto uv4 = Vector2f(1, 0);

                daTexcoords.append(uv1);
                daTexcoords.append(uv2);
                daTexcoords.append(uv3);

                daTexcoords.append(uv3);
                daTexcoords.append(uv2);
                daTexcoords.append(uv4);

                if (invNormals)
                {
                    tri[0] = i+2;
                    tri[1] = i+1;
                    tri[2] = i;
                    daIndices.append(tri);

                    tri[0] = i+5;
                    tri[1] = i+4;
                    tri[2] = i+3;
                    daIndices.append(tri);
                }
                else
                {
                    tri[0] = i;
                    tri[1] = i+1;
                    tri[2] = i+2;
                    daIndices.append(tri);

                    tri[0] = i+3;
                    tri[1] = i+4;
                    tri[2] = i+5;
                    daIndices.append(tri);
                }

                i += 6;
            }
        }

        vertices = New!(Vector3f[])(daVertices.length);
        vertices[] = daVertices.data[];

        normals = New!(Vector3f[])(daNormals.length);
        normals[] = daNormals.data[];

        texcoords = New!(Vector2f[])(daTexcoords.length);
        texcoords[] = daTexcoords.data[];

        indices = New!(uint[3][])(daIndices.length);
        indices[] = daIndices.data[];

        daVertices.free();
        daNormals.free();
        daTexcoords.free();
        daIndices.free();
        
        dataReady = true;
        
        prepareBuffers();
    }

    /**
     * Constructs a `ShapeSphere` with the default number of segments.
     *
     * Params:
     *   radius     = Sphere radius.
     *   owner      = Owner object.
     */
    this(float radius, GPU gpu, Owner owner)
    {
        this(radius, 16, 16, false, gpu, owner);
    }

    ~this()
    {
        if (vertices)
            Delete(vertices);
        if (normals)
            Delete(normals);
        if (texcoords)
            Delete(texcoords);
        if (indices)
            Delete(indices);
    }
}

/**
 * 2D rectangle. Vertices and texture coordinates are defined
 * in normalized [0,1] space. Useful for screen-space rendering,
 * post-processing, and UI.
 */
class ShapeNormQuad: Owner, Drawable
{
    GPU gpu;
    SDL_GPUBuffer* vertexBuffer;
    SDL_GPUBuffer* texcoordBuffer;
    SDL_GPUBuffer* indexBuffer;
    Vector2f[4] vertices;
    Vector2f[4] texcoords;
    ushort[3][2] indices;

    /**
     * Constructs a `ShapeQuad`.
     *
     * Params:
     *   owner = Owner object.
     */
    this(GPU gpu, Owner owner)
    {
        super(owner);
        this.gpu = gpu;

        vertices[0] = Vector2f(0, 1);
        vertices[1] = Vector2f(0, 0);
        vertices[2] = Vector2f(1, 0);
        vertices[3] = Vector2f(1, 1);

        texcoords[0] = Vector2f(0, 1);
        texcoords[1] = Vector2f(0, 0);
        texcoords[2] = Vector2f(1, 0);
        texcoords[3] = Vector2f(1, 1);

        indices[0][0] = 0;
        indices[0][1] = 1;
        indices[0][2] = 2;

        indices[1][0] = 0;
        indices[1][1] = 2;
        indices[1][2] = 3;

        vertexBuffer = gpu.createBuffer(SDL_GPU_BUFFERUSAGE_VERTEX, Vector3f.sizeof * vertices.length);
        texcoordBuffer = gpu.createBuffer(SDL_GPU_BUFFERUSAGE_VERTEX, Vector2f.sizeof * vertices.length);
        indexBuffer = gpu.createBuffer(SDL_GPU_BUFFERUSAGE_INDEX, ushort.sizeof * 3 * indices.length);

        gpu.uploadBuffer(vertices.ptr, Vector3f.sizeof * vertices.length, vertexBuffer);
        gpu.uploadBuffer(texcoords.ptr, Vector2f.sizeof * vertices.length, texcoordBuffer);
        gpu.uploadBuffer(indices.ptr, ushort.sizeof * 3 * indices.length, indexBuffer);
    }
    
    ~this()
    {
        if (vertexBuffer)
        {
            gpu.releaseBuffer(vertexBuffer);
        }
        if (texcoordBuffer)
        {
            gpu.releaseBuffer(texcoordBuffer);
        }
        if (indexBuffer)
        {
            gpu.releaseBuffer(indexBuffer);
        }
    }
    
    void render(GraphicsState* state)
    {
        auto pass = state.pass;
        pass.bindVertexBuffer(VertexAttribute.Position, vertexBuffer);
        pass.bindVertexBuffer(VertexAttribute.Texcoord, texcoordBuffer);
        pass.bindIndexBuffer(indexBuffer, SDL_GPU_INDEXELEMENTSIZE_16BIT);
        pass.drawIndexedPrimitives(cast(uint)indices.length * 3, 1, 0, 0, 0);
    }
}
