/*
Copyright (c) 2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module dagon.graphics.texturebuffer;

import dagon.core.sdl3;
//import dagon.core.vkformat;
//import dagon.core.dxgiformat;
import dagon.core.logger;
public import dagon.graphics.conv;

/**
 * Specifies the dimension of a texture.
 */
enum TextureDimension
{
    /// Unknown
    Undefined,

    /// 1-dimensional texture
    D1,

    /// 2-dimensional texture
    D2,

    /// 3-dimensional texture
    D3
}

/**
 * Represents the size of a texture in pixels.
 */
struct TextureSize
{
    /// Width
    uint width;

    /// Height
    uint height;

    /// Depth
    uint depth;
}

/**
 * The faces of a cube map texture.
 */
enum CubeFace: uint
{
    /// Positive-X face (right)
    PositiveX = SDL_GPU_CUBEMAPFACE_POSITIVEX,

    /// Negative-X face (left)
    NegativeX = SDL_GPU_CUBEMAPFACE_NEGATIVEX,

    /// Positive-Y face (top)
    PositiveY = SDL_GPU_CUBEMAPFACE_POSITIVEY,

    /// Negative-Y face (bottom)
    NegativeY = SDL_GPU_CUBEMAPFACE_NEGATIVEY,

    /// Positive-Z face (front)
    PositiveZ = SDL_GPU_CUBEMAPFACE_POSITIVEZ,

    /// Negative-Z face (back)
    NegativeZ = SDL_GPU_CUBEMAPFACE_NEGATIVEZ
}

/**
 * Bitmask for cube map faces.
 */
enum CubeFaceBit
{
    None = 0,
    PositiveX = 1,
    NegativeX = 2,
    PositiveY = 4,
    NegativeY = 8,
    PositiveZ = 16,
    NegativeZ = 32,
    All = 0xffffffff
}

/**
 * Returns a corresponding `CubeFaceBit` for a given `CubeFace`
 */
CubeFaceBit cubeFaceBit(CubeFace face)
{
    CubeFaceBit cfb = CubeFaceBit.None;
    switch(face)
    {
        case CubeFace.PositiveX: cfb = CubeFaceBit.PositiveX; break;
        case CubeFace.NegativeX: cfb = CubeFaceBit.NegativeX; break;
        case CubeFace.PositiveY: cfb = CubeFaceBit.PositiveY; break;
        case CubeFace.NegativeY: cfb = CubeFaceBit.NegativeY; break;
        case CubeFace.PositiveZ: cfb = CubeFaceBit.PositiveZ; break;
        case CubeFace.NegativeZ: cfb = CubeFaceBit.NegativeZ; break;
        default: break;
    }
    return cfb;
}

/**
 * Describes the format and layout of a texture.
 */
struct TextureFormat
{
    /// SDL GPU texture type.
    SDL_GPUTextureType type;
    
    /// SDL GPU texture format.
    SDL_GPUTextureFormat format;
    
    /**
     * For compressed formats, this should be the size of a 4x4 pixel block in bytes.
     * For uncompressed formats, this should be zero.
     */
    uint blockSize;

    /// Bitwise combination of `CubeFaceBit` members.
    uint cubeFaces;
    
    /// The number of channels.
    uint numChannels;
    
    /// The size of a pixel in bytes.
    uint pixelSize;
    
    /// Returns `true` if the format is a cube map.
    bool isCubemap() const @property
    {
        return cubeFaces != CubeFaceBit.None;
    }
    
    /// 
    bool isCompressed() const @property
    {
        return blockSize > 0;
    }
    
    /// Returns the texture dimension.
    TextureDimension dimension() const @property
    {
        if (type == SDL_GPU_TEXTURETYPE_2D)
            return TextureDimension.D2;
        else if (type == SDL_GPU_TEXTURETYPE_3D)
            return TextureDimension.D3;
        else
            return TextureDimension.Undefined;
    }
}

/**
 * Intermediate texture data storage.
 * Used to create textures loaded from container formats,
 * such as DDS and KTX, from custom formats, or directly
 * from memory.
 */
struct TextureBuffer
{
    /// Format of a texture data.
    TextureFormat format;

    /// Size of a texture data.
    TextureSize size;

    /// Number of mip levels.
    uint mipLevels;

    /// Raw texture data (can be compressed).
    ubyte[] data;
}

///
string textureTypeStr(SDL_GPUTextureType type)
{
    switch(type)
    {
        case SDL_GPU_TEXTURETYPE_2D: return "SDL_GPU_TEXTURETYPE_2D";
        case SDL_GPU_TEXTURETYPE_2D_ARRAY: return "SDL_GPU_TEXTURETYPE_2D_ARRAY";
        case SDL_GPU_TEXTURETYPE_3D: return "SDL_GPU_TEXTURETYPE_3D";
        case SDL_GPU_TEXTURETYPE_CUBE: return "SDL_GPU_TEXTURETYPE_CUBE";
        case SDL_GPU_TEXTURETYPE_CUBE_ARRAY: return "SDL_GPU_TEXTURETYPE_CUBE_ARRAY";
        default: return "Unknown";
    }
}

///
string textureFormatStr(SDL_GPUTextureFormat format)
{
    switch(format)
    {
        case SDL_GPU_TEXTUREFORMAT_INVALID: return "SDL_GPU_TEXTUREFORMAT_INVALID";

        // Unsigned Normalized Float Color Formats
        case SDL_GPU_TEXTUREFORMAT_A8_UNORM: return "SDL_GPU_TEXTUREFORMAT_A8_UNORM";
        case SDL_GPU_TEXTUREFORMAT_R8_UNORM: return "SDL_GPU_TEXTUREFORMAT_R8_UNORM";
        case SDL_GPU_TEXTUREFORMAT_R8G8_UNORM: return "SDL_GPU_TEXTUREFORMAT_R8G8_UNORM";
        case SDL_GPU_TEXTUREFORMAT_R8G8B8A8_UNORM: return "SDL_GPU_TEXTUREFORMAT_R8G8B8A8_UNORM";
        case SDL_GPU_TEXTUREFORMAT_R16_UNORM: return "SDL_GPU_TEXTUREFORMAT_R16_UNORM";
        case SDL_GPU_TEXTUREFORMAT_R16G16_UNORM: return "SDL_GPU_TEXTUREFORMAT_R16G16_UNORM";
        case SDL_GPU_TEXTUREFORMAT_R16G16B16A16_UNORM: return "SDL_GPU_TEXTUREFORMAT_R16G16B16A16_UNORM";
        case SDL_GPU_TEXTUREFORMAT_R10G10B10A2_UNORM: return "SDL_GPU_TEXTUREFORMAT_R10G10B10A2_UNORM";
        case SDL_GPU_TEXTUREFORMAT_B5G6R5_UNORM: return "SDL_GPU_TEXTUREFORMAT_B5G6R5_UNORM";
        case SDL_GPU_TEXTUREFORMAT_B5G5R5A1_UNORM: return "SDL_GPU_TEXTUREFORMAT_B5G5R5A1_UNORM";
        case SDL_GPU_TEXTUREFORMAT_B4G4R4A4_UNORM: return "SDL_GPU_TEXTUREFORMAT_B4G4R4A4_UNORM";
        case SDL_GPU_TEXTUREFORMAT_B8G8R8A8_UNORM: return "SDL_GPU_TEXTUREFORMAT_B8G8R8A8_UNORM";

        // Compressed Unsigned Normalized Float Color Formats
        case SDL_GPU_TEXTUREFORMAT_BC1_RGBA_UNORM: return "SDL_GPU_TEXTUREFORMAT_BC1_RGBA_UNORM";
        case SDL_GPU_TEXTUREFORMAT_BC2_RGBA_UNORM: return "SDL_GPU_TEXTUREFORMAT_BC2_RGBA_UNORM";
        case SDL_GPU_TEXTUREFORMAT_BC3_RGBA_UNORM: return "SDL_GPU_TEXTUREFORMAT_BC3_RGBA_UNORM";
        case SDL_GPU_TEXTUREFORMAT_BC4_R_UNORM: return "SDL_GPU_TEXTUREFORMAT_BC4_R_UNORM";
        case SDL_GPU_TEXTUREFORMAT_BC5_RG_UNORM: return "SDL_GPU_TEXTUREFORMAT_BC5_RG_UNORM";
        case SDL_GPU_TEXTUREFORMAT_BC7_RGBA_UNORM: return "SDL_GPU_TEXTUREFORMAT_BC7_RGBA_UNORM";

        // Compressed Signed Float Color Formats
        case SDL_GPU_TEXTUREFORMAT_BC6H_RGB_FLOAT: return "SDL_GPU_TEXTUREFORMAT_BC6H_RGB_FLOAT";

        // Compressed Unsigned Float Color Formats
        case SDL_GPU_TEXTUREFORMAT_BC6H_RGB_UFLOAT: return "SDL_GPU_TEXTUREFORMAT_BC6H_RGB_UFLOAT";

        // Signed Normalized Float Color Formats
        case SDL_GPU_TEXTUREFORMAT_R8_SNORM: return "SDL_GPU_TEXTUREFORMAT_R8_SNORM";
        case SDL_GPU_TEXTUREFORMAT_R8G8_SNORM: return "SDL_GPU_TEXTUREFORMAT_R8G8_SNORM";
        case SDL_GPU_TEXTUREFORMAT_R8G8B8A8_SNORM: return "SDL_GPU_TEXTUREFORMAT_R8G8B8A8_SNORM";
        case SDL_GPU_TEXTUREFORMAT_R16_SNORM: return "SDL_GPU_TEXTUREFORMAT_R16_SNORM";
        case SDL_GPU_TEXTUREFORMAT_R16G16_SNORM: return "SDL_GPU_TEXTUREFORMAT_R16G16_SNORM";
        case SDL_GPU_TEXTUREFORMAT_R16G16B16A16_SNORM: return "SDL_GPU_TEXTUREFORMAT_R16G16B16A16_SNORM";

        // Signed Float Color Formats
        case SDL_GPU_TEXTUREFORMAT_R16_FLOAT: return "SDL_GPU_TEXTUREFORMAT_R16_FLOAT";
        case SDL_GPU_TEXTUREFORMAT_R16G16_FLOAT: return "SDL_GPU_TEXTUREFORMAT_R16G16_FLOAT";
        case SDL_GPU_TEXTUREFORMAT_R16G16B16A16_FLOAT: return "SDL_GPU_TEXTUREFORMAT_R16G16B16A16_FLOAT";
        case SDL_GPU_TEXTUREFORMAT_R32_FLOAT: return "SDL_GPU_TEXTUREFORMAT_R32_FLOAT";
        case SDL_GPU_TEXTUREFORMAT_R32G32_FLOAT: return "SDL_GPU_TEXTUREFORMAT_R32G32_FLOAT";
        case SDL_GPU_TEXTUREFORMAT_R32G32B32A32_FLOAT: return "SDL_GPU_TEXTUREFORMAT_R32G32B32A32_FLOAT";

        // Unsigned Float Color Formats
        case SDL_GPU_TEXTUREFORMAT_R11G11B10_UFLOAT: return "SDL_GPU_TEXTUREFORMAT_R11G11B10_UFLOAT";

        // Unsigned Integer Color Formats
        case SDL_GPU_TEXTUREFORMAT_R8_UINT: return "SDL_GPU_TEXTUREFORMAT_R8_UINT";
        case SDL_GPU_TEXTUREFORMAT_R8G8_UINT: return "SDL_GPU_TEXTUREFORMAT_R8G8_UINT";
        case SDL_GPU_TEXTUREFORMAT_R8G8B8A8_UINT: return "SDL_GPU_TEXTUREFORMAT_R8G8B8A8_UINT";
        case SDL_GPU_TEXTUREFORMAT_R16_UINT: return "SDL_GPU_TEXTUREFORMAT_R16_UINT";
        case SDL_GPU_TEXTUREFORMAT_R16G16_UINT: return "SDL_GPU_TEXTUREFORMAT_R16G16_UINT";
        case SDL_GPU_TEXTUREFORMAT_R16G16B16A16_UINT: return "SDL_GPU_TEXTUREFORMAT_R16G16B16A16_UINT";
        case SDL_GPU_TEXTUREFORMAT_R32_UINT: return "SDL_GPU_TEXTUREFORMAT_R32_UINT";
        case SDL_GPU_TEXTUREFORMAT_R32G32_UINT: return "SDL_GPU_TEXTUREFORMAT_R32G32_UINT";
        case SDL_GPU_TEXTUREFORMAT_R32G32B32A32_UINT: return "SDL_GPU_TEXTUREFORMAT_R32G32B32A32_UINT";

        // Signed Integer Color Formats
        case SDL_GPU_TEXTUREFORMAT_R8_INT: return "SDL_GPU_TEXTUREFORMAT_R8_INT";
        case SDL_GPU_TEXTUREFORMAT_R8G8_INT: return "SDL_GPU_TEXTUREFORMAT_R8G8_INT";
        case SDL_GPU_TEXTUREFORMAT_R8G8B8A8_INT: return "SDL_GPU_TEXTUREFORMAT_R8G8B8A8_INT";
        case SDL_GPU_TEXTUREFORMAT_R16_INT: return "SDL_GPU_TEXTUREFORMAT_R16_INT";
        case SDL_GPU_TEXTUREFORMAT_R16G16_INT: return "SDL_GPU_TEXTUREFORMAT_R16G16_INT";
        case SDL_GPU_TEXTUREFORMAT_R16G16B16A16_INT: return "SDL_GPU_TEXTUREFORMAT_R16G16B16A16_INT";
        case SDL_GPU_TEXTUREFORMAT_R32_INT: return "SDL_GPU_TEXTUREFORMAT_R32_INT";
        case SDL_GPU_TEXTUREFORMAT_R32G32_INT: return "SDL_GPU_TEXTUREFORMAT_R32G32_INT";
        case SDL_GPU_TEXTUREFORMAT_R32G32B32A32_INT: return "SDL_GPU_TEXTUREFORMAT_R32G32B32A32_INT";

        // SRGB Unsigned Normalized Color Formats
        case SDL_GPU_TEXTUREFORMAT_R8G8B8A8_UNORM_SRGB: return "SDL_GPU_TEXTUREFORMAT_R8G8B8A8_UNORM_SRGB";
        case SDL_GPU_TEXTUREFORMAT_B8G8R8A8_UNORM_SRGB: return "SDL_GPU_TEXTUREFORMAT_B8G8R8A8_UNORM_SRGB";

        // Compressed SRGB Unsigned Normalized Color Formats
        case SDL_GPU_TEXTUREFORMAT_BC1_RGBA_UNORM_SRGB: return "SDL_GPU_TEXTUREFORMAT_BC1_RGBA_UNORM_SRGB";
        case SDL_GPU_TEXTUREFORMAT_BC2_RGBA_UNORM_SRGB: return "SDL_GPU_TEXTUREFORMAT_BC2_RGBA_UNORM_SRGB";
        case SDL_GPU_TEXTUREFORMAT_BC3_RGBA_UNORM_SRGB: return "SDL_GPU_TEXTUREFORMAT_BC3_RGBA_UNORM_SRGB";
        case SDL_GPU_TEXTUREFORMAT_BC7_RGBA_UNORM_SRGB: return "SDL_GPU_TEXTUREFORMAT_BC7_RGBA_UNORM_SRGB";

        // Depth Formats
        case SDL_GPU_TEXTUREFORMAT_D16_UNORM: return "SDL_GPU_TEXTUREFORMAT_D16_UNORM";
        case SDL_GPU_TEXTUREFORMAT_D24_UNORM: return "SDL_GPU_TEXTUREFORMAT_D24_UNORM";
        case SDL_GPU_TEXTUREFORMAT_D32_FLOAT: return "SDL_GPU_TEXTUREFORMAT_D32_FLOAT";
        case SDL_GPU_TEXTUREFORMAT_D24_UNORM_S8_UINT: return "SDL_GPU_TEXTUREFORMAT_D24_UNORM_S8_UINT";
        case SDL_GPU_TEXTUREFORMAT_D32_FLOAT_S8_UINT: return "SDL_GPU_TEXTUREFORMAT_D32_FLOAT_S8_UINT";

        // Compressed ASTC Normalized Float Color Formats
        case SDL_GPU_TEXTUREFORMAT_ASTC_4x4_UNORM: return "SDL_GPU_TEXTUREFORMAT_ASTC_4x4_UNORM";
        case SDL_GPU_TEXTUREFORMAT_ASTC_5x4_UNORM: return "SDL_GPU_TEXTUREFORMAT_ASTC_5x4_UNORM";
        case SDL_GPU_TEXTUREFORMAT_ASTC_5x5_UNORM: return "SDL_GPU_TEXTUREFORMAT_ASTC_5x5_UNORM";
        case SDL_GPU_TEXTUREFORMAT_ASTC_6x5_UNORM: return "SDL_GPU_TEXTUREFORMAT_ASTC_6x5_UNORM";
        case SDL_GPU_TEXTUREFORMAT_ASTC_6x6_UNORM: return "SDL_GPU_TEXTUREFORMAT_ASTC_6x6_UNORM";
        case SDL_GPU_TEXTUREFORMAT_ASTC_8x5_UNORM: return "SDL_GPU_TEXTUREFORMAT_ASTC_8x5_UNORM";
        case SDL_GPU_TEXTUREFORMAT_ASTC_8x6_UNORM: return "SDL_GPU_TEXTUREFORMAT_ASTC_8x6_UNORM";
        case SDL_GPU_TEXTUREFORMAT_ASTC_8x8_UNORM: return "SDL_GPU_TEXTUREFORMAT_ASTC_8x8_UNORM";
        case SDL_GPU_TEXTUREFORMAT_ASTC_10x5_UNORM: return "SDL_GPU_TEXTUREFORMAT_ASTC_10x5_UNORM";
        case SDL_GPU_TEXTUREFORMAT_ASTC_10x6_UNORM: return "SDL_GPU_TEXTUREFORMAT_ASTC_10x6_UNORM";
        case SDL_GPU_TEXTUREFORMAT_ASTC_10x8_UNORM: return "SDL_GPU_TEXTUREFORMAT_ASTC_10x8_UNORM";
        case SDL_GPU_TEXTUREFORMAT_ASTC_10x10_UNORM: return "SDL_GPU_TEXTUREFORMAT_ASTC_10x10_UNORM";
        case SDL_GPU_TEXTUREFORMAT_ASTC_12x10_UNORM: return "SDL_GPU_TEXTUREFORMAT_ASTC_12x10_UNORM";
        case SDL_GPU_TEXTUREFORMAT_ASTC_12x12_UNORM: return "SDL_GPU_TEXTUREFORMAT_ASTC_12x12_UNORM";

        // Compressed SRGB ASTC Normalized Float Color Formats
        case SDL_GPU_TEXTUREFORMAT_ASTC_4x4_UNORM_SRGB: return "SDL_GPU_TEXTUREFORMAT_ASTC_4x4_UNORM_SRGB";
        case SDL_GPU_TEXTUREFORMAT_ASTC_5x4_UNORM_SRGB: return "SDL_GPU_TEXTUREFORMAT_ASTC_5x4_UNORM_SRGB";
        case SDL_GPU_TEXTUREFORMAT_ASTC_5x5_UNORM_SRGB: return "SDL_GPU_TEXTUREFORMAT_ASTC_5x5_UNORM_SRGB";
        case SDL_GPU_TEXTUREFORMAT_ASTC_6x5_UNORM_SRGB: return "SDL_GPU_TEXTUREFORMAT_ASTC_6x5_UNORM_SRGB";
        case SDL_GPU_TEXTUREFORMAT_ASTC_6x6_UNORM_SRGB: return "SDL_GPU_TEXTUREFORMAT_ASTC_6x6_UNORM_SRGB";
        case SDL_GPU_TEXTUREFORMAT_ASTC_8x5_UNORM_SRGB: return "SDL_GPU_TEXTUREFORMAT_ASTC_8x5_UNORM_SRGB";
        case SDL_GPU_TEXTUREFORMAT_ASTC_8x6_UNORM_SRGB: return "SDL_GPU_TEXTUREFORMAT_ASTC_8x6_UNORM_SRGB";
        case SDL_GPU_TEXTUREFORMAT_ASTC_8x8_UNORM_SRGB: return "SDL_GPU_TEXTUREFORMAT_ASTC_8x8_UNORM_SRGB";
        case SDL_GPU_TEXTUREFORMAT_ASTC_10x5_UNORM_SRGB: return "SDL_GPU_TEXTUREFORMAT_ASTC_10x5_UNORM_SRGB";
        case SDL_GPU_TEXTUREFORMAT_ASTC_10x6_UNORM_SRGB: return "SDL_GPU_TEXTUREFORMAT_ASTC_10x6_UNORM_SRGB";
        case SDL_GPU_TEXTUREFORMAT_ASTC_10x8_UNORM_SRGB: return "SDL_GPU_TEXTUREFORMAT_ASTC_10x8_UNORM_SRGB";
        case SDL_GPU_TEXTUREFORMAT_ASTC_10x10_UNORM_SRGB: return "SDL_GPU_TEXTUREFORMAT_ASTC_10x10_UNORM_SRGB";
        case SDL_GPU_TEXTUREFORMAT_ASTC_12x10_UNORM_SRGB: return "SDL_GPU_TEXTUREFORMAT_ASTC_12x10_UNORM_SRGB";
        case SDL_GPU_TEXTUREFORMAT_ASTC_12x12_UNORM_SRGB: return "SDL_GPU_TEXTUREFORMAT_ASTC_12x12_UNORM_SRGB";

        // Compressed ASTC Signed Float Color Formats
        case SDL_GPU_TEXTUREFORMAT_ASTC_4x4_FLOAT: return "SDL_GPU_TEXTUREFORMAT_ASTC_4x4_FLOAT";
        case SDL_GPU_TEXTUREFORMAT_ASTC_5x4_FLOAT: return "SDL_GPU_TEXTUREFORMAT_ASTC_5x4_FLOAT";
        case SDL_GPU_TEXTUREFORMAT_ASTC_5x5_FLOAT: return "SDL_GPU_TEXTUREFORMAT_ASTC_5x5_FLOAT";
        case SDL_GPU_TEXTUREFORMAT_ASTC_6x5_FLOAT: return "SDL_GPU_TEXTUREFORMAT_ASTC_6x5_FLOAT";
        case SDL_GPU_TEXTUREFORMAT_ASTC_6x6_FLOAT: return "SDL_GPU_TEXTUREFORMAT_ASTC_6x6_FLOAT";
        case SDL_GPU_TEXTUREFORMAT_ASTC_8x5_FLOAT: return "SDL_GPU_TEXTUREFORMAT_ASTC_8x5_FLOAT";
        case SDL_GPU_TEXTUREFORMAT_ASTC_8x6_FLOAT: return "SDL_GPU_TEXTUREFORMAT_ASTC_8x6_FLOAT";
        case SDL_GPU_TEXTUREFORMAT_ASTC_8x8_FLOAT: return "SDL_GPU_TEXTUREFORMAT_ASTC_8x8_FLOAT";
        case SDL_GPU_TEXTUREFORMAT_ASTC_10x5_FLOAT: return "SDL_GPU_TEXTUREFORMAT_ASTC_10x5_FLOAT";
        case SDL_GPU_TEXTUREFORMAT_ASTC_10x6_FLOAT: return "SDL_GPU_TEXTUREFORMAT_ASTC_10x6_FLOAT";
        case SDL_GPU_TEXTUREFORMAT_ASTC_10x8_FLOAT: return "SDL_GPU_TEXTUREFORMAT_ASTC_10x8_FLOAT";
        case SDL_GPU_TEXTUREFORMAT_ASTC_10x10_FLOAT: return "SDL_GPU_TEXTUREFORMAT_ASTC_10x10_FLOAT";
        case SDL_GPU_TEXTUREFORMAT_ASTC_12x10_FLOAT: return "SDL_GPU_TEXTUREFORMAT_ASTC_12x10_FLOAT";
        case SDL_GPU_TEXTUREFORMAT_ASTC_12x12_FLOAT: return "SDL_GPU_TEXTUREFORMAT_ASTC_12x12_FLOAT";

        default: return "Unknown";
    }
}
