/*
Copyright (c) 2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module dagon.render.deferred.passes.decal;

import dlib.core.memory;
import dlib.core.ownership;
import dlib.math.vector;
import dlib.math.matrix;
import dlib.math.transformation;
import dlib.image.color;

import dagon.core.sdl3;
import dagon.core.gpu;
import dagon.core.crashhandler;
import dagon.graphics.state;
import dagon.graphics.entity;
import dagon.graphics.material;
import dagon.graphics.mesh;
import dagon.resource.shader;
import dagon.render.renderer;
import dagon.render.pass;
import dagon.render.view;
import dagon.render.deferred.gbuffer;

struct DecalShaderVertexUniformBuffer
{
    Matrix4x4f modelViewMatrix;
    Matrix4x4f normalMatrix;
    Matrix4x4f projectionMatrix;
}

struct DecalShaderFragmentUniformBuffer
{
    Matrix4x4f invViewMatrix;
    Matrix4x4f invModelMatrix;
    Matrix4x4f invProjectionMatrix;
    Color4f baseColor;
    Vector4f roughnessMetallic;
    Color4f emission;
    Vector4f alphaOptions;
    uint[4] flags;
    float[4] fparams;
    Vector4f resolution;
    Vector4f decalDirection;
}

enum DecalFlags
{
    Texture = 0,
}

enum DecalTextureFlags: uint
{
    HasBaseColorTexture = 1 << 0,
    HasNormalTexture = 1 << 1,
    HasHeightTexture = 1 << 2,
    HasRoughnessMetallicTexture = 1 << 3,
    HasEmissionTexture = 1 << 4
}

class DecalShader: Shader
{
   protected:
    DecalShaderVertexUniformBuffer vsUBO;
    DecalShaderFragmentUniformBuffer fsUBO;
    
   public:
    this(GPU gpu, Owner owner)
    {
        super(gpu, owner);
        
        vertexModule = New!ShaderModule(gpu, this);
        vertexModule.create("Decal.vert.glsl", "data/__internal/shaders/Decal/Decal.vert.glsl",
            ShaderSourceType.File, ShaderLanguage.GLSL, PipelineStage.Vertex);
        
        fragmentModule = New!ShaderModule(gpu, this);
        fragmentModule.create("Decal.frag.glsl", "data/__internal/shaders/Decal/Decal.frag.glsl",
            ShaderSourceType.File, ShaderLanguage.GLSL, PipelineStage.Fragment);
        
        if (!vertexModule.valid || !fragmentModule.valid)
        {
            exitWithError("Failed to create DecalShader");
        }
        
        vsUBO.modelViewMatrix = Matrix4x4f.identity;
        vsUBO.normalMatrix = Matrix4x4f.identity;
        vsUBO.projectionMatrix = Matrix4x4f.identity;
        
        fsUBO.invViewMatrix = Matrix4x4f.identity;
        fsUBO.invModelMatrix = Matrix4x4f.identity;
        fsUBO.invProjectionMatrix = Matrix4x4f.identity;
        fsUBO.baseColor = Color4f(1.0f, 1.0f, 1.0f, 1.0f);
        fsUBO.roughnessMetallic = Vector4f(0.0f, 0.5f, 0.0f, 0.0f);
        fsUBO.emission = Color4f(0.0f, 0.0f, 0.0f, 0.0f);
        fsUBO.alphaOptions = Vector4f(0.5f, 1.0f, 1.0f, 1.0f);
        fsUBO.fparams[0] = 0.0f;
        fsUBO.fparams[1] = 0.0f;
        fsUBO.fparams[2] = 0.0f;
        fsUBO.fparams[3] = 0.0f;
        fsUBO.resolution = Vector4f(0.0f, 0.0f, 0.0f, 0.0f);
        fsUBO.decalDirection = Vector4f(0.0f, 0.0f, 0.0f, 0.0f);
    }
    
    override void bindParameters(GraphicsState* state)
    {
        auto pass = state.pass;
        auto entity = state.entity;
        auto material = state.material;
        
        vsUBO.modelViewMatrix = pass.view.viewMatrix * entity.modelMatrix;
        vsUBO.normalMatrix = vsUBO.modelViewMatrix.inverse.transposed;
        vsUBO.projectionMatrix = pass.view.projectionMatrix;
        
        fsUBO.invViewMatrix = pass.view.invViewMatrix;
        fsUBO.invModelMatrix = entity.invModelMatrix;
        fsUBO.invProjectionMatrix = pass.view.invProjectionMatrix;
        
        fsUBO.flags[DecalFlags.Texture] = 0;
        fsUBO.flags[1] = 0;
        fsUBO.flags[2] = 0;
        fsUBO.flags[3] = 0;
        fsUBO.baseColor = material.baseColor;
        
        fsUBO.roughnessMetallic.g = material.roughness;
        fsUBO.roughnessMetallic.b = material.metallic;
        
        fsUBO.emission = material.emissionColor * material.emissionEnergy;
        
        fsUBO.alphaOptions.x = material.alphaClipThreshold;
        fsUBO.alphaOptions.y = cast(float)!material.shadeless;
        fsUBO.alphaOptions.z = entity.motionBlurMask;
        fsUBO.alphaOptions.w = entity.opacity * material.opacity;
        
        fsUBO.fparams[0] = material.ior / 12.5f * material.iorLevel;
        
        fsUBO.resolution.x = pass.view.width;
        fsUBO.resolution.y = pass.view.height;
        
        Vector4f decalDirectionModel = Vector4f(0.0f, 0.0f, 1.0f, 0.0f);
        fsUBO.decalDirection = decalDirectionModel * vsUBO.normalMatrix;
        
        if (material.baseColorTexture)
        {
            pass.bindTexture(PipelineStage.Fragment, 0, material.baseColorTexture);
            fsUBO.flags[DecalFlags.Texture] |= DecalTextureFlags.HasBaseColorTexture;
        }
        else
            pass.bindDefaultTexture(PipelineStage.Fragment, 0);
        
        if (material.normalTexture)
        {
            pass.bindTexture(PipelineStage.Fragment, 1, material.normalTexture);
            fsUBO.flags[DecalFlags.Texture] |= DecalTextureFlags.HasNormalTexture;
        }
        else
            pass.bindDefaultTexture(PipelineStage.Fragment, 1);
        
        if (material.heightTexture)
        {
            pass.bindTexture(PipelineStage.Fragment, 2, material.heightTexture);
            fsUBO.flags[DecalFlags.Texture] |= DecalTextureFlags.HasHeightTexture;
        }
        else
            pass.bindDefaultTexture(PipelineStage.Fragment, 2);
        
        if (material.roughnessMetallicTexture)
        {
            pass.bindTexture(PipelineStage.Fragment, 3, material.roughnessMetallicTexture);
            fsUBO.flags[DecalFlags.Texture] |= DecalTextureFlags.HasRoughnessMetallicTexture;
        }
        else
            pass.bindDefaultTexture(PipelineStage.Fragment, 3);
        
        if (material.emissionTexture)
        {
            pass.bindTexture(PipelineStage.Fragment, 4, material.emissionTexture);
            fsUBO.flags[DecalFlags.Texture] |= DecalTextureFlags.HasEmissionTexture;
        }
        else
            pass.bindDefaultTexture(PipelineStage.Fragment, 4);
        
        pass.bindInputBuffer(PipelineStage.Fragment, 5, &state.depthBuffer);
        pass.bindInputBuffer(PipelineStage.Fragment, 6, &state.velocityBuffer);
        
        pass.bindUniformBuffer(PipelineStage.Vertex, 0, &vsUBO);
        pass.bindUniformBuffer(PipelineStage.Fragment, 0, &fsUBO);
    }
}

class DecalPass: RenderPass
{
   protected:
    GPU gpu;
    GBuffer gbuffer;
    DecalShader decalShader;
    SDL_GPUColorTargetDescription[4] colorTargetsDescription;
    SDL_GPUColorTargetInfo[4] colorTargets;
    //SDL_GPUDepthStencilTargetInfo depthStencilTarget;
    
   public:
    this(Renderer renderer, GBuffer gbuffer)
    {
        super(renderer);
        this.gpu = renderer.gpu;
        this.gbuffer = gbuffer;
        decalShader = New!DecalShader(gpu, this);
        
        SDL_GPUGraphicsPipelineCreateInfo pipelineCreateInfo;
        pipelineCreateInfo.vertex_shader = decalShader.vertexModule.shader;
        pipelineCreateInfo.fragment_shader = decalShader.fragmentModule.shader;
        pipelineCreateInfo.primitive_type = SDL_GPU_PRIMITIVETYPE_TRIANGLELIST;
        
        SDL_GPUVertexBufferDescription[3] vbDescriptions;
        
        vbDescriptions[0].slot = 0;
        vbDescriptions[0].input_rate = SDL_GPU_VERTEXINPUTRATE_VERTEX;
        vbDescriptions[0].instance_step_rate = 0;
        vbDescriptions[0].pitch = Vector3f.sizeof;
        
        vbDescriptions[1].slot = 1;
        vbDescriptions[1].input_rate = SDL_GPU_VERTEXINPUTRATE_VERTEX;
        vbDescriptions[1].instance_step_rate = 0;
        vbDescriptions[1].pitch = Vector2f.sizeof;
        
        vbDescriptions[2].slot = 2;
        vbDescriptions[2].input_rate = SDL_GPU_VERTEXINPUTRATE_VERTEX;
        vbDescriptions[2].instance_step_rate = 0;
        vbDescriptions[2].pitch = Vector3f.sizeof;

        pipelineCreateInfo.vertex_input_state.num_vertex_buffers = vbDescriptions.length;
        pipelineCreateInfo.vertex_input_state.vertex_buffer_descriptions = vbDescriptions.ptr;
        
        SDL_GPUVertexAttribute[3] vertexAttributes;
    
        // Position
        vertexAttributes[0].buffer_slot = VertexAttribute.Position;
        vertexAttributes[0].location = VertexAttribute.Position;
        vertexAttributes[0].format = SDL_GPU_VERTEXELEMENTFORMAT_FLOAT3;
        vertexAttributes[0].offset = 0;
        
        // Texcoords
        vertexAttributes[1].buffer_slot = VertexAttribute.Texcoord;
        vertexAttributes[1].location = VertexAttribute.Texcoord;
        vertexAttributes[1].format = SDL_GPU_VERTEXELEMENTFORMAT_FLOAT2;
        vertexAttributes[1].offset = 0;
        
        // Normals
        vertexAttributes[2].buffer_slot = VertexAttribute.Normal;
        vertexAttributes[2].location = VertexAttribute.Normal;
        vertexAttributes[2].format = SDL_GPU_VERTEXELEMENTFORMAT_FLOAT3;
        vertexAttributes[2].offset = 0;
        
        pipelineCreateInfo.vertex_input_state.num_vertex_attributes = vertexAttributes.length;
        pipelineCreateInfo.vertex_input_state.vertex_attributes = vertexAttributes.ptr;
        
        SDL_GPUColorTargetBlendState blendState = {
            src_color_blendfactor: SDL_GPU_BLENDFACTOR_SRC_ALPHA,
            dst_color_blendfactor: SDL_GPU_BLENDFACTOR_ONE_MINUS_SRC_ALPHA,
            color_blend_op: SDL_GPU_BLENDOP_ADD,
            src_alpha_blendfactor: SDL_GPU_BLENDFACTOR_SRC_ALPHA,
            dst_alpha_blendfactor: SDL_GPU_BLENDFACTOR_ONE_MINUS_SRC_ALPHA,
            alpha_blend_op: SDL_GPU_BLENDOP_ADD,
            color_write_mask: 0,
            enable_blend: true,
            enable_color_write_mask: false
        };
        
        // Color target 0 - color buffer
        colorTargetsDescription[0].format = SDL_GPU_TEXTUREFORMAT_R8G8B8A8_UNORM;
        colorTargetsDescription[0].blend_state = blendState;
        colorTargets[0].load_op = SDL_GPU_LOADOP_LOAD;
        colorTargets[0].store_op = SDL_GPU_STOREOP_STORE;
        colorTargets[0].texture = gbuffer.colorBuffer;
        
        // Target 1 - normal buffer
        colorTargetsDescription[1].format = SDL_GPU_TEXTUREFORMAT_R16G16B16A16_FLOAT;
        colorTargetsDescription[1].blend_state = blendState;
        colorTargets[1].load_op = SDL_GPU_LOADOP_LOAD;
        colorTargets[1].store_op = SDL_GPU_STOREOP_STORE;
        colorTargets[1].texture = gbuffer.normalBuffer;
        
        // Target 2 - roughness/metallic buffer
        colorTargetsDescription[2].format = SDL_GPU_TEXTUREFORMAT_R8G8B8A8_UNORM;
        colorTargetsDescription[2].blend_state = blendState;
        colorTargets[2].load_op = SDL_GPU_LOADOP_LOAD;
        colorTargets[2].store_op = SDL_GPU_STOREOP_STORE;
        colorTargets[2].texture = gbuffer.roughnessMetallicBuffer;
        
        // Target 3 - emission buffer
        colorTargetsDescription[3].format = SDL_GPU_TEXTUREFORMAT_R16G16B16A16_FLOAT;
        colorTargetsDescription[3].blend_state = blendState;
        colorTargets[3].load_op = SDL_GPU_LOADOP_LOAD;
        colorTargets[3].store_op = SDL_GPU_STOREOP_STORE;
        colorTargets[3].texture = gbuffer.emissionBuffer;
        
        pipelineCreateInfo.target_info.num_color_targets = colorTargetsDescription.length;
        pipelineCreateInfo.target_info.color_target_descriptions = colorTargetsDescription.ptr;
        pipelineCreateInfo.target_info.has_depth_stencil_target = false;
        
        pipelineCreateInfo.rasterizer_state.fill_mode = SDL_GPU_FILLMODE_FILL;
        pipelineCreateInfo.rasterizer_state.cull_mode = SDL_GPU_CULLMODE_NONE;
        pipelineCreateInfo.rasterizer_state.front_face = SDL_GPU_FRONTFACE_COUNTER_CLOCKWISE;
        pipelineCreateInfo.rasterizer_state.depth_bias_constant_factor = 0.0f;
        pipelineCreateInfo.rasterizer_state.depth_bias_clamp = 0.0f;
        pipelineCreateInfo.rasterizer_state.depth_bias_slope_factor = 1.0f;
        pipelineCreateInfo.rasterizer_state.enable_depth_bias = false;
        pipelineCreateInfo.rasterizer_state.enable_depth_clip = false;
        
        pipelineCreateInfo.depth_stencil_state.compare_op = SDL_GPU_COMPAREOP_LESS_OR_EQUAL;
        pipelineCreateInfo.depth_stencil_state.enable_depth_test = false;
        pipelineCreateInfo.depth_stencil_state.enable_depth_write = false;
        pipelineCreateInfo.depth_stencil_state.enable_stencil_test = false;
        
        graphicsPipeline = SDL_CreateGPUGraphicsPipeline(gpu.device, &pipelineCreateInfo);
        
        colorTargetsInfo = colorTargets.ptr;
        numColorTargets = colorTargets.length; // color, normal, roughness-metallic, emission
        depthStencilTargetInfo = null; //&depthStencilTarget;
        enableDepthTarget = false;
    }
    
    override void render(GraphicsState* state)
    {
        if (state.scene is null)
            return;
        
        colorTargets[0].texture = gbuffer.colorBuffer;
        colorTargets[1].texture = gbuffer.normalBuffer;
        colorTargets[2].texture = gbuffer.roughnessMetallicBuffer;
        colorTargets[3].texture = gbuffer.emissionBuffer;
        
        debug SDL_PushGPUDebugGroup(renderer.commandBuffer, "DECAL");
        beginPass();
        
        state.depthBuffer = InputBuffer(gbuffer.depthBuffer, gbuffer.depthSampler);
        state.velocityBuffer = InputBuffer(gbuffer.velocityBuffer, gbuffer.colorSampler);
        
        foreach(entity; state.scene.entities)
        {
            if (entity.visible && entity.isDecal && entity.drawable)
            {
                state.entity = entity;
                if (entity.material)
                    state.material = entity.material;
                else
                    state.material = renderer.defaultMaterial;
                decalShader.bindParameters(state);
                entity.drawable.render(state);
            }
        }
        
        endPass();
        debug SDL_PopGPUDebugGroup(renderer.commandBuffer);
    }
}
