/*
Copyright (c) 2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module dagon.render.deferred.passes.sunlight;

import dlib.core.memory;
import dlib.core.ownership;
import dlib.math.vector;
import dlib.math.matrix;
import dlib.image.color;

import dagon.core.sdl3;
import dagon.core.gpu;
import dagon.core.crashhandler;
import dagon.graphics.state;
import dagon.graphics.mesh;
import dagon.graphics.shapes;
import dagon.graphics.csm;
import dagon.resource.shader;
import dagon.render.renderer;
import dagon.render.pass;
import dagon.render.view;
import dagon.render.deferred.gbuffer;

struct SunLightShaderVertexUniformBuffer
{
    // TODO
}

struct SunLightShaderFragmentUniformBuffer
{
    Matrix4x4f invViewMatrix;
    Matrix4x4f invProjectionMatrix;
    Matrix4x4f shadowMatrix1;
    Matrix4x4f shadowMatrix2;
    Matrix4x4f shadowMatrix3;
    Vector4f lighVector;
    Color4f lightColor;
    Vector4f shadowTextureResolution;
}

class SunLightShader: Shader
{
   protected:
    SunLightShaderVertexUniformBuffer vsUBO;
    SunLightShaderFragmentUniformBuffer fsUBO;
    
   public:
    this(GPU gpu, Owner owner)
    {
        super(gpu, owner);
        
        vertexModule = New!ShaderModule(gpu, this);
        vertexModule.create("SunLight.vert.glsl", "data/__internal/shaders/SunLight/SunLight.vert.glsl",
            ShaderSourceType.File, ShaderLanguage.GLSL, PipelineStage.Vertex);
        
        fragmentModule = New!ShaderModule(gpu, this);
        fragmentModule.create("SunLight.frag.glsl", "data/__internal/shaders/SunLight/SunLight.frag.glsl",
            ShaderSourceType.File, ShaderLanguage.GLSL, PipelineStage.Fragment);
        
        if (!vertexModule.valid || !fragmentModule.valid)
        {
            exitWithError("Failed to create SunLightShader");
        }
        
        fsUBO.invViewMatrix = Matrix4x4f.identity;
        fsUBO.invProjectionMatrix = Matrix4x4f.identity;
        fsUBO.lighVector = Vector4f(0.0f, 0.0f, 1.0f, 0.0f);
        fsUBO.lightColor = Color4f(1.0f, 1.0f, 1.0f, 1.0f);
        fsUBO.shadowTextureResolution = Vector4f(0.0f, 0.0f, 0.0f, 0.0f);
        fsUBO.shadowMatrix1 = Matrix4x4f.identity;
        fsUBO.shadowMatrix2 = Matrix4x4f.identity;
        fsUBO.shadowMatrix3 = Matrix4x4f.identity;
    }
    
    override void bindParameters(GraphicsState* state)
    {
        auto pass = state.pass;
        auto view = pass.view;
        auto scene = state.scene;
        auto sun = scene.sun;
        
        fsUBO.invViewMatrix = view.invViewMatrix;
        fsUBO.invProjectionMatrix = view.invProjectionMatrix;
        fsUBO.lighVector = Vector4f(sun.directionWorld);
        fsUBO.lighVector.w = 0.0;
        fsUBO.lighVector = fsUBO.lighVector * view.viewMatrix;
        fsUBO.lightColor = sun.color;
        fsUBO.lightColor.a = sun.energy;
        
        CascadedShadowMap shadowMap = cast(CascadedShadowMap)sun.shadowMap;
        if (shadowMap)
        {
            fsUBO.shadowTextureResolution.x = shadowMap.resolution;
            fsUBO.shadowTextureResolution.y = shadowMap.resolution;
            fsUBO.shadowMatrix1 = shadowMap.area[0].shadowMatrix;
            fsUBO.shadowMatrix2 = shadowMap.area[1].shadowMatrix;
            fsUBO.shadowMatrix3 = shadowMap.area[2].shadowMatrix;
        }
        else
        {
            fsUBO.shadowTextureResolution.x = 0.0f;
            fsUBO.shadowTextureResolution.y = 0.0f;
            fsUBO.shadowMatrix1 = Matrix4x4f.identity;
            fsUBO.shadowMatrix2 = Matrix4x4f.identity;
            fsUBO.shadowMatrix3 = Matrix4x4f.identity;
        }
        
        pass.bindInputBuffer(PipelineStage.Fragment, 0, &state.colorBuffer);
        pass.bindInputBuffer(PipelineStage.Fragment, 1, &state.normalBuffer);
        pass.bindInputBuffer(PipelineStage.Fragment, 2, &state.roughnessMetallicBuffer);
        pass.bindInputBuffer(PipelineStage.Fragment, 3, &state.depthBuffer);
        pass.bindTexture(PipelineStage.Fragment, 4, shadowMap.depthTexture, shadowMap.depthSampler);
        
        //pass.bindUniformBuffer(PipelineStage.Vertex, 0, &vsUBO);
        pass.bindUniformBuffer(PipelineStage.Fragment, 0, &fsUBO);
    }
}

class SunLightPass: RenderPass
{
    GPU gpu;
    GBuffer gbuffer;
    SunLightShader sunLightShader;
    
    SDL_GPUColorTargetDescription colorTargetDescription;
    SDL_GPUColorTargetInfo colorTargetInfo;
    
    this(Renderer renderer, GBuffer gbuffer)
    {
        super(renderer);
        this.gpu = renderer.gpu;
        this.gbuffer = gbuffer;
        sunLightShader = New!SunLightShader(gpu, this);
        shader = sunLightShader;
        
        SDL_GPUGraphicsPipelineCreateInfo pipelineCreateInfo;
        pipelineCreateInfo.vertex_shader = sunLightShader.vertexModule.shader;
        pipelineCreateInfo.fragment_shader = sunLightShader.fragmentModule.shader;
        pipelineCreateInfo.primitive_type = SDL_GPU_PRIMITIVETYPE_TRIANGLELIST;
        
        SDL_GPUVertexBufferDescription[2] vbDescriptions;
        
        vbDescriptions[0].slot = VertexAttribute.Position;
        vbDescriptions[0].input_rate = SDL_GPU_VERTEXINPUTRATE_VERTEX;
        vbDescriptions[0].instance_step_rate = 0;
        vbDescriptions[0].pitch = Vector2f.sizeof;
        
        vbDescriptions[1].slot = VertexAttribute.Texcoord;
        vbDescriptions[1].input_rate = SDL_GPU_VERTEXINPUTRATE_VERTEX;
        vbDescriptions[1].instance_step_rate = 0;
        vbDescriptions[1].pitch = Vector2f.sizeof;

        pipelineCreateInfo.vertex_input_state.num_vertex_buffers = vbDescriptions.length;
        pipelineCreateInfo.vertex_input_state.vertex_buffer_descriptions = vbDescriptions.ptr;
        
        SDL_GPUVertexAttribute[2] vertexAttributes;
    
        // Position
        vertexAttributes[0].buffer_slot = VertexAttribute.Position;
        vertexAttributes[0].location = VertexAttribute.Position;
        vertexAttributes[0].format = SDL_GPU_VERTEXELEMENTFORMAT_FLOAT2;
        vertexAttributes[0].offset = 0;
        
        // Texcoords
        vertexAttributes[1].buffer_slot = VertexAttribute.Texcoord;
        vertexAttributes[1].location = VertexAttribute.Texcoord;
        vertexAttributes[1].format = SDL_GPU_VERTEXELEMENTFORMAT_FLOAT2;
        vertexAttributes[1].offset = 0;
        
        pipelineCreateInfo.vertex_input_state.num_vertex_attributes = vertexAttributes.length;
        pipelineCreateInfo.vertex_input_state.vertex_attributes = vertexAttributes.ptr;
        
        SDL_GPUColorTargetBlendState blendState = {
            src_color_blendfactor: SDL_GPU_BLENDFACTOR_ONE,
            dst_color_blendfactor: SDL_GPU_BLENDFACTOR_ONE,
            color_blend_op: SDL_GPU_BLENDOP_ADD,
            src_alpha_blendfactor: SDL_GPU_BLENDFACTOR_ONE,
            dst_alpha_blendfactor: SDL_GPU_BLENDFACTOR_ONE,
            alpha_blend_op: SDL_GPU_BLENDOP_ADD,
            color_write_mask: 0,
            enable_blend: true,
            enable_color_write_mask: false
        };
        colorTargetDescription.format = SDL_GPU_TEXTUREFORMAT_R16G16B16A16_FLOAT;
        colorTargetDescription.blend_state = blendState;
        
        pipelineCreateInfo.target_info.num_color_targets = 1;
        pipelineCreateInfo.target_info.color_target_descriptions = &colorTargetDescription;
        pipelineCreateInfo.target_info.has_depth_stencil_target = false;
        
        pipelineCreateInfo.rasterizer_state.fill_mode = SDL_GPU_FILLMODE_FILL;
        pipelineCreateInfo.rasterizer_state.cull_mode = SDL_GPU_CULLMODE_NONE;
        pipelineCreateInfo.rasterizer_state.front_face = SDL_GPU_FRONTFACE_COUNTER_CLOCKWISE;
        pipelineCreateInfo.rasterizer_state.depth_bias_constant_factor = 0.0f;
        pipelineCreateInfo.rasterizer_state.depth_bias_clamp = 0.0f;
        pipelineCreateInfo.rasterizer_state.depth_bias_slope_factor = 1.0f;
        pipelineCreateInfo.rasterizer_state.enable_depth_bias = false;
        pipelineCreateInfo.rasterizer_state.enable_depth_clip = false;
        
        pipelineCreateInfo.depth_stencil_state.compare_op = SDL_GPU_COMPAREOP_LESS;
        pipelineCreateInfo.depth_stencil_state.enable_depth_test = false;
        pipelineCreateInfo.depth_stencil_state.enable_depth_write = false;
        pipelineCreateInfo.depth_stencil_state.enable_stencil_test = false;
        
        graphicsPipeline = SDL_CreateGPUGraphicsPipeline(gpu.device, &pipelineCreateInfo);
        
        colorTargetInfo.clear_color = SDL_FColor(0.0f, 0.0f, 0.0f, 0.0f);
        colorTargetInfo.load_op = SDL_GPU_LOADOP_LOAD;
        colorTargetInfo.store_op = SDL_GPU_STOREOP_STORE;
        colorTargetInfo.texture = gbuffer.radianceBuffer;
        
        colorTargetsInfo = &colorTargetInfo;
        numColorTargets = 1;
        depthStencilTargetInfo = null;
        enableDepthTarget = false;
    }
    
    override void render(GraphicsState* state)
    {
        if (state.scene is null)
            return;
        
        colorTargetInfo.texture = gbuffer.radianceBuffer;
        
        debug SDL_PushGPUDebugGroup(renderer.commandBuffer, "SUN_LIGHT");
        beginPass();
        
        state.depthBuffer = InputBuffer(gbuffer.depthBuffer, gbuffer.depthSampler);
        state.colorBuffer = InputBuffer(gbuffer.colorBuffer, gbuffer.colorSampler);
        state.normalBuffer = InputBuffer(gbuffer.normalBuffer, gbuffer.colorSampler);
        state.roughnessMetallicBuffer = InputBuffer(gbuffer.roughnessMetallicBuffer, gbuffer.colorSampler);
        state.emissionBuffer = InputBuffer(gbuffer.emissionBuffer, gbuffer.colorSampler);
        state.velocityBuffer = InputBuffer(gbuffer.velocityBuffer, gbuffer.colorSampler);
        state.radianceBuffer = InputBuffer(null, null);
        state.entity = null;
        sunLightShader.bindParameters(state);
        
        renderer.renderScreenQuad(state);
        
        endPass();
        debug SDL_PopGPUDebugGroup(renderer.commandBuffer);
    }
}
