/*
Copyright (c) 2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module dagon.ext.imgui.backend;

import core.stdc.string: memcpy;

import dlib.core.memory;
import dlib.core.ownership;
import dlib.math.vector;

import dagon.core.crashhandler;
import dagon.core.sdl3;
import dagon.core.gpu;
import dagon.core.logger;
import dagon.graphics.texture;
import dagon.graphics.state;
import dagon.resource.shader;
import dagon.render.pass;
import dagon.render.renderer;

import bindbc.imgui;

struct ImGuiShaderVertexUniformBuffer
{
    Vector4f position;
    Vector4f scaling;
}

class ImGuiShader: Shader
{
   protected:
    ImGuiShaderVertexUniformBuffer vsUBO;
   
   public:
    Vector2f position = Vector2f(0.0f, 0.0f);
    Vector2f scaling = Vector2f(1.0f, 1.0f);
    Texture texture;
    
    this(GPU gpu, Owner owner)
    {
        super(gpu, owner);
        
        vertexModule = New!ShaderModule(gpu, this);
        vertexModule.create("ImGui.vert.glsl", "data/__internal/shaders/ImGui/ImGui.vert.glsl",
            ShaderSourceType.File, ShaderLanguage.GLSL, PipelineStage.Vertex);
        
        fragmentModule = New!ShaderModule(gpu, this);
        fragmentModule.create("ImGui.frag.glsl", "data/__internal/shaders/ImGui/ImGui.frag.glsl",
            ShaderSourceType.File, ShaderLanguage.GLSL, PipelineStage.Fragment);
        
        if (!vertexModule.valid || !fragmentModule.valid)
        {
            exitWithError("Failed to create ImGuiShader");
        }
        
        vsUBO.position = Vector4f(0.0f, 0.0f, 0.0f, 1.0f);
        vsUBO.scaling = Vector4f(1.0f, 1.0f, 0.0f, 1.0f);
    }
    
    override void bindParameters(GraphicsState* state)
    {
        auto pass = state.pass;
        
        vsUBO.position = Vector4f(position.x, position.y, 0.0f, 1.0f);
        vsUBO.scaling = Vector4f(scaling.x, scaling.y, 0.0f, 1.0f);
        
        if (texture)
            pass.bindTexture(PipelineStage.Fragment, 0, texture);
        else
            pass.bindDefaultTexture(PipelineStage.Fragment, 0);
        
        pass.bindUniformBuffer(PipelineStage.Vertex, 0, &vsUBO);
    }
}

struct ImGui_ImplSDLGPU3_InitInfo
{
    SDL_GPUDevice* device;
    SDL_GPUTextureFormat colorTargetFormat = SDL_GPU_TEXTUREFORMAT_INVALID;
    SDL_GPUSampleCount msaaSamples = SDL_GPU_SAMPLECOUNT_1;
    SDL_GPUSwapchainComposition swapchainComposition = SDL_GPU_SWAPCHAINCOMPOSITION_SDR; // Only used in multi-viewports mode.
    SDL_GPUPresentMode presentMode = SDL_GPU_PRESENTMODE_VSYNC; // Only used in multi-viewports mode.
}

struct ImGui_ImplSDLGPU3_RenderState
{
    SDL_GPUDevice* device;
}

// Reusable buffers for rendering a frame
struct ImGui_ImplSDLGPU3_FrameData
{
    SDL_GPUBuffer* vertexBuffer;
    uint vertexBufferSize;
    SDL_GPUBuffer* indexBuffer;
    uint indexBufferSize;
}

struct ImGui_ImplSDLGPU3_Data
{
    ImGui_ImplSDLGPU3_InitInfo initInfo;

    // Render state
    ImGui_ImplSDLGPU3_RenderState renderState;
    SDL_GPUSampler* currentSampler;

    // Graphics pipeline and shaders
    SDL_GPUShader* vertexShader;
    SDL_GPUShader* fragmentShader;
    SDL_GPUGraphicsPipeline* pipeline;

    // Frame data for main window
    ImGui_ImplSDLGPU3_FrameData mainWindowFrameData;
}

class ImGuiPass: RenderPass
{
   protected:
    GPU gpu;
    ImGuiShader imguiShader;
    Texture fontTexture;
    
    SDL_GPUBuffer* vertexBuffer = null;
    SDL_GPUBuffer* indexBuffer = null;
    uint vertexBufferSize = 0;
    uint indexBufferSize = 0;
    
    ImGui_ImplSDLGPU3_Data backendData;
    
    SDL_GPUColorTargetInfo colorTargetInfo;
    
   public:
    this(Renderer renderer)
    {
        super(renderer);
        this.gpu = renderer.gpu;
        
        imguiShader = New!ImGuiShader(gpu, this);
        shader = imguiShader;
        
        if (!initGraphicsPipeline())
            exitWithError("Error initializing ImGuiPass");
        
        createFontTexture();
        
        ImGuiIO* io = igGetIO();
        io.BackendFlags |= cast(int)ImGuiBackendFlags.RendererHasVtxOffset;
        io.BackendFlags |= cast(int)ImGuiBackendFlags.RendererHasViewports;
        io.BackendRendererUserData = cast(void*)&backendData;
        io.BackendRendererName = "imgui_impl_dagon";
    }

    ~this()
    {
        if (vertexBuffer) SDL_ReleaseGPUBuffer(gpu.device, vertexBuffer);
        if (indexBuffer) SDL_ReleaseGPUBuffer(gpu.device, indexBuffer);
        if (backendData.currentSampler) SDL_ReleaseGPUSampler(gpu.device, backendData.currentSampler);
    }
    
   protected:
    bool initGraphicsPipeline()
    {
        backendData.initInfo.device = gpu.device;
        backendData.initInfo.colorTargetFormat = gpu.swapchainTextureFormat;
        backendData.initInfo.msaaSamples = SDL_GPU_SAMPLECOUNT_1;
        
        backendData.renderState.device = gpu.device;
        
        backendData.vertexShader = imguiShader.vertexModule.shader;
        backendData.fragmentShader = imguiShader.fragmentModule.shader;
        
        SDL_GPUVertexBufferDescription vbDesc;
        vbDesc.slot = 0;
        vbDesc.input_rate = SDL_GPU_VERTEXINPUTRATE_VERTEX;
        vbDesc.instance_step_rate = 0;
        vbDesc.pitch = ImDrawVert.sizeof;
        
        SDL_GPUVertexAttribute[3] va;
        va[0].buffer_slot = 0;
        va[0].format = SDL_GPU_VERTEXELEMENTFORMAT_FLOAT2;
        va[0].location = 0;
        va[0].offset = ImDrawVert.pos.offsetof;

        va[1].buffer_slot = 0;
        va[1].format = SDL_GPU_VERTEXELEMENTFORMAT_FLOAT2;
        va[1].location = 1;
        va[1].offset = ImDrawVert.uv.offsetof;

        va[2].buffer_slot = 0;
        va[2].format = SDL_GPU_VERTEXELEMENTFORMAT_UBYTE4_NORM;
        va[2].location = 2;
        va[2].offset = ImDrawVert.col.offsetof;
        
        SDL_GPUVertexInputState vertexInputState;
        vertexInputState.num_vertex_attributes = va.length;
        vertexInputState.vertex_attributes = va.ptr;
        vertexInputState.num_vertex_buffers = 1;
        vertexInputState.vertex_buffer_descriptions = &vbDesc;
        
        SDL_GPURasterizerState rasterizerState;
        rasterizerState.fill_mode = SDL_GPU_FILLMODE_FILL;
        rasterizerState.cull_mode = SDL_GPU_CULLMODE_NONE;
        rasterizerState.front_face = SDL_GPU_FRONTFACE_COUNTER_CLOCKWISE;
        rasterizerState.enable_depth_bias = false;
        rasterizerState.enable_depth_clip = false;
        
        SDL_GPUMultisampleState multisampleState;
        multisampleState.sample_count = backendData.initInfo.msaaSamples;
        multisampleState.enable_mask = false;
        
        SDL_GPUDepthStencilState depthStencilState;
        depthStencilState.enable_depth_test = false;
        depthStencilState.enable_depth_write = false;
        depthStencilState.enable_stencil_test = false;
        
        SDL_GPUColorTargetBlendState blendState;
        blendState.enable_blend = true;
        blendState.src_color_blendfactor = SDL_GPU_BLENDFACTOR_SRC_ALPHA;
        blendState.dst_color_blendfactor = SDL_GPU_BLENDFACTOR_ONE_MINUS_SRC_ALPHA;
        blendState.color_blend_op = SDL_GPU_BLENDOP_ADD;
        blendState.src_alpha_blendfactor = SDL_GPU_BLENDFACTOR_ONE;
        blendState.dst_alpha_blendfactor = SDL_GPU_BLENDFACTOR_ONE_MINUS_SRC_ALPHA;
        blendState.alpha_blend_op = SDL_GPU_BLENDOP_ADD;
        blendState.color_write_mask = SDL_GPU_COLORCOMPONENT_R | SDL_GPU_COLORCOMPONENT_G | SDL_GPU_COLORCOMPONENT_B | SDL_GPU_COLORCOMPONENT_A;
        
        SDL_GPUColorTargetDescription colorTargetDesc;
        colorTargetDesc.format = backendData.initInfo.colorTargetFormat;
        colorTargetDesc.blend_state = blendState;
        
        SDL_GPUGraphicsPipelineTargetInfo targetInfo;
        targetInfo.num_color_targets = 1;
        targetInfo.color_target_descriptions = &colorTargetDesc;
        targetInfo.has_depth_stencil_target = false;
        
        SDL_GPUGraphicsPipelineCreateInfo pipelineCreateInfo;
        pipelineCreateInfo.vertex_shader = backendData.vertexShader;
        pipelineCreateInfo.fragment_shader = backendData.fragmentShader;
        pipelineCreateInfo.vertex_input_state = vertexInputState;
        pipelineCreateInfo.primitive_type = SDL_GPU_PRIMITIVETYPE_TRIANGLELIST;
        pipelineCreateInfo.rasterizer_state = rasterizerState;
        pipelineCreateInfo.multisample_state = multisampleState;
        pipelineCreateInfo.depth_stencil_state = depthStencilState;
        pipelineCreateInfo.target_info = targetInfo;

        graphicsPipeline = SDL_CreateGPUGraphicsPipeline(backendData.initInfo.device, &pipelineCreateInfo);
        if (graphicsPipeline is null)
        {
            logError("Failed to create graphics pipeline");
            return false;
        }
        
        backendData.pipeline = graphicsPipeline;
        
        colorTargetInfo.clear_color = SDL_FColor(0.0f, 0.0f, 0.0f, 0.0f);
        colorTargetInfo.load_op = SDL_GPU_LOADOP_LOAD;
        colorTargetInfo.store_op = SDL_GPU_STOREOP_STORE;
        colorTargetsInfo = &colorTargetInfo;
        numColorTargets = 1;
        depthStencilTargetInfo = null;
        enableDepthTarget = false;
        
        return true;
    }
    
    void createFontTexture()
    {
        ImGuiIO* io = igGetIO();
        char* pixels;
        int width, height;
        int bytesPerPixel;
        
        ImFontAtlas_GetTexDataAsRGBA32(io.Fonts, &pixels, &width, &height, &bytesPerPixel);

        TextureFormat fontTexFormat;
        fontTexFormat.type = SDL_GPU_TEXTURETYPE_2D;
        fontTexFormat.format = SDL_GPU_TEXTUREFORMAT_R8G8B8A8_UNORM;
        fontTexFormat.blockSize = 0;
        fontTexFormat.cubeFaces = CubeFaceBit.None;
        fontTexFormat.numChannels = 4;
        fontTexFormat.pixelSize = 4;

        TextureSize fontTexSize;
        fontTexSize.width = cast(uint)width;
        fontTexSize.height = cast(uint)height;
        fontTexSize.depth = 1;

        TextureBuffer texBuffer;
        texBuffer.format = fontTexFormat;
        texBuffer.size = fontTexSize;
        texBuffer.mipLevels = 1;

        size_t totalBufferSize = fontTexSize.width * fontTexSize.height * fontTexFormat.pixelSize;
        texBuffer.data = (cast(ubyte*)pixels)[0..totalBufferSize];

        TextureCreationOptions options;
        options.generateMipmaps = false;
        options.repeatUV = false;
        options.anisotropicFiltering = false;

        fontTexture = New!Texture(gpu, this);
        fontTexture.create(&texBuffer, &options);

        io.Fonts.TexID = cast(ImTextureID)cast(void*)fontTexture;
    }
    
    void updateBuffers(ImDrawData* drawData)
    {
        uint neededVertexSize = cast(uint)(drawData.TotalVtxCount * ImDrawVert.sizeof);
        uint neededIndexSize = cast(uint)(drawData.TotalIdxCount * ImDrawIdx.sizeof);

        if (neededVertexSize == 0 || neededIndexSize == 0)
            return;

        if (vertexBuffer is null || vertexBufferSize < neededVertexSize)
        {
            if (vertexBuffer)
                SDL_ReleaseGPUBuffer(gpu.device, vertexBuffer);
            
            vertexBufferSize = cast(uint)(neededVertexSize * 1.5f);
            SDL_GPUBufferCreateInfo createInfo;
            createInfo.usage = SDL_GPU_BUFFERUSAGE_VERTEX;
            createInfo.size = vertexBufferSize;
            
            vertexBuffer = SDL_CreateGPUBuffer(gpu.device, &createInfo);
        }

        if (indexBuffer is null || indexBufferSize < neededIndexSize)
        {
            if (indexBuffer) SDL_ReleaseGPUBuffer(gpu.device, indexBuffer);
            
            indexBufferSize = cast(uint)(neededIndexSize * 1.5f);
            SDL_GPUBufferCreateInfo createInfo;
            createInfo.usage = SDL_GPU_BUFFERUSAGE_INDEX;
            createInfo.size = indexBufferSize;
            
            indexBuffer = SDL_CreateGPUBuffer(gpu.device, &createInfo);
        }

        SDL_GPUTransferBufferCreateInfo transferInfo;
        transferInfo.usage = SDL_GPU_TRANSFERBUFFERUSAGE_UPLOAD;
        transferInfo.size = neededVertexSize + neededIndexSize;

        SDL_GPUTransferBuffer* transferBuffer = SDL_CreateGPUTransferBuffer(gpu.device, &transferInfo);
        if (transferBuffer is null) return;

        void* mappedData = SDL_MapGPUTransferBuffer(gpu.device, transferBuffer, false);
        if (mappedData is null)
        {
            SDL_ReleaseGPUTransferBuffer(gpu.device, transferBuffer);
            return;
        }

        ubyte* vtxDst = cast(ubyte*)mappedData;
        ubyte* idxDst = cast(ubyte*)(cast(size_t)mappedData + neededVertexSize);

        foreach (int n; 0..drawData.CmdListsCount)
        {
            ImDrawList* cmdList = drawData.CmdLists[n];
            
            uint vtxSize = cast(uint)(cmdList.VtxBuffer.Size * ImDrawVert.sizeof);
            memcpy(vtxDst, cmdList.VtxBuffer.Data, vtxSize);
            vtxDst += vtxSize;

            uint idxSize = cast(uint)(cmdList.IdxBuffer.Size * ImDrawIdx.sizeof);
            memcpy(idxDst, cmdList.IdxBuffer.Data, idxSize);
            idxDst += idxSize;
        }

        SDL_UnmapGPUTransferBuffer(gpu.device, transferBuffer);
        
        SDL_GPUCopyPass* copyPass = SDL_BeginGPUCopyPass(renderer.commandBuffer);
        if (copyPass is null)
        {
            SDL_ReleaseGPUTransferBuffer(gpu.device, transferBuffer);
            return;
        }
        else
        {
            SDL_GPUTransferBufferLocation vtxSource;
            vtxSource.transfer_buffer = transferBuffer;
            vtxSource.offset = 0;

            SDL_GPUBufferRegion vtxDest;
            vtxDest.buffer = vertexBuffer;
            vtxDest.offset = 0;
            vtxDest.size = neededVertexSize;

            SDL_UploadToGPUBuffer(copyPass, &vtxSource, &vtxDest, false);

            SDL_GPUTransferBufferLocation idxSource;
            idxSource.transfer_buffer = transferBuffer;
            idxSource.offset = neededVertexSize;

            SDL_GPUBufferRegion idxDest;
            idxDest.buffer = indexBuffer;
            idxDest.offset = 0;
            idxDest.size = neededIndexSize;

            SDL_UploadToGPUBuffer(copyPass, &idxSource, &idxDest, false);
            
            SDL_EndGPUCopyPass(copyPass);
        }

        SDL_ReleaseGPUTransferBuffer(gpu.device, transferBuffer);
        
        backendData.mainWindowFrameData = ImGui_ImplSDLGPU3_FrameData(
            vertexBuffer,
            vertexBufferSize,
            indexBuffer,
            indexBufferSize);
    }
    
   public:
    override void render(GraphicsState* state)
    {
        ImDrawData* drawData = igGetDrawData();
        
        if (drawData is null || drawData.CmdListsCount == 0)
            return;
        
        updateBuffers(drawData);
        
        colorTargetInfo.texture = renderer.swapchainTexture;
        
        debug SDL_PushGPUDebugGroup(renderer.commandBuffer, "IMGUI");
        beginPass();
        
        bindVertexBuffer(0, vertexBuffer);
        bindIndexBuffer(indexBuffer, SDL_GPU_INDEXELEMENTSIZE_16BIT);
        
        uint globalVtxOffset = 0;
        uint globalIdxOffset = 0;
        ImVec2 clipOff = drawData.DisplayPos;
        
        float left = clipOff.x;
        float right = clipOff.x + drawData.DisplaySize.x;
        float top = clipOff.y;
        float bottom = clipOff.y + drawData.DisplaySize.y;
        
        imguiShader.scaling.x = 2.0f / (right - left);
        imguiShader.scaling.y = 2.0f / (bottom - top);
        imguiShader.position.x = (right + left) / (left - right);
        imguiShader.position.y = (bottom + top) / (top - bottom);
        
        foreach (int n; 0..drawData.CmdListsCount)
        {
            ImDrawList* cmdList = drawData.CmdLists[n];
            
            foreach (int cmdIdx; 0..cmdList.CmdBuffer.Size)
            {
                ImDrawCmd* pcmd = &cmdList.CmdBuffer.Data[cmdIdx];
                if (pcmd.UserCallback is null)
                {
                    SDL_Rect clipRect;
                    clipRect.x = cast(int)(pcmd.ClipRect.x - clipOff.x);
                    clipRect.y = cast(int)(pcmd.ClipRect.y - clipOff.y);
                    clipRect.w = cast(int)(pcmd.ClipRect.z - pcmd.ClipRect.x);
                    clipRect.h = cast(int)(pcmd.ClipRect.w - pcmd.ClipRect.y);
                    SDL_SetGPUScissor(renderPass, &clipRect);
                    
                    Texture tex = fontTexture;
                    if (pcmd.TextureId !is null)
                    {
                        Texture customTexture = cast(Texture)pcmd.TextureId;
                        if (customTexture !is null)
                            tex = customTexture;
                    }
                    
                    imguiShader.texture = tex;
                    imguiShader.bindParameters(state);
                    
                    backendData.currentSampler = tex.sampler;

                    drawIndexedPrimitives(pcmd.ElemCount, 1, pcmd.IdxOffset + globalIdxOffset, pcmd.VtxOffset + globalVtxOffset, 0);
                }
            }

            globalVtxOffset += cmdList.VtxBuffer.Size;
            globalIdxOffset += cmdList.IdxBuffer.Size;
        }
        
        endPass();
        debug SDL_PopGPUDebugGroup(renderer.commandBuffer);
    }
}
