/*
Copyright (c) 2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module dagon.ext.imgui;

public import bindbc.imgui;

import dlib.core.memory;
import dlib.text.str;

import dagon.core.sdl3;
import dagon.core.event;
import dagon.core.time;
import dagon.core.application;
import dagon.render.renderer;
import dagon.ext.imgui.backend;

private ImGuiKey sdl3KeyToImGuiKey(SDL_Keycode key)
{
    switch (key)
    {
        case SDLK_TAB:       return ImGuiKey.Tab;
        case SDLK_LEFT:      return ImGuiKey.LeftArrow;
        case SDLK_RIGHT:     return ImGuiKey.RightArrow;
        case SDLK_UP:        return ImGuiKey.UpArrow;
        case SDLK_DOWN:      return ImGuiKey.DownArrow;
        case SDLK_PAGEUP:    return ImGuiKey.PageUp;
        case SDLK_PAGEDOWN:  return ImGuiKey.PageDown;
        case SDLK_HOME:      return ImGuiKey.Home;
        case SDLK_END:       return ImGuiKey.End;
        case SDLK_INSERT:    return ImGuiKey.Insert;
        case SDLK_DELETE:    return ImGuiKey.Delete;
        case SDLK_BACKSPACE: return ImGuiKey.Backspace;
        case SDLK_SPACE:     return ImGuiKey.Space;
        case SDLK_RETURN:    return ImGuiKey.Enter;
        case SDLK_ESCAPE:    return ImGuiKey.Escape;
        case SDLK_A:         return ImGuiKey.A;
        case SDLK_C:         return ImGuiKey.C;
        case SDLK_V:         return ImGuiKey.V;
        case SDLK_X:         return ImGuiKey.X;
        case SDLK_Y:         return ImGuiKey.Y;
        case SDLK_Z:         return ImGuiKey.Z;
        // TODO: other keys
        default:             return ImGuiKey.None;
    }
}

class ImGui: EventListener
{
    Application application;
    ImGuiContext* igContext;
    ImGuiIO* io;
    
    ImFont* font;
    
    const(ImWchar)[] fontRanges = [
        0x0020, 0x00FF, // Basic Latin + Latin Supplement
        0x0370, 0x03FF, // Greek
        0x0400, 0x044F, // Cyrillic
        0
    ];
    
    bool active = true;
    
    ImGuiPass imGuiPass;
    
    this(Application application, Renderer renderer, string fontPath = "", uint fontSize = 16)
    {
        super(application.eventManager, application);
        this.application = application;
        
        igContext = igCreateContext(null);
        igSetCurrentContext(igContext);
        io = igGetIO();
        io.BackendPlatformName = "imgui_impl_dagon_sdl3";
        io.ConfigFlags |= ImGuiConfigFlags.DockingEnable;
        io.ConfigWindowsMoveFromTitleBarOnly = true;
        io.FontGlobalScale = 1.0f / application.pixelRatio;

        if (fontPath.length)
        {
            String path = fontPath;
            font = ImFontAtlas_AddFontFromFileTTF(io.Fonts, path.ptr, cast(uint)(fontSize * application.pixelRatio), null, fontRanges.ptr);
            path.free();
        }
        
        igStyleColorsDark(null);
        
        imGuiPass = New!ImGuiPass(renderer);
    }
    
    ~this()
    {
        if (igContext)
        {
            igDestroyContext(igContext);
            igContext = null;
        }
    }
    
    void reset()
    {
        igClearActiveID();
        ImGuiIO_ClearInputKeys(io);
        
        io.ConfigInputTrickleEventQueue = false; 
        
        for (int i = 0; i < 5; i++)
            io.MouseDown[i] = false;
        
        for (int i = 0; i < ImGuiKey.COUNT; i++)
            io.KeysDown[i] = false;
        
        for (int i = 0; i < ImGuiNavInput.COUNT; i++)
            io.NavInputs[i] = 0.0f;
        
        ImGuiContext* ctx = igGetCurrentContext();
        ctx.NavId = 0;
        ctx.NavFocusScopeId = 0;
        ctx.NavActivateId = 0;
        ctx.NavActivateDownId = 0;
        ctx.NavActivatePressedId = 0;
        ctx.NavActivateInputId = 0;
        ctx.NavJustMovedToId = 0;
        ctx.ActiveIdSource = ImGuiInputSource.None;
        
        igSetWindowFocus_Str(null);
    }
    
    override void onResize(int width, int height)
    {
        io.DisplaySize = ImVec2(eventManager.windowWidth, eventManager.windowHeight);
    }
    
    void onProcessEvent(SDL_Event* event)
    {
        if (!active || event is null)
            return;
        
        switch(event.type)
        {
            case SDL_EVENT_MOUSE_MOTION:
                ImGuiIO_AddMousePosEvent(io, event.motion.x, event.motion.y);
                break;
                
            case SDL_EVENT_MOUSE_BUTTON_DOWN:
            case SDL_EVENT_MOUSE_BUTTON_UP:
                int button = -1;
                if (event.button.button == SDL_BUTTON_LEFT) button = 0;
                if (event.button.button == SDL_BUTTON_RIGHT) button = 1;
                if (event.button.button == SDL_BUTTON_MIDDLE) button = 2;
                
                if (button != -1)
                {
                    ImGuiIO_AddMouseButtonEvent(io, button, event.type == SDL_EVENT_MOUSE_BUTTON_DOWN);
                }
                break;
                
            case SDL_EVENT_MOUSE_WHEEL:
                ImGuiIO_AddMouseWheelEvent(io, event.wheel.x, event.wheel.y);
                break;
                
            case SDL_EVENT_TEXT_INPUT:
                ImGuiIO_AddInputCharactersUTF8(io, event.text.text);
                break;
                
            case SDL_EVENT_KEY_DOWN:
            case SDL_EVENT_KEY_UP:
                ImGuiIO_AddKeyEvent(io, ImGuiKey.ModCtrl, (event.key.mod & SDL_KMOD_CTRL) != 0);
                ImGuiIO_AddKeyEvent(io, ImGuiKey.ModShift, (event.key.mod & SDL_KMOD_SHIFT) != 0);
                ImGuiIO_AddKeyEvent(io, ImGuiKey.ModAlt, (event.key.mod & SDL_KMOD_ALT) != 0);

                ImGuiKey imguiKey = sdl3KeyToImGuiKey(event.key.key);
                if (imguiKey != ImGuiKey.None)
                {
                    ImGuiIO_AddKeyEvent(io, imguiKey, event.type == SDL_EVENT_KEY_DOWN);
                }
                break;
                
            default:
                break;
        }
    }
    
    bool capturesMouse() @property
    {
        return active && io.WantCaptureMouse;
    }
    
    bool capturesKeyboard() @property
    {
        return active && io.WantCaptureKeyboard;
    }
    
    void onUpdate(Time t)
    {
    }
    
    void update(Time t)
    {
        if (!active)
            return;
        
        imGuiPass.active = active;
        
        processEvents();
        
        io.DisplaySize = ImVec2(cast(float)application.drawableWidth, cast(float)application.drawableHeight);
        //io.DisplayFramebufferScale = ImVec2(application.pixelRatio, application.pixelRatio);
        io.DeltaTime = cast(float)t.delta;
        
        if (io.WantTextInput)
        {
            if (!SDL_TextInputActive(application.window))
                SDL_StartTextInput(application.window);
        }
        else
        {
            if (SDL_TextInputActive(application.window))
                SDL_StopTextInput(application.window);
        }
        
        igNewFrame();
        
        onUpdate(t);
        
        igRender();
    }
}
