/*
Copyright (c) 2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

/**
 * Helper module that publicly imports Assimp binding.
 *
 * Copyright: Timur Gafarov 2026.
 * License: $(LINK2 https://boost.org/LICENSE_1_0.txt, Boost License 1.0).
 * Authors: Timur Gafarov
 */
module dagon.core.assimp;

import std.conv;
import std.string;

import dlib.math.matrix;
import dlib.image.color;

import bindbc.loader;
import loader = bindbc.loader.sharedlib;
public import bindbc.assimp;

import dagon.core.logger;

/**
 * Loads Assimp library.
 *
 * Params:
 *   path = optional path to the library.
 *
 * Returns:
 *   API support enum for the loaded library.
 */
AssimpSupport loadAssimp(string path = "")
{
    AssimpSupport assimpSupport;
    if (path.length)
        assimpSupport = bindbc.assimp.loadAssimp(toStringz(path));
    else
        assimpSupport = bindbc.assimp.loadAssimp();
    
    if (loader.errors.length)
    {
        foreach(info; loader.errors)
        {
            logError(to!string(info.error), ": ", to!string(info.message));
        }
    }
    
    return assimpSupport;
}

///
Color4f fromAssimpColor(aiColor4D col)
{
    return Color4f(col.r, col.g, col.b, col.a);
}

///
Matrix4x4f fromAssimpMatrix(aiMatrix4x4 m)
{
    return matrixf(
        m.a1, m.a2, m.a3, m.a4,
        m.b1, m.b2, m.b3, m.b4,
        m.c1, m.c2, m.c3, m.c4,
        m.d1, m.d2, m.d3, m.d4
    );
}
