/*
Copyright (c) 2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

/**
 * GPU wrapper class.
 *
 * Description:
 * The `dagon.core.gpu` module defines the `GPU` class that wraps
 * `SDL_GPUDevice` management and GPU buffer creation API.
 *
 * Copyright: Timur Gafarov 2026.
 * License: $(LINK2 https://boost.org/LICENSE_1_0.txt, Boost License 1.0).
 * Authors: Timur Gafarov
 */
module dagon.core.gpu;

import std.conv;
import std.string;

import dlib.core.ownership;

import dagon.core.application;
import dagon.core.sdl3;
import dagon.core.logger;

/// Supported GPU backends. Only Vulkan is supported at the moment.
enum GPUBackend
{
    Vulkan = 0
}

/**
 * `SDL_GPUDevice` wrapper class.
 *
 * This class provides an abstraction layer for SDL 3.0's GPU device management,
 * including device initialization, buffer creation, and resource management.
 * It handles the lifecycle of GPU resources and provides convenient methods for
 * common GPU operations like buffer uploads and device querying.
 */
class GPU: Owner
{
    /// Reference to the Application instance.
    Application application;
    
    /// Pointer to the underlying SDL GPU device.
    SDL_GPUDevice* device;
    
    /// The GPU backend currently in use (Vulkan).
    GPUBackend backend = GPUBackend.Vulkan;
    
    /// Human-readable name of the GPU device.
    string deviceName = "Unknown";
    
    /// Name of the GPU driver.
    string deviceDriver = "Unknown";
    
    /// Version string of the GPU driver
    string deviceDriverVersion = "";
    
    /// The texture format used by the swapchain.
    SDL_GPUTextureFormat swapchainTextureFormat;
    
    /// Default texture for fallback sampling operations.
    SDL_GPUTexture* defaultTexture;
    
    /// Default sampler for fallback sampling operations.
    SDL_GPUSampler* defaultSampler;
    
    /// Whether the GPU device supports HDR extended linear swapchain composition.
    bool hdrExtendedLinearSwapchainSupported = false;
    
    /// Whether HDR swapchain is currently enabled.
    bool hdrSwapchain = false;
    
    /**
     * Constructs a GPU device wrapper for the given application.
     *
     * Initializes the SDL GPU device, claims the application window for GPU rendering,
     * and creates default texture and sampler resources. Queries device information
     * such as name, driver, and version. Also checks for and enables HDR swapchain
     * support if available and requested.
     * Terminates with an error if GPU device creation fails or the backend is unsupported.
     *
     * Params:
     *   application = The parent Application instance.
     *   owner       = Optional owner for memory management.
     */
    this(Application application, Owner owner = null)
    {
        super(owner);
        this.application = application;
        if (application.window)
        {
            string backendStr;
            if (backend == GPUBackend.Vulkan)
                backendStr = "vulkan";
            else
                exitWithError("Unsupported GPU API backend: " ~ backend.to!string);
            
            device = SDL_CreateGPUDevice(SDL_GPU_SHADERFORMAT_SPIRV, application.gpuDebug, toStringz(backendStr));
            if (device is null)
                exitWithError("SDL_CreateGPUDevice failed: " ~ to!string(SDL_GetError()));
            
            SDL_ClaimWindowForGPUDevice(device, application.window);
            
            SDL_PropertiesID gpuProps = SDL_GetGPUDeviceProperties(device);
            deviceName = SDL_GetStringProperty(gpuProps, SDL_PROP_GPU_DEVICE_NAME_STRING, "Unknown").to!string;
            deviceDriver = SDL_GetStringProperty(gpuProps, SDL_PROP_GPU_DEVICE_DRIVER_NAME_STRING, "Unknown").to!string;
            deviceDriverVersion = SDL_GetStringProperty(gpuProps, SDL_PROP_GPU_DEVICE_DRIVER_VERSION_STRING, "Unknown").to!string;
            
            if (application.hdrOutputSupport && application.hdrOutput)
            {
                hdrExtendedLinearSwapchainSupported = SDL_WindowSupportsGPUSwapchainComposition(device, application.window, SDL_GPU_SWAPCHAINCOMPOSITION_HDR_EXTENDED_LINEAR);
                if (hdrExtendedLinearSwapchainSupported)
                {
                    SDL_SetGPUSwapchainParameters(device, application.window, SDL_GPU_SWAPCHAINCOMPOSITION_HDR_EXTENDED_LINEAR, SDL_GPU_PRESENTMODE_VSYNC);
                    hdrSwapchain = application.hdrOutputSupport && application.hdrOutput;
                }
            }
            
            swapchainTextureFormat = SDL_GetGPUSwapchainTextureFormat(device, application.window);
            
            SDL_GPUTextureCreateInfo textureCreateInfo = {
                type: SDL_GPU_TEXTURETYPE_2D,
                width: 32,
                height: 32,
                layer_count_or_depth: 1,
                format: SDL_GPU_TEXTUREFORMAT_R8_UNORM,
                usage: SDL_GPU_TEXTUREUSAGE_SAMPLER,
                num_levels: 1,
                sample_count: SDL_GPU_SAMPLECOUNT_1
            };
            defaultTexture = SDL_CreateGPUTexture(device, &textureCreateInfo);
            
            SDL_GPUSamplerCreateInfo samplerCreateInfo = {
                min_filter: SDL_GPU_FILTER_NEAREST,
                mag_filter: SDL_GPU_FILTER_NEAREST,
                mipmap_mode: SDL_GPU_SAMPLERMIPMAPMODE_NEAREST,
                address_mode_u: SDL_GPU_SAMPLERADDRESSMODE_CLAMP_TO_EDGE,
                address_mode_v: SDL_GPU_SAMPLERADDRESSMODE_CLAMP_TO_EDGE,
                address_mode_w: SDL_GPU_SAMPLERADDRESSMODE_CLAMP_TO_EDGE,
                mip_lod_bias: 0.0f,
                max_anisotropy: 1.0f,
                min_lod: 0.0f,
                max_lod: 0.0f,
                enable_anisotropy: false,
                enable_compare: false,
                compare_op: SDL_GPU_COMPAREOP_ALWAYS
            };
            defaultSampler = SDL_CreateGPUSampler(device, &samplerCreateInfo);
        }
    }
    
    /**
     * Destructor that releases all GPU resources.
     */
    ~this()
    {
        if (defaultTexture)
            SDL_ReleaseGPUTexture(device, defaultTexture);
        
        if (defaultSampler)
            SDL_ReleaseGPUSampler(device, defaultSampler);
        
        if (device)
        {
            SDL_DestroyGPUDevice(device);
            device = null;
        }
    }
    
    /**
     * Creates a GPU buffer with the specified usage flags and size.
     *
     * Allocates GPU device memory for a buffer that can be used for various purposes
     * such as vertex data, index data, or uniform buffers.
     *
     * Params:
     *   usage = SDL GPU buffer usage flags indicating the buffer's purpose.
     *   size = Size of the buffer in bytes.
     *
     * Returns:
     *   Pointer to the created SDL GPU buffer, or null if device is not initialized.
     */
    SDL_GPUBuffer* createBuffer(SDL_GPUBufferUsageFlags usage, size_t size)
    {
        if (device is null)
            return null;
        SDL_GPUBufferCreateInfo info;
        info.size = cast(uint)size;
        info.usage = usage;
        return SDL_CreateGPUBuffer(device, &info);
    }

    /**
     * Uploads data to a GPU buffer from CPU memory.
     *
     * Creates a transfer buffer, copies the provided CPU data into it, and then
     * submits a GPU copy operation to transfer the data to the target GPU buffer.
     * The transfer buffer is released after the operation completes.
     *
     * Params:
     *   ptr = Pointer to the CPU memory containing the data to upload.
     *   size = Size of the data in bytes.
     *   target = Pointer to the target GPU buffer to upload to.
     *
     * Returns:
     *   `true` if the upload was successful, `false` if device is not initialized.
     */
    bool uploadBuffer(void* ptr, size_t size, SDL_GPUBuffer* target)
    {
        if (device is null)
            return false;
        
        SDL_GPUTransferBufferCreateInfo tinfo;
        tinfo.size = cast(uint)size;
        tinfo.usage = SDL_GPU_TRANSFERBUFFERUSAGE_UPLOAD;
        auto tBuf = SDL_CreateGPUTransferBuffer(device, &tinfo);

        void* map = SDL_MapGPUTransferBuffer(device, tBuf, false);
        SDL_memcpy(map, ptr, size);
        SDL_UnmapGPUTransferBuffer(device, tBuf);

        auto cmd = SDL_AcquireGPUCommandBuffer(device);
        auto copy = SDL_BeginGPUCopyPass(cmd);
        
        SDL_GPUTransferBufferLocation src = { transfer_buffer: tBuf, offset: 0 };
        SDL_GPUBufferRegion dst = { buffer: target, offset: 0, size: cast(uint)size };
        
        SDL_UploadToGPUBuffer(copy, &src, &dst, true);
        SDL_EndGPUCopyPass(copy);
        SDL_SubmitGPUCommandBuffer(cmd);
        SDL_ReleaseGPUTransferBuffer(device, tBuf);
        
        return true;
    }
    
    /**
     * Releases a GPU buffer and frees its resources.
     *
     * Properly cleans up the specified GPU buffer. Should be called when the buffer
     * is no longer needed to prevent resource leaks.
     *
     * Params:
     *   target = Pointer to the GPU buffer to release.
     */
    void releaseBuffer(SDL_GPUBuffer* target)
    {
        if (device is null)
            return;
        
        SDL_ReleaseGPUBuffer(device, target);
    }
}
