/*
Copyright (c) 2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module dagon.core.hashmap;

import core.atomic;
import std.traits;

import dlib.core.memory;
import dlib.core.ownership;

import dagon.core.xxhash64;

enum XXHASH64_SEED = 42;

class FlatHashMap: Owner
{
   protected:
    struct Bucket
    {
        ulong key;   // xxHash64 (0 = empty)
        void* value; // Arbitrary raw pointer
    }

    Bucket[] buckets;
    size_t size;
    size_t capacity;

    enum size_t DEFAULT_CAPACITY = 512;
    enum float LOAD_FACTOR = 0.7f;

   public:
    this(Owner owner)
    {
        super(owner);
        capacity = DEFAULT_CAPACITY;
        buckets = New!(Bucket[])(capacity);
    }

    ~this()
    {
        if (buckets.ptr)
            Delete(buckets);
    }

    /// Insert. Returns true if new entry is inserted, false if it already exists.
    bool set(ulong key, void* value, out void* existingValue)
    {
        if (key == 0) key = 1;

        if (cast(float)size / cast(float)capacity >= LOAD_FACTOR)
        {
            resize(capacity * 2);
        }

        size_t index = cast(size_t)(key & (capacity - 1));

        while(true)
        {
            ulong currentKey = buckets[index].key;

            if (currentKey == 0) 
            {
                buckets[index].value = value;
                buckets[index].key = key;
                size++;
                existingValue = value;
                return true;
            }

            if (currentKey == key) 
            {
                existingValue = buckets[index].value;
                return false;
            }

            index = (index + 1) & (capacity - 1);
        }
    }

    ///
    bool set(string key, Object value)
    {
        void* existingValue;
        return set(xxHash64(key, 42), cast(void*)value, existingValue);
    }

    ///
    bool set(string key, void* value)
    {
        void* existingValue;
        return set(xxHash64(key, 42), value, existingValue);
    }

    ///
    bool set(T)(string key, T* value)
    {
        void* existingValue;
        return set(xxHash64(key, 42), cast(void*)value, existingValue);
    }

    ///
    void* get(ulong key)
    {
        if (key == 0) key = 1;

        size_t index = cast(size_t)(key & (capacity - 1));
        size_t start = index;

        while(true)
        {
            ulong currentKey = buckets[index].key;

            if (currentKey == key)
                return buckets[index].value;
            if (currentKey == 0)
                return null;

            index = (index + 1) & (capacity - 1);
            if (index == start)
                break;
        }
        return null;
    }
    
    ///
    T get(T)(string key) if (is(T == class))
    {
        return cast(T)get(xxHash64(key, 42));
    }

   protected:
    void resize(size_t newCapacity)
    {
        auto oldBuckets = buckets;
        
        auto newBuckets = New!(Bucket[])(newCapacity);
        size_t newSize = 0;

        foreach(ref b; oldBuckets)
        {
            if (b.key != 0)
            {
                size_t index = cast(size_t)(b.key & (newCapacity - 1));
                while (newBuckets[index].key != 0)
                {
                    index = (index + 1) & (newCapacity - 1);
                }
                newBuckets[index].key = b.key;
                newBuckets[index].value = b.value;
                newSize++;
            }
        }

        capacity = newCapacity;
        size = newSize;
        buckets = newBuckets;

        Delete(oldBuckets);
    }
}
