/*
Copyright (c) 2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module dagon.resource.assetmanager;

import core.atomic;

import dlib.core.memory;
import dlib.core.ownership;
import dlib.core.thread;
import dlib.container.dict;
import dlib.filesystem.filesystem;

import dagon.core.application;
import dagon.core.logger;
import dagon.core.gpu;
import dagon.core.hashmap;
import dagon.graphics.texture;
import dagon.graphics.lut;
import dagon.resource.asset;
import dagon.resource.image;
import dagon.resource.texture;

import gscript;

///
struct LoadingStatus
{
    ulong assetID;
    uint index;
    uint numAssets;
    float progress;
    bool ready;
}

///
class AssetManager: Owner, GsObject
{
    ///
    Application application;
    
    /// Default options for converting loaded image data.
    ImageConversionOptions defaultImageConversionOptions;
    
    /// Default options for creating new textures.
    TextureCreationOptions defaultTextureCreationOptions;
    
    /// Hash map of registered assets.
    FlatHashMap!Asset assets;
    
    ///
    uint numAssets = 0;
    
    ///
    Thread loadingThread;
    
    ///
    protected LoadingStatus[2] _loadingStatus;
    protected shared uint loadingStatusActiveIndex = 0;
    
    /// GScript dynamic properties attached to this world instance.
    Dict!(GsDynamic, string) gsProperties;
    
    ///
    this(Application application, Owner owner)
    {
        super(owner);
        
        this.application = application;
        
        // TODO: init defaultImageConversionOptions and defaultTextureCreationOptions from application settings
        
        defaultImageConversionOptions.width = 0;
        defaultImageConversionOptions.height = 0;
        defaultImageConversionOptions.depth = 1;
        defaultImageConversionOptions.compressionFormat = TextureCompressionFormat.None;
        defaultImageConversionOptions.lutFormat = LUTFormat.Undefined;
        defaultImageConversionOptions.hint = 0;
        
        defaultTextureCreationOptions.generateMipmaps = true;
        defaultTextureCreationOptions.repeatUV = true;
        defaultTextureCreationOptions.bilinearFiltering = true;
        defaultTextureCreationOptions.anisotropicFiltering = true;
        defaultTextureCreationOptions.writeable = false;
        
        assets = New!(FlatHashMap!Asset)(this);
        
        loadingThread = New!Thread(&loadSync);
        
        _loadingStatus[0].assetID = 0;
        _loadingStatus[0].index = 0;
        _loadingStatus[0].numAssets = 0;
        _loadingStatus[0].progress = 0.0f;
        _loadingStatus[0].ready = false;
        
        _loadingStatus[1].assetID = 0;
        _loadingStatus[1].index = 0;
        _loadingStatus[1].numAssets = 0;
        _loadingStatus[1].progress = 0.0f;
        _loadingStatus[1].ready = false;
        
        gsProperties = dict!(GsDynamic, string);
    }
    
    /// Releases world resources and script properties.
    ~this()
    {
        Delete(loadingThread);
        Delete(gsProperties);
    }
    
    /// Returns a registered asset by ID, or null if it doesn't exist.
    Asset getAsset(ulong id)
    {
        return assets.get(id);
    }
    
    /// Returns a registered asset under the given name, or null if it doesn't exist.
    Asset getAsset(string name)
    {
        return assets[name];
    }
    
    /// Checks if an asset is registered under a given name.
    bool assetExists(string name)
    {
        Asset existingAsset = assets[name];
        return (existingAsset !is null);
    }
    
    /// Registers an asset under a given name and returns its ID.
    ulong addAsset(Asset asset, string name)
    {
        //assets[name] = asset;
        ulong id = xxHash64(name, XXHASH64_SEED);
        Asset existingAsset;
        assets.set(id, asset, existingAsset);
        numAssets++;
        return id;
    }
    
    /// Loads all registered assets in the current thread.
    void loadSync()
    {
        if (numAssets == 0)
            return;
        
        uint index = 0;
        float progress = 0.0f;
        float progressStep = 1.0f / cast(float)numAssets;
        
        bool isFirst = true;

        foreach(ulong id, Asset asset; assets)
        {
            //logDebug("Loading asset ", asset.filename, "...");
            if (isFirst)
            {
                isFirst = false;
                updateLoadingStatus(id, index, progress, false);
            }
            loadAsset(asset);
            index++;
            progress += progressStep;
            updateLoadingStatus(id, index, progress, index >= numAssets);
        }
    }
    
    /// Loads all registered assets in the parallel thread, returns immediately.
    void loadAsync()
    {
        loadingThread.start();
    }
    
    protected void updateLoadingStatus(ulong id, uint index, float progress, bool ready)
    {
        uint writeIdx = (atomicLoad(loadingStatusActiveIndex) == 0) ? 1 : 0;
        
        auto buf = cast(LoadingStatus*)&_loadingStatus[writeIdx];
        buf.assetID = id;
        buf.index = index;
        buf.numAssets = numAssets;
        buf.progress = progress;
        buf.ready = ready;
        
        atomicStore(loadingStatusActiveIndex, writeIdx);
    }
    
    /// Returns current loading status.
    LoadingStatus loadingStatus() @property
    {
        uint readIdx = atomicLoad(loadingStatusActiveIndex);
        return *(cast(LoadingStatus*)&_loadingStatus[readIdx]);
    }
    
    /**
     * Immediately loads a texture asset from a file using provided conversion and creation settings.
     *
     * Params:
     *   filename = Virtual path of the texture file to load.
     *   conversionOptions = Image conversion settings to apply.
     *   creationOptions = Texture creation settings to use.
     *   cache = Whether the asset should be cached.
     *
     * Returns: The loaded texture asset instance.
     */
    TextureAsset loadTexture(string filename, ImageConversionOptions* conversionOptions, TextureCreationOptions* creationOptions, bool cache = true)
    {
        TextureAsset asset = New!TextureAsset(application.gpu, filename, this);
        asset.conversionOptions = *conversionOptions;
        asset.creationOptions = *creationOptions;
        asset.cache = cache;
        if (application.fileExists(filename))
            loadAsset(asset);
        else
            logError("Can\'t find file ", filename);
        return asset;
    }
    
    /**
     * Immediately loads a texture asset from a file using default conversion and creation settings.
     *
     * Params:
     *   filename = Virtual path of the texture file to load.
     *   cache = Whether the texture asset should be cached.
     *
     * Returns: The loaded texture asset instance.
     */
    TextureAsset loadTexture(string filename, bool cache = true)
    {
        return loadTexture(filename, &defaultImageConversionOptions, &defaultTextureCreationOptions, cache);
    }
    
    /**
     * Immediately loads the given asset.
     *
     * Params:
     *   asset = The asset object to load.
     *   filename = Virtual path of the source file.
     *
     * Returns: true if loading succeeded; otherwise false.
     */
    bool loadAsset(Asset asset)
    {
        bool res = false;
        FileStat s;
        if (application.vfs.stat(asset.filename, s))
        {
            auto istrm = application.vfs.openForInput(asset.filename);
            res = asset.load(istrm, application.vfs);
            Delete(istrm);
        }
        else
            logError("Can\'t find file ", asset.filename);
        return res;
    }
    
    /**
     * Creates and immediately loads a new asset of type `T` from the specified file.
     *
     * Params:
     *   filename = Virtual path of the asset file.
     *
     * Returns: A loaded asset instance of type `T`.
     */
    T loadAsset(T)(string filename)
    {
        T asset = New!T(application.gpu, filename, this);
        loadAsset(asset);
        return asset;
    }
    
    /**
     * Returns a GScript dynamic property for the specified key.
     *
     * Params:
     *   key = The property name to retrieve.
     *
     * Returns: The property value, or an empty `GsDynamic` if not found.
     */
    GsDynamic get(string key)
    {
        switch(key)
        {
            default:
                auto v = key in gsProperties;
                if (v)
                    return *v;
                else
                    return GsDynamic();
        }
    }
    
    /**
     * Sets a GScript dynamic property value for the specified key.
     *
     * Params:
     *   key = The property name to store.
     *   value = The dynamic value to assign.
     */
    void set(string key, GsDynamic value)
    {
        gsProperties[key] = value;
    }
    
    /**
     * Checks whether a GScript dynamic property exists for the specified key.
     *
     * Params:
     *   key = The property name to check.
     *
     * Returns: True if the property exists.
     */
    bool contains(string key)
    {
        switch(key)
        {
            default:
                if ((key in gsProperties) !is null)
                    return true;
                else
                    return false;
        }
    }
    
    /// Prototype assignment for GScript object compatibility (no-op).
    void setPrototype(GsObject obj)
    {
        // No-op
    }
}
