/*
Copyright (c) 2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module dagon.resource.daf;

import std.stdio;
import std.path;

import dlib.core.memory;
import dlib.core.ownership;
import dlib.core.stream;
import dlib.image.color;
import dlib.image.io.utils;
import dlib.math.vector;
import dlib.math.quaternion;
import dlib.container.array;
import dlib.filesystem.filesystem;

import dagon.core.logger;
import dagon.core.time;
import dagon.core.gpu;
import dagon.graphics.drawable;
import dagon.graphics.state;
import dagon.graphics.entity;
import dagon.graphics.mesh;
import dagon.graphics.material;
import dagon.resource.asset;
import dagon.resource.texture;

struct DAFHeader
{
    uint formatVersion;
    uint flags;
    uint fileSize;
    uint chunkTableOffset;
    uint chunkCount;
    uint stringTableOffset;
    uint stringTableSize;
    uint buffersOffset;
    uint buffersSize;
}

enum DAFChunkType: uint
{
    Entities = 0,
    Meshes = 1,
    Materials = 2,
    Skeletons = 3,
    Poses = 4,
    PoseTables = 5
}

struct DAFChunk
{
    DAFChunkType type;
    uint offset;
    uint count;
    uint stride;
}

struct DAFString
{
    uint offset;
    uint size;
}

struct DAFEntity
{
    DAFString name;
    uint classList;
    uint numClasses;
    uint flags;
    int parent;
    Vector3f position;
    Quaternionf rotation;
    Vector3f scaling;
    int mesh;
    int poseTable;
    uint userDataBuffer;
    uint userDataSize;
};

struct DAFMesh
{
    DAFString name;
    uint classList;
    uint numClasses;
    uint flags;
    uint vertexBuffer;
    uint normalBuffer;
    uint texcoordBuffer;
    uint bonesBuffer;
    uint boneWeightsBuffer;
    uint numVertices;
    uint indicesBuffer;
    uint numTriangles;
    uint faceGroupBuffer;
    uint numFaceGroups;
    uint userDataBuffer;
    uint userDataSize;
}

struct DAFFaceGroup
{
    int material;
    uint firstTriangle;
    uint numTriangles;
}

struct DAFMaterial
{
    DAFString name;
    uint classList;
    uint numClasses;
    uint flags;
    Color4f baseColor;
    float roughness;
    float metallic;
    Color4f emissionColor;
    float emissionEnergy;
    float ior;
    float iorLevel;
    float subsurfaceScattering;
    float opacity;
    float alphaClipThreshold;
    uint shadeless;
    BlendMode blendMode;
    int baseColorTexture;
    int normalTexture;
    int heightTexture;
    int roughnessMetallicTexture;
    int emissionTexture;
    uint userDataBuffer;
    uint userDataSize;
}

enum DAFTextureSemantic: uint
{
    Unspecified = 0,
    BaseColor = 1,
    Normal = 2,
    Height = 3,
    RoughnessMetallic = 4,
    Emission = 5
}

enum DAFTextureFilter: uint
{
    Nearest = 0,
    Linear = 1
}

struct DAFTexture
{
    DAFString filename;
    uint classList;
    uint numClasses;
    uint flags;
    DAFTextureFilter minFilter;
    DAFTextureFilter magFilter;
    DAFTextureFilter mipmapMode;
    DAFTextureSemantic semantic;
    uint userDataBuffer;
    uint userDataSize;
}

version = DAFDebug;

class DagonAsset: Asset
{
    ///
    ubyte[] data;
    
    ///
    Entity rootEntity;
    
    ///
    Array!Entity entities;
    
    ///
    Array!Mesh meshes;
    
    ///
    Array!Material materials;
    
    ///
    this(GPU gpu, Owner owner)
    {
        super(gpu, owner);
    }
    
    ///
    ~this()
    {
        release();
    }
    
    /// Releases all resources associated with the asset.
    override void release()
    {
        entities.free();
        
        foreach(mesh; meshes)
        {
            if (mesh.facegroups.length)
                Delete(mesh.facegroups);
        }
        
        meshes.free();
        materials.free();
        
        if (data.length)
            Delete(data);
    }
    
    /// Loads an asset from a given stream.
    override bool load(string filename, InputStream istrm, ReadOnlyFileSystem fs)
    {
        release();
        
        rootEntity = New!Entity(this);
        
        logDebug("Loading ", filename, "...");
        
        string rootDir = dirName(filename);
        
        char[4] magic;
        if (!istrm.fillArray(magic))
        {
            logError("loadDAF error: not a DAF file");
            return false;
        }
        
        version(DAFDebug)
            logDebug("Signature: ", magic);
        
        if (magic != "DAF\0")
        {
            logError("loadDAF error: not a DAF file");
            return false;
        }
        
        DAFHeader hdr = readStruct!DAFHeader(istrm);
        version(DAFDebug)
        {
            logDebug("Format version: ", hdr.formatVersion);
            logDebug("Flags: ", hdr.flags);
            logDebug("File size: ", hdr.fileSize);
            logDebug("Chunk table offset: ", hdr.chunkTableOffset);
            logDebug("Chunk count: ", hdr.chunkCount);
            logDebug("String table offset: ", hdr.stringTableOffset);
            logDebug("String table size: ", hdr.stringTableSize);
            logDebug("Buffers offset: ", hdr.buffersOffset);
            logDebug("Buffers size: ", hdr.buffersSize);
        }
        
        data = New!(ubyte[])(istrm.size);
        istrm.position = 0;
        istrm.fillArray(data);
        
        DAFChunk[] chunks = cast(DAFChunk[])data[hdr.chunkTableOffset..hdr.chunkTableOffset+DAFChunk.sizeof*hdr.chunkCount];
        
        string strings = cast(string)data[hdr.stringTableOffset..hdr.stringTableOffset+hdr.stringTableSize];
        version(DAFDebug)
            logDebug("Strings: ", strings);
        
        ubyte[] buffers = data[hdr.buffersOffset..hdr.buffersOffset+hdr.buffersSize];
        
        DAFEntity[] entities;
        DAFMesh[] meshes;
        DAFMaterial[] materials;
        
        foreach(chunk; chunks)
        {
            version(DAFDebug) logDebug(chunk);
            auto chunkData = data[chunk.offset..chunk.offset+chunk.stride*chunk.count];
            if (chunk.type == DAFChunkType.Entities)
                entities = cast(DAFEntity[])chunkData;
            else if (chunk.type == DAFChunkType.Meshes)
                meshes = cast(DAFMesh[])chunkData;
            else if (chunk.type == DAFChunkType.Materials)
                materials = cast(DAFMaterial[])chunkData;
        }
        
        // Create materials
        foreach(mat; materials)
        {
            string name = strings[mat.name.offset..mat.name.offset+mat.name.size];
            version(DAFDebug)
            {
                logDebug("Material: ", name);
                logDebug("  baseColor: ", mat.baseColor);
                logDebug("  roughness: ", mat.roughness);
                logDebug("  metallic: ", mat.metallic);
                logDebug("  emissionColor: ", mat.emissionColor);
                logDebug("  emissionEnergy: ", mat.emissionEnergy);
                logDebug("  ior: ", mat.ior);
                logDebug("  iorLevel: ", mat.iorLevel);
                logDebug("  subsurfaceScattering: ", mat.subsurfaceScattering);
                logDebug("  opacity: ", mat.opacity);
                logDebug("  alphaClipThreshold: ", mat.alphaClipThreshold);
                logDebug("  shadeless: ", mat.shadeless);
                logDebug("  blendMode: ", mat.blendMode);
                logDebug("  baseColorTexture: ", mat.baseColorTexture);
                logDebug("  normalTexture: ", mat.normalTexture);
                logDebug("  heightTexture: ", mat.heightTexture);
                logDebug("  roughnessMetallicTexture: ", mat.roughnessMetallicTexture);
                logDebug("  emissionTexture: ", mat.emissionTexture);
            }
            
            Material material = New!Material(this);
            material.name = name;
            material.baseColor = mat.baseColor;
            material.roughness = mat.roughness;
            material.metallic = mat.metallic;
            material.emissionColor = mat.emissionColor;
            material.emissionEnergy = mat.emissionEnergy;
            material.ior = mat.ior;
            material.iorLevel = mat.iorLevel;
            material.subsurfaceScattering = mat.subsurfaceScattering;
            material.opacity = mat.opacity;
            material.alphaClipThreshold = mat.alphaClipThreshold;
            material.shadeless = cast(bool)mat.shadeless;
            material.blendMode = mat.blendMode;
            // TODO: material.baseColorTexture
            // TODO: material.normalTexture
            // TODO: material.heightTexture
            // TODO: material.roughnessMetallicTexture
            // TODO: material.emissionTexture
            
            this.materials.append(material);
        }
        
        // Create meshes
        foreach(m; meshes)
        {
            string name = strings[m.name.offset..m.name.offset+m.name.size];
            DAFFaceGroup[] facegroups = cast(DAFFaceGroup[])buffers[m.faceGroupBuffer..m.faceGroupBuffer+DAFFaceGroup.sizeof*m.numFaceGroups];
            version(DAFDebug)
            {
                logDebug("Mesh: ", name);
                logDebug("  Number of vertices: ", m.numVertices);
                logDebug("  Number of triangles: ", m.numTriangles);
                logDebug("  Number of facegroups: ", m.numFaceGroups);
                logDebug("  Vertex buffer: ", cast(Vector3f[])buffers[m.vertexBuffer..m.vertexBuffer+Vector3f.sizeof*m.numVertices]);
                logDebug("  Normal buffer: ", cast(Vector3f[])buffers[m.normalBuffer..m.normalBuffer+Vector3f.sizeof*m.numVertices]);
                logDebug("  Texcoord buffer: ", cast(Vector2f[])buffers[m.texcoordBuffer..m.texcoordBuffer+Vector2f.sizeof*m.numVertices]);
                logDebug("  Index buffer: ", cast(uint[3][])buffers[m.indicesBuffer..m.indicesBuffer+12*m.numTriangles]);
            }
            
            Mesh mesh = New!Mesh(gpu, this);
            mesh.name = name;
            mesh.vertices = cast(Vector3f[])buffers[m.vertexBuffer..m.vertexBuffer+Vector3f.sizeof*m.numVertices];
            mesh.normals = cast(Vector3f[])buffers[m.normalBuffer..m.normalBuffer+Vector3f.sizeof*m.numVertices];
            mesh.texcoords = cast(Vector2f[])buffers[m.texcoordBuffer..m.texcoordBuffer+Vector2f.sizeof*m.numVertices];
            mesh.indices = cast(uint[3][])buffers[m.indicesBuffer..m.indicesBuffer+12*m.numTriangles];
            mesh.facegroups = New!(FaceGroup[])(facegroups.length);
            
            foreach(i, fg; facegroups)
            {
                version(DAFDebug)
                {
                    writefln("  Facegroup for material %s:", fg.material);
                    writeln("  ", fg);
                    logDebug("    Indices buffer: ", mesh.indices[fg.firstTriangle..fg.firstTriangle+fg.numTriangles]);
                }
                
                Material material = null;
                if (fg.material >= 0)
                    material = this.materials[fg.material];
                
                mesh.facegroups[i] = FaceGroup(fg.firstTriangle, fg.numTriangles, material, true);
            }
            
            mesh.dataReady = true;
            mesh.prepareBuffers();
            mesh.calcBoundingBox();
            
            this.meshes.append(mesh);
        }
        
        // Create entities
        foreach(e; entities)
        {
            string name = strings[e.name.offset..e.name.offset+e.name.size];
            version(DAFDebug)
            {
                logDebug("Entity: ", name);
                logDebug("  Parent: ", e.parent);
                logDebug("  Position: ", e.position);
                logDebug("  Rotation: ", e.rotation);
                logDebug("  Scaling: ", e.scaling);
                logDebug("  Mesh: ", e.mesh);
                logDebug("  Pose table: ", e.poseTable);
            }
            
            Entity entity = New!Entity(this);
            entity.name = name;
            entity.position = e.position;
            entity.rotation = e.rotation;
            entity.scaling = e.scaling;
            entity.transformMode = TransformMode.TRS;
            entity.dynamic = false;
            if (e.mesh >= 0)
                entity.drawable = this.meshes[e.mesh];
            this.entities.append(entity);
        }
        
        // Create parent-child links
        foreach(i, entity; this.entities)
        {
            DAFEntity e = entities[i];
            if (e.parent >= 0)
                this.entities[e.parent].addChild(entity);
            else
                rootEntity.addChild(entity);
        }
        
        return true;
    }
}
