/*
Copyright (c) 2025-2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module dagon.resource.model;

import dlib.core.memory;
import dlib.core.ownership;
import dlib.core.stream;
import dlib.container.array;
import dlib.filesystem.filesystem;

import dagon.core.gpu;
import dagon.core.assimp;
import dagon.graphics.drawable;
import dagon.graphics.state;
import dagon.graphics.entity;
import dagon.graphics.mesh;
import dagon.graphics.material;
import dagon.resource.asset;

///
class ModelAsset: Asset
{
    ///
    Entity rootEntity;
    
    ///
    Array!Entity entities;
    
    ///
    Array!Mesh meshes;
    
    ///
    this(GPU gpu, Owner owner)
    {
        super(gpu, owner);
    }
    
    ///
    ~this()
    {
        //
    }
    
    /// Releases all resources associated with the asset.
    override void release()
    {
        //
    }
    
    /// Loads an asset from a given stream.
    override bool load(string filename, InputStream istrm, ReadOnlyFileSystem fs)
    {
        //
        return false;
    }
}
