/*
Copyright (c) 2025-2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module dagon.resource.model;

import std.string;
import std.path;
import std.conv;

import dlib.core.memory;
import dlib.core.ownership;
import dlib.core.stream;
import dlib.container.array;
import dlib.container.dict;
import dlib.math.vector;
import dlib.math.matrix;
import dlib.geometry.triangle;
import dlib.image.color;
import dlib.filesystem.filesystem;
import dlib.text.str;

import dagon.core.logger;
import dagon.core.time;
import dagon.core.gpu;
import dagon.core.assimp;
import dagon.graphics.drawable;
import dagon.graphics.state;
import dagon.graphics.entity;
import dagon.graphics.mesh;
import dagon.graphics.material;
import dagon.resource.asset;
import dagon.resource.texture;

class AssimpMesh: Mesh
{
    this(GPU gpu, Owner owner)
    {
        super(gpu, owner);
    }
    
    ~this()
    {
        if (vertices.length)
            Delete(vertices);
        if (normals.length)
            Delete(normals);
        if (texcoords.length)
            Delete(texcoords);
        if (indices.length)
            Delete(indices);
        if (facegroups.length)
            Delete(facegroups);
    }
}

alias ModelConversionOptions = aiPostProcessSteps;

extern(System) size_t vfsRead(aiFile* f, char* buffer, size_t size, size_t count)
{
    if (size == 0 || count == 0) return 0;
    auto istrm = cast(InputStream)f.UserData;
    size_t bytesRead = istrm.readBytes(buffer, size * count);
    return bytesRead / size;
}

extern(System) aiReturn vfsSeek(aiFile* f, size_t offset, aiOrigin origin)
{
    auto istrm = cast(InputStream)f.UserData;
    size_t targetPos;

    switch (origin)
    {
        case aiOrigin.SET:
            targetPos = offset;
            break;
        case aiOrigin.CUR:
            targetPos = istrm.position + offset;
            break;
        case aiOrigin.END:
            targetPos = istrm.size + offset;
            break;
        default:
            return aiReturn.FAILURE;
    }

    if (targetPos <= istrm.size)
    {
        istrm.seek(targetPos);
        return aiReturn.SUCCESS;
    }
    
    return aiReturn.FAILURE;
}

extern(System) size_t vfsTell(aiFile* f)
{
    InputStream istrm = cast(InputStream)f.UserData;
    return istrm.position;
}

extern(System) size_t vfsFileSize(aiFile* f)
{
    InputStream istrm = cast(InputStream)f.UserData;
    return istrm.size;
}

extern(System) aiFile* vfsOpen(aiFileIO* io, const(char)* filePath, const(char)* mode)
{
    ReadOnlyFileSystem fs = cast(ReadOnlyFileSystem)io.UserData;
    
    InputStream istrm = fs.openForInput(filePath.to!string);
    
    aiFile* f = New!(aiFile)();
    f.ReadProc = &vfsRead;
    f.WriteProc = null;
    f.TellProc = &vfsTell;
    f.FileSizeProc = &vfsFileSize;
    f.SeekProc = &vfsSeek;
    f.FlushProc = null;
    f.UserData = cast(char*)istrm;
    
    logInfo(filePath.to!string);
    
    return f;
}

extern(System) void vfsClose(aiFileIO* io, aiFile* f)
{
    InputStream istrm = cast(InputStream)f.UserData;
    Delete(istrm);
    Delete(f);
}

///
class ModelAsset: Asset, TriangleSet
{
    ///
    Entity rootEntity;
    
    ///
    Array!Entity entities;
    
    ///
    Array!AssimpMesh meshes;
    
    ///
    Array!Material materials;
    
    ///
    Dict!(TextureAsset, string) textureAssets;
    
    ///
    ModelConversionOptions conversionOptions =
        ModelConversionOptions.Triangulate | ModelConversionOptions.FlipUVs;
    
    ///
    this(GPU gpu, Owner owner)
    {
        super(gpu, owner);
        textureAssets = dict!(TextureAsset, string)();
    }
    
    ///
    ~this()
    {
        release();
        Delete(textureAssets);
    }
    
    /// Releases all resources associated with the asset.
    override void release()
    {
        entities.free();
        meshes.free();
        materials.free();
        textureAssets.clear();
    }
    
    /// Loads an asset from a given stream.
    override bool load(string filename, InputStream istrm, ReadOnlyFileSystem fs)
    {
        release();
        
        logDebug("Loading ", filename, "...");
        
        string rootDir = dirName(filename);
        
        aiFileIO io;
        io.OpenProc = &vfsOpen;
        io.CloseProc = &vfsClose;
        io.UserData = cast(char*)fs;
        const(aiScene*) scene = aiImportFileEx(toStringz(filename), conversionOptions, &io);
        
        bool result;
        if (scene)
        {
            for (uint i = 0; i < scene.mNumMaterials; i++)
            {
                readMaterial(scene.mMaterials[i], fs, rootDir);
            }
            
            for (uint i = 0; i < scene.mNumMeshes; i++)
            {
                readMesh(scene.mMeshes[i]);
            }
            
            rootEntity = readNode(scene.mRootNode);
            
            aiReleaseImport(scene);
            result = true;
        }
        else
        {
            logError("Failed to load \"", filename, "\". ", aiGetErrorString().to!string);
            result = false;
        }
        
        foreach(e; entities)
        {
            e.update(Time(0.0, 0.0));
        }
        
        foreach(e; entities)
        {
            e.postUpdate(Time(0.0, 0.0));
        }
        
        return result;
    }
    
    protected Material readMaterial(const(aiMaterial)* material, ReadOnlyFileSystem fs, string rootDir)
    {
        Material mat = New!Material(this);
        
        mat.roughness = 1.0f;
        mat.metallic = 0.0f;
        
        aiColor4D color;
        aiString texturePath;
        
        // Read base color
        Color4f baseColor = Color4f(1.0f, 1.0f, 1.0f, 1.0f);
        if (aiGetMaterialColor(material, "$clr.base", 0, 0, &color) == aiReturn.SUCCESS)
            baseColor = fromAssimpColor(color);
        else if (aiGetMaterialColor(material, "$clr.diffuse", 0, 0, &color) == aiReturn.SUCCESS)
            baseColor = fromAssimpColor(color);
        mat.baseColor = baseColor.toGamma;
        
        // Read base color texture
        string baseColorTexturePath;
        if (aiGetMaterialTexture(material, aiTextureType.BASE_COLOR, 0, &texturePath, null, null, null, null, null, null) == aiReturn.SUCCESS)
        {
            baseColorTexturePath = texturePath.data[0..texturePath.length].idup;
            //logInfo("Base color texture path: ", baseColorTexturePath);
            if (baseColorTexturePath.length)
            {
                if (baseColorTexturePath in textureAssets)
                {
                    mat.baseColorTexture = textureAssets[baseColorTexturePath].texture;
                }
                else
                {
                    auto aBaseColorTexture = New!TextureAsset(gpu, this);
                    aBaseColorTexture.creationOptions.generateMipmaps = true;
                    aBaseColorTexture.creationOptions.repeatUV = true;
                    aBaseColorTexture.creationOptions.anisotropicFiltering = true;
                    // TODO: compression parameters
                    textureAssets[baseColorTexturePath] = aBaseColorTexture;
                    if (loadTextureAsset(aBaseColorTexture, fs, rootDir, baseColorTexturePath))
                        mat.baseColorTexture = aBaseColorTexture.texture;
                }
            }
        }
        
        // Read normal texture
        string normalTexturePath;
        if (aiGetMaterialTexture(material, aiTextureType.NORMALS, 0, &texturePath, null, null, null, null, null, null) == aiReturn.SUCCESS)
        {
            normalTexturePath = texturePath.data[0..texturePath.length].idup;
            //logInfo("Normal texture path: ", normalTexturePath);
            if (normalTexturePath.length)
            {
                if (normalTexturePath in textureAssets)
                {
                    mat.normalTexture = textureAssets[normalTexturePath].texture;
                }
                else
                {
                    auto aNormalTexture = New!TextureAsset(gpu, this);
                    aNormalTexture.creationOptions.generateMipmaps = true;
                    aNormalTexture.creationOptions.repeatUV = true;
                    aNormalTexture.creationOptions.anisotropicFiltering = true;
                    // TODO: compression parameters
                    textureAssets[normalTexturePath] = aNormalTexture;
                    if (loadTextureAsset(aNormalTexture, fs, rootDir, normalTexturePath))
                        mat.normalTexture = aNormalTexture.texture;
                }
            }
        }
        
        // Read roughness factor
        float roughness;
        if (aiGetMaterialFloat(material, "$mat.roughnessFactor", 0, 0, &roughness) == aiReturn.SUCCESS)
            mat.roughness = roughness;
        else
            mat.roughness = 1.0f;
        
        // Read metallic factor
        float metallic;
        if (aiGetMaterialFloat(material, "$mat.metallicFactor", 0, 0, &metallic) == aiReturn.SUCCESS)
            mat.metallic = metallic;
        else
            mat.metallic = 0.0f;
        
        // Read metallic-roughness texture
        string metallicRoughnessTexturePath;
        if (aiGetMaterialTexture(material, aiTextureType.GLTF_METALLIC_ROUGHNESS, 0, &texturePath, null, null, null, null, null, null) == aiReturn.SUCCESS)
        {
            metallicRoughnessTexturePath = texturePath.data[0..texturePath.length].idup;
            //logInfo("Metallic/roughness texture path: ", metallicRoughnessTexturePath);
            if (metallicRoughnessTexturePath.length)
            {
                if (metallicRoughnessTexturePath in textureAssets)
                {
                    mat.roughnessMetallicTexture = textureAssets[metallicRoughnessTexturePath].texture;
                }
                else
                {
                    auto aMetallicRoughnessTexture = New!TextureAsset(gpu, this);
                    aMetallicRoughnessTexture.creationOptions.generateMipmaps = true;
                    aMetallicRoughnessTexture.creationOptions.repeatUV = true;
                    aMetallicRoughnessTexture.creationOptions.anisotropicFiltering = true;
                    // TODO: compression parameters
                    textureAssets[normalTexturePath] = aMetallicRoughnessTexture;
                    if (loadTextureAsset(aMetallicRoughnessTexture, fs, rootDir, metallicRoughnessTexturePath))
                        mat.roughnessMetallicTexture = aMetallicRoughnessTexture.texture;
                }
            }
        }
        
        // TODO: other textures
        
        materials.insertBack(mat);
        
        return mat;
    }
    
    protected bool loadTextureAsset(TextureAsset asset, ReadOnlyFileSystem fs, string rootDir, string relPath)
    {
        String imgPath1 = String(rootDir);
        imgPath1 ~= "/";
        imgPath1 ~= relPath;
        string assetPath1 = imgPath1.toString;
        
        bool res = false;
        FileStat fstat;
        if (fs.stat(assetPath1, fstat))
        {
            InputStream istrm = fs.openForInput(assetPath1);
            res = asset.load(assetPath1, istrm, fs);
            if (!res)
                logError("Failed to load \"", assetPath1, "\"");
            Delete(istrm);
        }
        /*
        else
        {
            //TODO
            // If relPath failed (may be absolute path), try to load using baseName
            String imgPath2 = String(rootDir);
            imgPath2 ~= "/";
            imgPath2 ~= baseName(relPath);
            string assetPath2 = imgPath2.toString;
            if (fs.stat(assetPath2, fstat))
            {
                res = assetManager.loadAssetThreadSafePart(asset, assetPath2);
                if (!res)
                    logError("Failed to load \"", assetPath2, "\"");
            }
            else
                logError("Image file \"", relPath, "\" not found");
            
            imgPath2.free();
        }
        */
        
        imgPath1.free();
        
        return res;
    }
    
    protected Mesh readMesh(const(aiMesh)* mesh)
    {
        AssimpMesh m = New!AssimpMesh(gpu, this);
        auto name = mesh.mName.data[0..mesh.mName.length].idup;
        
        bool needGenNormals = false;
        
        m.vertices = New!(Vector3f[])(mesh.mNumVertices);
        
        if (mesh.mNormals is null)
        {
            needGenNormals = true;
            logWarning("Mesh \"", name, "\" has no normals (they will be generated)");
        }
        else
        {
            m.normals = New!(Vector3f[])(mesh.mNumVertices);
        }
        
        if (mesh.mTextureCoords[0] is null)
        {
            logWarning("Mesh \"", name, "\" has no texcoords");
        }
        else
        {
            m.texcoords = New!(Vector2f[])(mesh.mNumVertices);
        }
        
        m.indices = New!(uint[3][])(mesh.mNumFaces);
        
        for (uint i = 0; i < mesh.mNumVertices; ++i)
        {
            m.vertices[i] = *cast(Vector3f*)&mesh.mVertices[i];
            
            if (mesh.mNormals !is null)
                m.normals[i] = *cast(Vector3f*)&mesh.mNormals[i];
            
            if (mesh.mTextureCoords[0] !is null)
            {
                m.texcoords[i].x = mesh.mTextureCoords[0][i].x;
                m.texcoords[i].y = mesh.mTextureCoords[0][i].y;
            }
        }
        
        for (uint i = 0; i < mesh.mNumFaces; ++i)
        {
            auto face = mesh.mFaces[i];
            foreach (j; 0..face.mNumIndices)
            {
                m.indices[i][j] = face.mIndices[j];
            }
        }
        
        if (mesh.mMaterialIndex < materials.length)
        {
            m.material = materials[mesh.mMaterialIndex];
        }
        
        if (needGenNormals)
            m.generateNormals();
        
        m.calcBoundingBox();
        m.dataReady = true;
        
        m.prepareBuffers();
        
        meshes.insertBack(m);
        
        return m;
    }
    
    protected Entity readNode(const(aiNode)* node, Entity parent = null)
    {
        Entity e = New!Entity(this);
        auto name = node.mName.data[0..node.mName.length].idup;
        
        aiVector3D scaling;
        aiQuaternion rotation;
        aiVector3D position;
        aiDecomposeMatrix(&node.mTransformation, &scaling, &rotation, &position);
        
        e.position = fromAssimpVector(position);
        e.rotation = fromAssimpQuaternion(rotation);
        e.scaling = fromAssimpVector(scaling);
        
        if (parent)
            parent.addChild(e);
        
        if (node.mNumChildren > 0)
        {
            for (uint i = 0; i < node.mNumChildren; ++i)
            {
                auto childEntity = readNode(node.mChildren[i], e);
            }
        }
        
        if (node.mNumMeshes == 1)
        {
            e.drawable = meshes[node.mMeshes[0]];
        }
        else if (node.mNumMeshes > 0)
        {
            auto meshGroup = New!DrawableGroup(e);
            e.drawable = meshGroup;
            
            for (uint i = 0; i < node.mNumMeshes; ++i)
            {
                meshGroup.add(meshes[node.mMeshes[i]]);
            }
        }
        
        entities.insertBack(e);
        
        return e;
    }
    
    /**
     * Iterates over all triangles in the nodes.
     *
     * Params:
     *   dg = Delegate to call for each triangle.
     * Returns:
     *   0 if completed, nonzero if interrupted.
     */
    int opApply(scope int delegate(Triangle t) dg)
    {
        int result = 0;
        
        foreach(entity; entities)
        {
            AssimpMesh mesh = cast(AssimpMesh)entity.drawable;
            if (mesh)
            {
                foreach(i, ref f; mesh.indices)
                {
                    Triangle tri = mesh.getTriangle(i);
                    
                    Matrix4x4f mat = entity.modelMatrix;
                    
                    tri.v[0] = tri.v[0] * mat;
                    tri.v[1] = tri.v[1] * mat;
                    tri.v[2] = tri.v[2] * mat;
                    tri.n[0] = mat.rotate(tri.n[0]);
                    tri.n[1] = mat.rotate(tri.n[1]);
                    tri.n[2] = mat.rotate(tri.n[2]);
                    tri.normal = (tri.n[0] + tri.n[1] + tri.n[2]) / 3.0f;
                    
                    result = dg(tri);
                    if (result)
                        break;
                }
            }
        }
        
        return result;
    }
}
