/*
Copyright (c) 2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module dagon.resource.texture;

import std.math;
import std.string;
import std.conv;
import std.path;

import dlib.core.memory;
import dlib.core.ownership;
import dlib.core.stream;
import dlib.math.utils;
import dlib.filesystem.filesystem;

import dagon.core.sdl3;
import dagon.core.application;
import dagon.core.crashhandler;
import dagon.core.gpu;
import dagon.core.dxt;
import dagon.core.bc4;
import dagon.core.bc7;
import dagon.core.logger;
import dagon.graphics.texturebuffer;
import dagon.graphics.texture;
import dagon.graphics.lut;
import dagon.resource.asset;
import dagon.resource.image;
import dagon.resource.dds;
import dagon.resource.ktx;
import dagon.resource.hdr;
import dagon.resource.png;

///
__gshared bc7enc_compress_block_params bc7Params;

static this()
{
    bc7enc_compress_block_init();
    bc7enc_compress_block_params_init(&bc7Params);
}

// Known image file signatures
alias MagicPNG = PNGSignature;
alias MagicDDS = DDSSignature;
immutable(ubyte)[4] MagicJPEG_Raw = [0xFF, 0xD8, 0xFF, 0xDB];
immutable(ubyte)[4] MagicJPEG_JFIF = [0xFF, 0xD8, 0xFF, 0xE0];
immutable(ubyte)[4] MagicJPEG_EXIF = [0xFF, 0xD8, 0xFF, 0xE1];
immutable(ubyte)[2] MagicJPEG_XL_Naked = [0xFF, 0x0A];
immutable(ubyte)[12] MagicJPEG_XL_ISOBMFF = [0x00, 0x00, 0x00, 0x0C, 0x4A, 0x58, 0x4C, 0x20, 0x0D, 0x0A, 0x87, 0x0A];
immutable(ubyte)[11] MagicRadiance = [0x23, 0x3F, 0x52, 0x41, 0x44, 0x49, 0x41, 0x4E, 0x43, 0x45, 0x0A]; // "#?RADIANCE\n"
immutable(ubyte)[7] MagicRGBE = [0x23, 0x3F, 0x52, 0x47, 0x42, 0x45, 0x0A]; // "#?RGBE\n"
immutable(ubyte)[12] MagicKTX = [0xAB, 0x4B, 0x54, 0x58, 0x20, 0x31, 0x31, 0xBB, 0x0D, 0x0A, 0x1A, 0x0A];
immutable(ubyte)[12] MagicKTX2 = [0xAB, 0x4B, 0x54, 0x58, 0x20, 0x32, 0x30, 0xBB, 0x0D, 0x0A, 0x1A, 0x0A];
immutable(ubyte)[2] MagicBMP = [0x42, 0x4D];
immutable(ubyte)[6] MagicGIF87a = [0x47, 0x49, 0x46, 0x38, 0x37, 0x61]; // "GIF87a"
immutable(ubyte)[6] MagicGIF89a = [0x47, 0x49, 0x46, 0x38, 0x39, 0x61]; // "GIF89a"
immutable(ubyte)[4] MagicTIFF_LE = [0x49, 0x49, 0x2A, 0x00];
immutable(ubyte)[4] MagicTIFF_BE = [0x4D, 0x4D, 0x00, 0x2A];
immutable(ubyte)[4] MagicRIFF = [0x52, 0x49, 0x46, 0x46];
immutable(ubyte)[4] MagicIFF = [0x46, 0x4F, 0x52, 0x4D]; // "FORM"
immutable(ubyte)[4] MagicICO = [0x00, 0x00, 0x01, 0x00];
immutable(ubyte)[4] MagicQOI = [0x71, 0x6F, 0x69, 0x66]; // "qoif"
immutable(ubyte)[2] MagicPBM_ASCII = [0x50, 0x31]; // "P1"
immutable(ubyte)[2] MagicPGM_ASCII = [0x50, 0x32]; // "P2"
immutable(ubyte)[2] MagicPPM_ASCII = [0x50, 0x33]; // "P3"
immutable(ubyte)[2] MagicPBM_Bin = [0x50, 0x34]; // "P4"
immutable(ubyte)[2] MagicPGM_Bin = [0x50, 0x35]; // "P5"
immutable(ubyte)[2] MagicPPM_Bin = [0x50, 0x36]; // "P6"
immutable(ubyte)[2] MagicPAM = [0x50, 0x37]; // "P7"
immutable(ubyte)[8] MagicXCF = [0x67, 0x69, 0x6D, 0x70, 0x20, 0x78, 0x63, 0x66]; // "gimp xcf"
immutable(ubyte)[9] MagicXPM = [0x2F, 0x2A, 0x20, 0x58, 0x50, 0x4D, 0x20, 0x2A, 0x2F]; // "/* XPM */"
immutable(ubyte)[1] MagicPCX = [0x0A];

/// Detects image file format from magic bytes.
ImageFileFormat detectImageFileFormat(InputStream istrm)
{
    ubyte[12] magic;
    
    if (!istrm.fillArray(magic))
        // Very small file, likely corrupt
        return ImageFileFormat.Unknown;
    
    istrm.setPosition(0);

    if (magic[0..MagicPNG.length] == MagicPNG) return ImageFileFormat.PNG;
    if (magic[0..MagicJPEG_Raw.length] == MagicJPEG_Raw) return ImageFileFormat.JPEG;
    if (magic[0..MagicJPEG_JFIF.length] == MagicJPEG_JFIF) return ImageFileFormat.JPEG;
    if (magic[0..MagicJPEG_EXIF.length] == MagicJPEG_EXIF) return ImageFileFormat.JPEG;
    if (magic[0..MagicDDS.length] == MagicDDS) return ImageFileFormat.DDS;
    if (magic[0..MagicRadiance.length] == MagicRadiance) return ImageFileFormat.HDR;
    if (magic[0..MagicRGBE.length] == MagicRGBE) return ImageFileFormat.HDR;
    if (magic[0..MagicKTX.length] == MagicKTX) return ImageFileFormat.KTX;
    if (magic[0..MagicKTX2.length] == MagicKTX2) return ImageFileFormat.KTX2;
    if (magic[0..MagicRIFF.length] == MagicRIFF && magic[8..12] == [0x57, 0x45, 0x42, 0x50]) return ImageFileFormat.WebP;
    if (magic[0..MagicBMP.length] == MagicBMP) return ImageFileFormat.BMP;
    if (magic[0..MagicGIF87a.length] == MagicGIF87a || magic[0..MagicGIF89a.length] == MagicGIF89a) return ImageFileFormat.GIF;
    if (magic[0..MagicTIFF_LE.length] == MagicTIFF_LE || magic[0..MagicTIFF_BE.length] == MagicTIFF_BE) return ImageFileFormat.TIFF;
    if (magic[0..MagicICO.length] == MagicICO) return ImageFileFormat.ICO;
    if (magic[0..MagicJPEG_XL_Naked.length] == MagicJPEG_XL_Naked) return ImageFileFormat.JPEG_XL;
    if (magic[0..MagicJPEG_XL_ISOBMFF.length] == MagicJPEG_XL_ISOBMFF) return ImageFileFormat.JPEG_XL;
    if (magic[0..MagicQOI.length] == MagicQOI) return ImageFileFormat.QOI;
    if (magic[0..MagicXCF.length] == MagicXCF) return ImageFileFormat.XCF;
    if (magic[0..MagicPBM_ASCII.length] == MagicPBM_ASCII) return ImageFileFormat.PNM;
    if (magic[0..MagicPGM_ASCII.length] == MagicPGM_ASCII) return ImageFileFormat.PNM;
    if (magic[0..MagicPPM_ASCII.length] == MagicPPM_ASCII) return ImageFileFormat.PNM;
    if (magic[0..MagicPBM_Bin.length] == MagicPBM_Bin) return ImageFileFormat.PNM;
    if (magic[0..MagicPGM_Bin.length] == MagicPGM_Bin) return ImageFileFormat.PNM;
    if (magic[0..MagicPPM_Bin.length] == MagicPPM_Bin) return ImageFileFormat.PNM;
    if (magic[0..MagicPAM.length] == MagicPAM) return ImageFileFormat.PNM;
    if (magic[0..MagicXPM.length] == MagicXPM) return ImageFileFormat.XPM;
    if (magic[0..MagicPCX.length] == MagicPCX) return ImageFileFormat.PCX;
    if (magic[0..MagicIFF.length] == MagicIFF && magic[8..12] == [0x49, 0x4C, 0x42, 0x4D]) return ImageFileFormat.LBM;

    return ImageFileFormat.Unknown;
}

///
class TextureAsset: Asset
{
    ///
    ImageFileFormat fileFormat = ImageFileFormat.Unknown;
    
    ///
    TextureBuffer buffer;
    
    ///
    Texture texture;
    
    ///
    ImageConversionOptions conversionOptions;
    
    ///
    TextureCreationOptions creationOptions;
    
    ///
    this(GPU gpu, Owner owner)
    {
        super(gpu, owner);
        
        // Default conversion options
        conversionOptions.width = 0;
        conversionOptions.height = 0;
        conversionOptions.depth = 1;
        conversionOptions.compressionFormat = TextureCompressionFormat.None;
        conversionOptions.lutFormat = LUTFormat.Undefined;
        conversionOptions.hint = 0;
        
        // Default creation options
        creationOptions.generateMipmaps = false;
        creationOptions.repeatUV = false;
        creationOptions.bilinearFiltering = true;
        creationOptions.anisotropicFiltering = false;
        creationOptions.writeable = false;
    }
    
    ///
    ~this()
    {
        releaseBuffer();
    }
    
    ///
    protected void releaseBuffer()
    {
        if (buffer.data.length)
        {
            Delete(buffer.data);
            buffer.data = [];
        }
    }
    
    /// Releases all resources associated with the asset.
    override void release()
    {
        releaseBuffer();
        clearOwnedObjects();
    }
    
    ///
    override bool load(string filename, InputStream istrm, ReadOnlyFileSystem fs)
    {
        string name = filename.baseName;
        
        ubyte[] data = globalResourceCache.load(ResourceType.Texture, name, filename, &textureLoadCallback, &buffer);
        if (data.length)
        {
            Delete(data);
        }
        else
        {
            logDebug("Decoding ", filename, "...");
            
            string extension = filename.extension.toLower;
            
            // Try to detect format by magic bytes first
            fileFormat = detectImageFileFormat(istrm);
            if (fileFormat == ImageFileFormat.Unknown)
                fileFormat = imageFormatByExtension(extension);
            
            // TODO: custom loader functions that override default ones
            switch(fileFormat)
            {
                case ImageFileFormat.DDS:
                    loaded = loadDDS(istrm, &buffer);
                    break;
                case ImageFileFormat.KTX:
                    if (isImageFileFormatSupported(ImageFileFormat.KTX))
                        loaded = loadKTX1(istrm, &buffer);
                    else
                        loaded = false;
                    break;
                case ImageFileFormat.KTX2:
                    if (isImageFileFormatSupported(ImageFileFormat.KTX2))
                        loaded = loadKTX2(istrm, &buffer, cast(TranscodeHint)conversionOptions.hint);
                    else
                        loaded = false;
                    break;
                case ImageFileFormat.HDR:
                    loaded = loadHDR(istrm, &buffer);
                    break;
                case ImageFileFormat.PNG:
                    // Use custom PNG decoder because of conversion bugs in SDL_Image
                    loaded = loadPNG(istrm, &buffer);
                    break;
                default:
                    if (isSupportedImageFormat(extension))
                        loaded = loadImage(istrm, extension, &buffer, &conversionOptions);
                    else
                    {
                        loaded = false;
                        logError("Unsupported image file format");
                    }
                    break;
            }
            
            if (!loaded)
            {
                if (!persistent)
                    releaseBuffer();
                return false;
            }
            
            if (conversionOptions.compressionFormat != TextureCompressionFormat.None && 
                !buffer.format.isCompressed)
            {
                if (buffer.format.type == SDL_GPU_TEXTURETYPE_2D &&
                    buffer.format.format == SDL_GPU_TEXTUREFORMAT_R8G8B8A8_UNORM)
                {
                    logDebug("Compressing ", filename, " to ", conversionOptions.compressionFormat);
                    compressTexture();
                    creationOptions.generateMipmaps = false;
                }
                else
                {
                    logWarning(
                        filename, ": ",
                        "texture compression for type ", textureTypeStr(buffer.format.type),
                        " and format ", textureFormatStr(buffer.format.format),
                        " is not supported");
                }
            }
            else if (buffer.format.type == SDL_GPU_TEXTURETYPE_2D)
            {
                if (conversionOptions.lutFormat == LUTFormat.Hald)
                {
                    if (conversionOptions.width * conversionOptions.height * conversionOptions.depth == 
                        buffer.size.width * buffer.size.height)
                    {
                        // Interpret 2D texture as 3D texture
                        buffer.size.width = conversionOptions.width;
                        buffer.size.height = conversionOptions.height;
                        buffer.size.depth = conversionOptions.depth;
                        buffer.format.type = SDL_GPU_TEXTURETYPE_3D;
                    }
                    else
                    {
                        logError("Invalid target size for converting Hald CLUT to 3D texture");
                    }
                }
                else if (conversionOptions.lutFormat == LUTFormat.GPUImage)
                {
                    convertGPUImageLUTto3DTexture(&buffer);
                }
                else if (conversionOptions.lutFormat != LUTFormat.Undefined)
                {
                    logWarning(
                        filename, ": ",
                        "unsupported LUT format ", conversionOptions.lutFormat);
                }
            }
            
            if (cache)
                globalResourceCache.save(ResourceType.Texture, name, &textureSaveCallback, &buffer);
        }
        
        texture = New!Texture(gpu, this);
        loaded = texture.create(&buffer, &creationOptions);
        
        if (!persistent)
            releaseBuffer();
        
        return loaded;
    }
    
    ///
    protected void compressTexture()
    {
        uint width = buffer.size.width;
        uint height = buffer.size.height;
        uint numChannels = buffer.format.numChannels;
        uint pSize = buffer.format.pixelSize;
        uint mipLevels;
        
        uint blockSize;
        SDL_GPUTextureFormat newFormat;
        if (conversionOptions.compressionFormat == TextureCompressionFormat.BC1)
        {
            blockSize = 8;
            newFormat = SDL_GPU_TEXTUREFORMAT_BC1_RGBA_UNORM;
        }
        else if (conversionOptions.compressionFormat == TextureCompressionFormat.BC3)
        {
            blockSize = 16;
            newFormat = SDL_GPU_TEXTUREFORMAT_BC3_RGBA_UNORM;
        }
        else if (conversionOptions.compressionFormat == TextureCompressionFormat.BC4)
        {
            blockSize = 8;
            newFormat = SDL_GPU_TEXTUREFORMAT_BC4_R_UNORM;
        }
        else if (conversionOptions.compressionFormat == TextureCompressionFormat.BC7)
        {
            blockSize = 16;
            newFormat = SDL_GPU_TEXTUREFORMAT_BC7_RGBA_UNORM;
        }
        
        ubyte[] compressedTextureBuffer;
        
        if (creationOptions.generateMipmaps && buffer.mipLevels == 1)
        {
            mipLevels = 1 + cast(uint)floor(log2(cast(double)max2(width, height)));
            
            size_t mipChainSize = 0;
            size_t compressedMipChainSize = 0;
            uint w = width;
            uint h = height;
            foreach (level; 0..mipLevels)
            {
                mipChainSize += w * h * numChannels;
                auto blocksH = (w + 3) / 4;
                auto blocksV = (h + 3) / 4;
                size_t levelSize = blocksH * blocksV * blockSize;
                
                compressedMipChainSize += levelSize;
                w = max2(1, w / 2);
                h = max2(1, h / 2);
            }
            
            ubyte[] mipChainBuffer = New!(ubyte[])(mipChainSize);
            ubyte[] compressedMipChainBuffer = New!(ubyte[])(compressedMipChainSize);
            
            uint levelWidth = width;
            uint levelHeight = height;
            uint prevLevelWidth = levelWidth;
            uint prevLevelHeight = levelHeight;
            
            size_t offset = 0;
            size_t offsetCompressed = 0;

            ubyte[] levelSourceBuffer = buffer.data;
            foreach (level; 0..mipLevels)
            {
                size_t levelSize = levelWidth * levelHeight * numChannels;
                ubyte[] levelBufferSlice;
                
                if (level > 0)
                {
                    levelBufferSlice = mipChainBuffer[offset..offset + levelSize];
                    downsampleBox2x2(levelSourceBuffer, prevLevelWidth, prevLevelHeight, numChannels, levelBufferSlice);
                    offset += levelSize;
                }
                else
                {
                    levelBufferSlice = levelSourceBuffer[offset..offset + levelSize];
                    offset += levelSize;
                }
                
                auto blocksH = max2(1, (levelWidth + 3) / 4);
                auto blocksV = max2(1, (levelHeight + 3) / 4);
                auto levelSizeCompressed = blocksH * blocksV * blockSize;
                ubyte[] levelCompDst = compressedMipChainBuffer[offsetCompressed..offsetCompressed + levelSizeCompressed];
                
                switch(conversionOptions.compressionFormat)
                {
                    case TextureCompressionFormat.BC1:
                        dxtCompress(levelCompDst.ptr, levelBufferSlice.ptr, levelWidth, levelHeight, 0);
                        break;
                    case TextureCompressionFormat.BC3:
                        dxtCompress(levelCompDst.ptr, levelBufferSlice.ptr, levelWidth, levelHeight, 1);
                        break;
                    case TextureCompressionFormat.BC4:
                        bc4Compress(levelCompDst.ptr, levelBufferSlice.ptr, levelWidth, levelHeight, numChannels);
                        break;
                    case TextureCompressionFormat.BC7:
                        bc7Compress(levelCompDst.ptr, levelBufferSlice.ptr, levelWidth, levelHeight, &bc7Params);
                        break;
                    default:
                        exitWithError("Unsupported texture compression format: " ~ 
                            conversionOptions.compressionFormat.to!string);
                        break;
                }
                
                offsetCompressed += levelSizeCompressed;
                
                prevLevelWidth = levelWidth;
                prevLevelHeight = levelHeight;
                
                levelWidth = max2(1, levelWidth / 2);
                levelHeight = max2(1, levelHeight / 2);
                
                levelSourceBuffer = levelBufferSlice;
            }
            
            Delete(mipChainBuffer);
            
            compressedTextureBuffer = compressedMipChainBuffer;
        }
        else
        {
            mipLevels = 1;
            auto blocksH = max2(1, (width + 3) / 4);
            auto blocksV = max2(1, (height + 3) / 4);
            auto compressedDataSize = blocksH * blocksV * blockSize;
            compressedTextureBuffer = New!(ubyte[])(compressedDataSize);
            
            switch(conversionOptions.compressionFormat)
            {
                case TextureCompressionFormat.BC1:
                    dxtCompress(compressedTextureBuffer.ptr, buffer.data.ptr, width, height, 0);
                    break;
                case TextureCompressionFormat.BC3:
                    dxtCompress(compressedTextureBuffer.ptr, buffer.data.ptr, width, height, 1);
                    break;
                case TextureCompressionFormat.BC4:
                    bc4Compress(compressedTextureBuffer.ptr, buffer.data.ptr, width, height, numChannels);
                    break;
                case TextureCompressionFormat.BC7:
                    bc7Compress(compressedTextureBuffer.ptr, buffer.data.ptr, width, height, &bc7Params);
                    break;
                default:
                    exitWithError("Unsupported texture compression format: " ~ 
                        conversionOptions.compressionFormat.to!string);
                    break;
            }
        }
        
        releaseBuffer();
        buffer.data = compressedTextureBuffer;
        buffer.format.format = newFormat;
        buffer.format.blockSize = blockSize;
        buffer.mipLevels = mipLevels;
    }
}

///
bool textureSaveCallback(string path, OutputStream outputStream, void* data)
{
    return saveDDS(outputStream, cast(TextureBuffer*)data);
}

///
bool textureLoadCallback(string path, InputStream inputStream, void* data)
{
    return loadDDS(inputStream, cast(TextureBuffer*)data);
}

/// Downsamples an image by 2.
void downsampleBox2x2(ubyte[] src, uint srcW, uint srcH, uint channels, ubyte[] dst)
{
    uint dstW = srcW > 1 ? srcW / 2 : 1;
    uint dstH = srcH > 1 ? srcH / 2 : 1;
    
    foreach (y; 0..dstH)
    {
        int srcY0 = y * 2;
        int srcY1 = (srcY0 + 1 < srcH) ? srcY0 + 1 : srcY0;

        foreach (x; 0..dstW)
        {
            int srcX0 = x * 2;
            int srcX1 = (srcX0 + 1 < srcW) ? srcX0 + 1 : srcX0;

            int dstIndex = (y * dstW + x) * channels;

            int i00 = (srcY0 * srcW + srcX0) * channels;
            int i10 = (srcY0 * srcW + srcX1) * channels;
            int i01 = (srcY1 * srcW + srcX0) * channels;
            int i11 = (srcY1 * srcW + srcX1) * channels;

            foreach (c; 0..channels)
            {
                uint sum =
                    src[i00 + c] +
                    src[i10 + c] +
                    src[i01 + c] +
                    src[i11 + c];

                // Average: (sum + 2) / 4
                dst[dstIndex + c] = cast(ubyte)((sum + 2) >> 2);
            }
        }
    }
}
