// LowQuality, HighQuality, UltraQuality
profile: HighQuality;

ssao.enabled: true;
ssao.radius: 0.2;
ssao.power: 5.0;
ssao.temporalAccumulation: true;
ssao.denoise: false;
ssao.halfResolution: true;

decals.enabled: true;
selfIllumination.enabled: true;
sunLight.enabled: true;
lightVolumes.enabled: true;
fog.enabled: true;

sslr.enabled: true;
sslr.halfResolution: true;
sslr.samplingFunction: GGX_VNDF;
sslr.samples: 40;
sslr.refineSamples: 4;
sslr.maxRayDistance: 10.0;
sslr.hitThickness: 0.3;
sslr.velocitySensitivity: 50.0;
sslr.historyWeight: 0.01;
sslr.motionWeight: 1.0;
sslr.blur: false;
sslr.blurRadius: 2;

motionBlur.enabled: true;
motionBlur.samples: 16;
motionBlur.framerate: 24;
motionBlur.randomness: 0.2;
motionBlur.minDistance: 0.01;
motionBlur.maxDistance: 1.0;
motionBlur.radialBlurAmount: 0.0;

tonemapping.enabled: true;
tonemapping.look: "PunchyLegacy";

// None, FXAA, SMAA
antialiasing: SMAA;

sharpening.enabled: true;
sharpening.strength: 0.5;

lensDistortion.enabled: false;
lensDistortion.scale: 0.99;
lensDistortion.dispersion: 0.05;
lensDistortion.useRadialDistortion: false;
lensDistortion.k1: 0.01; // positive = barrel, negative = pincushion
lensDistortion.k2: 0.05;
