ssao.enabled: true;
ssao.radius: 0.2;
ssao.power: 5.0;
ssao.temporalAccumulation: true;
ssao.denoise: false;

decals.enabled: true;
selfIllumination.enabled: true;
sunLight.enabled: true;
lightVolumes.enabled: true;
fog.enabled: true;

sslr.enabled: true;

motionBlur.enabled: true;
motionBlur.samples: 16;
motionBlur.framerate: 24;
motionBlur.randomness: 0.2;
motionBlur.minDistance: 0.01;
motionBlur.maxDistance: 1.0;
motionBlur.radialBlurAmount: 0.0;

tonemapping.enabled: true;
tonemapping.look: "PunchyLegacy";

fxaa.enabled: true;

sharpening.enabled: false;
sharpening.strength: 0.5;

lensDistortion.enabled: false;
