profile: 1; // 0 = low quality, 1 = high quality, 2 = ultra quality

ssao.enabled: true;
ssao.radius: 0.2;
ssao.power: 5.0;
ssao.temporalAccumulation: false;
ssao.denoise: true;
ssao.halfResolution: false;

decals.enabled: true;
selfIllumination.enabled: true;
sunLight.enabled: true;
lightVolumes.enabled: true;
fog.enabled: true;

sslr.enabled: true;
sslr.halfResolution: false;
sslr.samples: 40;
sslr.refineSamples: 4;
sslr.maxRayDistance: 10.0;
sslr.hitThickness: 0.3;
sslr.velocitySensitivity: 100.0;
sslr.historyWeight: 0.01;
sslr.motionWeight: 1.0;
sslr.blur: true;
sslr.blurRadius: 2;

motionBlur.enabled: true;
motionBlur.samples: 16;
motionBlur.framerate: 24;
motionBlur.randomness: 0.2;
motionBlur.minDistance: 0.01;
motionBlur.maxDistance: 1.0;
motionBlur.radialBlurAmount: 0.0;

tonemapping.enabled: true;
tonemapping.look: "PunchyLegacy";

// Supported values are "FXAA", "SMAA"
// or "None" to disable
antialiasing: "SMAA";

sharpening.enabled: true;
sharpening.strength: 0.5;

lensDistortion.enabled: false;
