/*
Copyright (c) 2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module dagon.render.pass;

import dlib.core.ownership;

import dagon.core.sdl3;
import dagon.core.time;
import dagon.graphics.texture;
import dagon.graphics.state;
import dagon.resource.shader.shadermodule;
import dagon.render.renderer;
import dagon.render.view;

abstract class RenderPass: Owner
{
   public:
    Renderer renderer;
    View view;
    bool active = true;
    
   protected:
    SDL_GPURenderPass* renderPass;
    SDL_GPUColorTargetInfo* colorTargetsInfo;
    uint numColorTargets;
    SDL_GPUDepthStencilTargetInfo* depthStencilTargetInfo = null;
    bool enableDepthTarget = false;
    SDL_GPUGraphicsPipeline* graphicsPipeline;
    
   public:
    this(Renderer renderer)
    {
        super(renderer);
        this.renderer = renderer;
        renderer.addRenderPass(this);
    }
    
    ~this()
    {
        if (graphicsPipeline)
            SDL_ReleaseGPUGraphicsPipeline(renderer.gpu.device, graphicsPipeline);
    }
    
    protected void beginPass()
    {
        renderPass = SDL_BeginGPURenderPass(
            renderer.commandBuffer,
            colorTargetsInfo,
            numColorTargets,
            depthStencilTargetInfo);
        
        if (graphicsPipeline)
            SDL_BindGPUGraphicsPipeline(renderPass, graphicsPipeline);
    }
    
    protected void endPass()
    {
        if (renderPass)
            SDL_EndGPURenderPass(renderPass);
    }
    
    void bindDefaultTexture(PipelineStage stage, uint binding)
    {
        auto samplerBinding = SDL_GPUTextureSamplerBinding(renderer.gpu.defaultTexture, renderer.gpu.defaultSampler);
        
        if (stage == PipelineStage.Vertex)
            SDL_BindGPUVertexSamplers(renderPass, binding, &samplerBinding, 1);
        else if (stage == PipelineStage.Fragment)
            SDL_BindGPUFragmentSamplers(renderPass, binding, &samplerBinding, 1);
    }
    
    void bindTexture(PipelineStage stage, uint binding, SDL_GPUTexture* texture, SDL_GPUSampler* sampler)
    {
        auto samplerBinding = SDL_GPUTextureSamplerBinding(texture, sampler);
        
        if (stage == PipelineStage.Vertex)
            SDL_BindGPUVertexSamplers(renderPass, binding, &samplerBinding, 1);
        else if (stage == PipelineStage.Fragment)
            SDL_BindGPUFragmentSamplers(renderPass, binding, &samplerBinding, 1);
    }
    
    void bindInputBuffer(PipelineStage stage, uint binding, InputBuffer* buffer)
    {
        auto samplerBinding = SDL_GPUTextureSamplerBinding(buffer.texture, buffer.sampler);
        
        if (stage == PipelineStage.Vertex)
            SDL_BindGPUVertexSamplers(renderPass, binding, &samplerBinding, 1);
        else if (stage == PipelineStage.Fragment)
            SDL_BindGPUFragmentSamplers(renderPass, binding, &samplerBinding, 1);
    }
    
    void bindTexture(PipelineStage stage, uint binding, Texture texture)
    {
        auto samplerBinding = SDL_GPUTextureSamplerBinding(texture.texture, texture.sampler);
        
        if (stage == PipelineStage.Vertex)
            SDL_BindGPUVertexSamplers(renderPass, binding, &samplerBinding, 1);
        else if (stage == PipelineStage.Fragment)
            SDL_BindGPUFragmentSamplers(renderPass, binding, &samplerBinding, 1);
    }
    
    void bindUniformBuffer(PipelineStage stage, uint binding, void* data, uint size)
    {
        if (stage == PipelineStage.Vertex)
            SDL_PushGPUVertexUniformData(renderer.commandBuffer, binding, data, size);
        else if (stage == PipelineStage.Fragment)
            SDL_PushGPUFragmentUniformData(renderer.commandBuffer, binding, data, size);
    }
    
    void bindUniformBuffer(T)(PipelineStage stage, uint binding, T* uniformStruct) if (isStd140Compliant!T)
    {
        if (stage == PipelineStage.Vertex)
            SDL_PushGPUVertexUniformData(renderer.commandBuffer, binding, uniformStruct, cast(uint)T.sizeof);
        else if (stage == PipelineStage.Fragment)
            SDL_PushGPUFragmentUniformData(renderer.commandBuffer, binding, uniformStruct, cast(uint)T.sizeof);
    }
    
    // TODO: VertexBuffer class
    void bindVertexBuffer(uint slot, SDL_GPUBuffer* vertexBuffer)
    {
        SDL_GPUBufferBinding bufferBinding;
        bufferBinding.buffer = vertexBuffer;
        bufferBinding.offset = 0;
        SDL_BindGPUVertexBuffers(renderPass, slot, &bufferBinding, 1);
    }
    
    void bindIndexBuffer(SDL_GPUBuffer* indexBuffer, SDL_GPUIndexElementSize elementSize)
    {
        SDL_GPUBufferBinding bufferBinding;
        bufferBinding.buffer = indexBuffer;
        bufferBinding.offset = 0;
        SDL_BindGPUIndexBuffer(renderPass, &bufferBinding, elementSize);
    }
    
    void setStencilReference(ubyte value)
    {
        SDL_SetGPUStencilReference(renderPass, value);
    }
    
    void drawPrimitives(uint numVertices, uint numInstances, uint firstVertex, uint firstInstance)
    {
        SDL_DrawGPUPrimitives(renderPass, numVertices, numInstances, firstVertex, firstInstance);
    }
    
    void drawIndexedPrimitives(uint numIndices, uint numInstances, uint firstIndex, int vertexOffset, uint firstInstance)
    {
        SDL_DrawGPUIndexedPrimitives(renderPass, numIndices, numInstances, firstIndex, vertexOffset, firstInstance);
    }
    
    void update(Time t)
    {
        //
    }
    
    void render(GraphicsState* state)
    {
        //
    }
    
    void resize(uint width, uint height)
    {
        //
    }
}
