/*
Copyright (c) 2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

/**
 * A high-level renderer abstraction for Dagon's rendering system.
 *
 * Description:
 * The `dagon.render.renderer` module defines the basic `Renderer` class,
 * which manages render passes and serves as a base for creating
 * custom renderers.
 *
 * Copyright: Timur Gafarov 2026
 * License: $(LINK2 https://boost.org/LICENSE_1_0.txt, Boost License 1.0).
 * Authors: Timur Gafarov
 */
module dagon.render.renderer;

import dlib.core.memory;
import dlib.core.ownership;
import dlib.container.array;

import dagon.core.sdl3;
import dagon.core.gpu;
import dagon.core.logger;
import dagon.core.event;
import dagon.core.time;
import dagon.core.updateable;
import dagon.graphics.state;
import dagon.graphics.shapes;
import dagon.graphics.material;
import dagon.graphics.scene;
import dagon.render.view;
import dagon.render.pass;
import dagon.render.frametask;

/**
 * High-level renderer abstraction.
 */
abstract class Renderer: EventListener, Updateable
{
   public:
    /// GPU object.
    GPU gpu;
    
    /// GPU command buffer for rendering a frame.
    SDL_GPUCommandBuffer* commandBuffer;
    
    /// Array of render passes in order of execution.
    Array!RenderPass renderPasses;
    
    /// Quad shape for fullscreen passes.
    ShapeNormQuad screenQuad;
    
    /// Per-frame graphics pipeline state.
    GraphicsState state;
    
    /// The main render view.
    View view;
    
    /// Material used to render entities without a material.
    Material defaultMaterial;
    
    /// Inactive renderer does nothing in runtime.
    bool active = true;
    
    ///
    Array!FrameTask frameTasks;
    
    /**
     * Current swapchain texture. Can be null, because the renderer doesn't wait
     * for the valid texture to be acquired and just cancels the pipeline in such case.
     * This pointer is only reliable to use from the `render` methods of the renderer's passes.
     */
    SDL_GPUTexture* swapchainTexture;
    
    /// Current swapchain texture width, if `swapchainTexture` is not null.
    uint swapchainWidth;
    
    /// Current swapchain texture height, if `swapchainTexture` is not null.
    uint swapchainHeight;
    
   protected:
    bool minimized = false;
    bool buffersInvalidated = false;
    bool firstFrame = true;
    
   public:
    /**
     * Constructs a renderer with the given GPU and event manager.
     *
     * Params:
     *   gpu = GPU object.
     *   eventManager = Event manager.
     */
    this(GPU gpu, EventManager eventManager)
    {
        super(eventManager, gpu);
        this.gpu = gpu;
        this.screenQuad = New!ShapeNormQuad(gpu, this);
        
        uint drawableWidth = gpu.application.drawableWidth;
        uint drawableHeight = gpu.application.drawableHeight;
        this.view = New!View(drawableWidth, drawableHeight, this);
        
        defaultMaterial = New!Material(this);
    }
    
    ///
    ~this()
    {
        renderPasses.free();
        frameTasks.free();
    }
    
    ///
    void invalidateBuffers()
    {
        buffersInvalidated = true;
    }
    
    /**
     * Adds a render pass to the renderer.
     * Usually it is not needed to call this method on user side,
     * it is automatically called in RenderPass constructor.
     *
     * Params:
     *   renderPass = Render pass object.
     */
    void addRenderPass(RenderPass renderPass)
    {
        renderPasses.append(renderPass);
        renderPass.view = view;
    }
    
    ///
    void addFrameTask(FrameTask task)
    {
        frameTasks.append(task);
    }
    
    /**
     * Updates the renderer and its pipeline for the current frame.
     *
     * Params:
     *   t = Frame timing information.
     */
    void update(Time t)
    {
        processEvents();
        
        if (state.scene)
        {
            view.camera = state.scene.activeCamera;
        }
        
        view.update(t);
        
        if (firstFrame)
        {
            firstFrame = false;
            view.prevViewMatrix = view.viewMatrix;
        }
        
        state.time = t;
        
        foreach(pass; renderPasses)
        {
            pass.update(t);
        }
        
        onUpdate(t);
    }
    
    /// Renders the current frame using the pipeline and output buffer.
    void render()
    {
        if (!active || minimized)
            return;
        
        if (buffersInvalidated)
        {
            buffersInvalidated = false;
            SDL_WaitForGPUIdle(gpu.device);
            resize();
        }
        
        commandBuffer = SDL_AcquireGPUCommandBuffer(gpu.device);
        
        SDL_AcquireGPUSwapchainTexture(
            commandBuffer,
            gpu.application.window,
            &swapchainTexture,
            &swapchainWidth,
            &swapchainHeight);
        
        if (swapchainTexture is null)
        {
            SDL_CancelGPUCommandBuffer(commandBuffer);
            return;
        }
        
        foreach(i, task; frameTasks)
        {
            if (task.active)
            {
                task.submit(this);
            }
        }
        
        state.reset();
        
        foreach(i, pass; renderPasses)
        {
            if (pass.active)
            {
                state.pass = pass;
                pass.render(&state);
            }
        }
        
        SDL_SubmitGPUCommandBuffer(commandBuffer);
    }
    
    /// Override for custom post-update logic.
    void onUpdate(Time t)
    {
        foreach(i, task; frameTasks)
        {
            if (task.active)
            {
                task.update(t);
            }
        }
    }
    
    void resize()
    {
        uint drawableWidth = gpu.application.drawableWidth;
        uint drawableHeight = gpu.application.drawableHeight;
        view.resize(drawableWidth, drawableHeight);
        
        foreach(pass; renderPasses)
        {
            pass.resize(drawableWidth, drawableHeight);
        }
    }
    
    override void onResize(int width, int height)
    {
        buffersInvalidated = true;
    }
    
    override void onMinimize()
    {
        minimized = true;
    }
    
    override void onRestore()
    {
        minimized = false;
    }
    
    /**
     * Assigns a scene to the renderer.
     *
     * Params:
     *   scene = The scene to render.
     * Note:
     *   Override this method to implement custom scene assignment logic.
     */
    void setScene(Scene scene)
    {
        state.scene = scene;
    }
    
    ///
    void renderScreenQuad(GraphicsState* state)
    {
        screenQuad.render(state);
    }
}
