/*
Copyright (c) 2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

/**
 * Provides the `View` abstraction for Dagon's rendering system.
 *
 * Description:
 * The `dagon.render.view` module defines the `View` class, which
 * encapsulates camera and projection settings for a render pass.
 *
 * Copyright: Timur Gafarov 2026
 * License: $(LINK2 https://boost.org/LICENSE_1_0.txt, Boost License 1.0).
 * Authors: Timur Gafarov
 */
module dagon.render.view;

import dlib.core.ownership;
import dlib.math.vector;
import dlib.math.matrix;
import dlib.math.transformation;

import dagon.core.time;
import dagon.graphics.camera;

/**
 * Encapsulates camera and projection settings for a render pass.
 */
class View: Owner
{
    /// Matrix that brings vectors from eye space to clip space.
    Matrix4x4f projectionMatrix;
    
    /// Inverse of projectionMatrix.
    Matrix4x4f invProjectionMatrix;
    
    /// Matrix that brings vectors from world space to eye space.
    Matrix4x4f viewMatrix;
    
    /// Inverse of viewMatrix.
    Matrix4x4f invViewMatrix;
    
    /// viewMatrix from the previous frame.
    Matrix4x4f prevViewMatrix;
    
    /// Viewport width in pixels.
    uint width;
    
    /// Viewport height in pixels.
    uint height;
    
    /// Aspect ratio of the viewport.
    float aspectRatio;
    
    /// Field of view in degrees (vertical) for perspective projection.
    float fov = 60.0f;

    /// Near clipping plane distance.
    float zNear = 0.01f;

    /// Far clipping plane distance.
    float zFar = 1000.0f;
    
    /// The camera used for rendering.
    Camera camera;
    
    this(uint width, uint height, Owner owner)
    {
        super(owner);
        viewMatrix = Matrix4x4f.identity;
        invViewMatrix = Matrix4x4f.identity;
        prevViewMatrix = Matrix4x4f.identity;
        resize(width, height);
    }
    
    /// Resizes the viewport and updates the aspect ratio.
    void resize(uint width, uint height)
    {
        this.width = width;
        this.height = height;
        aspectRatio = cast(float)width / cast(float)height;
        update(Time(0.0, 0.0));
        prevViewMatrix = viewMatrix;
    }
    
    /**
     * Updates matrices for the current frame using camera transform and projection settings.
     *
     * Params:
     *   t = Frame timing information.
     */
    void update(Time t)
    {
        prevViewMatrix = viewMatrix;
        
        if (camera)
        {
            fov = camera.fov;
            zNear = camera.zNear;
            zFar = camera.zFar;
            projectionMatrix = camera.projectionMatrix(aspectRatio);
            viewMatrix = camera.viewMatrix;
            invViewMatrix = camera.invViewMatrix;
        }
        else
        {
            projectionMatrix = perspectiveMatrix(fov, aspectRatio, zNear, zFar);
            invViewMatrix = viewMatrix.inverse;
        }
        // TODO: orthographic projection support
        
        invProjectionMatrix = projectionMatrix.inverse;
    }
}
